/* Auto-generated by qjsm tools/gen-bindings.js from /usr/include/libusb-1.0/libusb.h -- do not edit by hand.
 * Regenerate with:
 *   qjsm tools/gen-bindings.js --api=cfunction --library=libusb-1.0.so.0 --structs --jsdoc  /usr/include/libusb-1.0/libusb.h
 * (clang invocation used to build the AST, once per source: clang -Xclang -ast-dump=json -fsyntax-only <source>)
 */
import { CFunction, toArrayBuffer, ptr as __ptr, toString as __cstr, dlsym, dlopen, RTLD_NOW } from 'ffi';

const __lib = dlopen("libusb-1.0.so.0", RTLD_NOW);
if (__lib == null) throw new Error("gen-bindings: dlopen(libusb-1.0.so.0) failed");

function __sym(name) {
  const p = dlsym(__lib, name);
  if(p == null) throw new Error("gen-bindings: symbol not found: " + name);
  return p;
}

const __dvs = new WeakMap();

function __dv(o) {
  let d = __dvs.get(o);
  if(!d) __dvs.set(o, (d = new DataView(o)));
  return d;
}

function __ptrOut(v) {
  return v === 0n ? null : v <= 0xffffffffn ? Number(v) : v;
}

function __ptrIn(v) {
  return v === null || v === undefined ? 0n : typeof v === "object" ? BigInt(v.ptr !== undefined ? v.ptr : __ptr(v)) : BigInt(v);
}

const __index = /^(0|[1-9]\d*)$/;

function __ptrArray(a, wrap) {
  const at = i => {
    const p = a[i];
    return p === 0n ? null : wrap ? wrap(p) : __ptrOut(p);
  };

  return new Proxy(a, {
    get(t, k) {
      if(typeof k === "string" && __index.test(k)) return Number(k) < t.length ? at(Number(k)) : undefined;
      if(k === Symbol.iterator) return function*() { for(let i = 0; i < t.length; i++) yield at(i); };

      const v = Reflect.get(t, k, t);
      return typeof v === "function" ? v.bind(t) : v;
    },
    set(t, k, v) {
      if(typeof k === "string" && __index.test(k)) {
        if(Number(k) >= t.length) return false;
        t[k] = __ptrIn(v);
        return true;
      }
      return Reflect.set(t, k, v, t);
    },
  });
}

function __bytes(v) {
  return ArrayBuffer.isView(v) ? new Uint8Array(v.buffer, v.byteOffset, v.byteLength) : new Uint8Array(v);
}

function __view(cls, p, size, owner) {
  const b = toArrayBuffer(BigInt(p), 0, size);

  Object.setPrototypeOf(b, cls.prototype);
  if(owner) Object.defineProperty(b, "__owner", { value: owner });
  return b;
}

const __sizes = { bool: 1, i8: 1, u8: 1, i16: 2, u16: 2, i32: 4, u32: 4, i64: 8, u64: 8, i64_fast: 8, u64_fast: 8, f32: 4, f64: 8, pointer: 8, ptr: 8, function: 8, cstring: 8 };

/* A type spelled "T *" is a pointer, whatever T is. */
function __sz(type) {
  return __sizes[type.endsWith("*") ? "pointer" : type];
}

function __read(dv, type, off) {
  if(type.endsWith("*")) type = "pointer";
  switch(type) {
    case "bool": return dv.getUint8(off) !== 0;
    case "i8": return dv.getInt8(off);
    case "u8": return dv.getUint8(off);
    case "i16": return dv.getInt16(off, true);
    case "u16": return dv.getUint16(off, true);
    case "i32": return dv.getInt32(off, true);
    case "u32": return dv.getUint32(off, true);
    case "i64": return dv.getBigInt64(off, true);
    case "u64": return dv.getBigUint64(off, true);
    case "i64_fast": return Number(dv.getBigInt64(off, true));
    case "u64_fast": return Number(dv.getBigUint64(off, true));
    case "f32": return dv.getFloat32(off, true);
    case "f64": return dv.getFloat64(off, true);
    case "pointer": case "ptr": case "function": return __ptrOut(dv.getBigUint64(off, true));
    case "cstring": { const p = __ptrOut(dv.getBigUint64(off, true)); return p === null ? null : __cstr(p); }
  }
}

function __write(dv, type, off, v) {
  if(type.endsWith("*")) type = "pointer";
  switch(type) {
    case "bool": return dv.setUint8(off, v ? 1 : 0);
    case "i8": return dv.setInt8(off, v);
    case "u8": return dv.setUint8(off, v);
    case "i16": return dv.setInt16(off, v, true);
    case "u16": return dv.setUint16(off, v, true);
    case "i32": return dv.setInt32(off, v, true);
    case "u32": return dv.setUint32(off, v, true);
    case "i64": case "i64_fast": return dv.setBigInt64(off, BigInt(v), true);
    case "u64": case "u64_fast": case "pointer": case "ptr": case "function": return dv.setBigUint64(off, v === null ? 0n : BigInt(v), true);
    case "f32": return dv.setFloat32(off, v, true);
    case "f64": return dv.setFloat64(off, v, true);
  }
  throw new TypeError("cannot write a " + type + " field");
}

function __variable(name, type) {
  const v = { get ptr() { return __sym(name); } };
  if(__sz(type) !== undefined) {
    const dv = () => new DataView(toArrayBuffer(__sym(name), 0, __sz(type)));
    Object.defineProperty(v, "value", { enumerable: true, get: () => __read(dv(), type, 0), set: x => __write(dv(), type, 0, x) });
  }
  return v;
}

function __ret(cls, f) {
  return (...args) => Object.setPrototypeOf(f(...args), cls.prototype);
}

// classes and structs

/* struct libusb_device_descriptor, 18 bytes (line 573) */
/**
 * struct libusb_device_descriptor, 18 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=18] - a byte length, or bytes to copy
 * @property {number} bLength - uint8_t, offset 0
 * @property {number} bDescriptorType - uint8_t, offset 1
 * @property {number} bcdUSB - uint16_t, offset 2
 * @property {number} bDeviceClass - uint8_t, offset 4
 * @property {number} bDeviceSubClass - uint8_t, offset 5
 * @property {number} bDeviceProtocol - uint8_t, offset 6
 * @property {number} bMaxPacketSize0 - uint8_t, offset 7
 * @property {number} idVendor - uint16_t, offset 8
 * @property {number} idProduct - uint16_t, offset 10
 * @property {number} bcdDevice - uint16_t, offset 12
 * @property {number} iManufacturer - uint8_t, offset 14
 * @property {number} iProduct - uint8_t, offset 15
 * @property {number} iSerialNumber - uint8_t, offset 16
 * @property {number} bNumConfigurations - uint8_t, offset 17
 */
export class libusb_device_descriptor extends ArrayBuffer {
  constructor(init = 18) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 18) { return __view(libusb_device_descriptor, p, size, owner); }
  get ptr() { return __ptr(this); }
  get bLength() { return __dv(this).getUint8(0); }
  set bLength(v) { __dv(this).setUint8(0, v); }
  get bDescriptorType() { return __dv(this).getUint8(1); }
  set bDescriptorType(v) { __dv(this).setUint8(1, v); }
  get bcdUSB() { return __dv(this).getUint16(2, true); }
  set bcdUSB(v) { __dv(this).setUint16(2, v, true); }
  get bDeviceClass() { return __dv(this).getUint8(4); }
  set bDeviceClass(v) { __dv(this).setUint8(4, v); }
  get bDeviceSubClass() { return __dv(this).getUint8(5); }
  set bDeviceSubClass(v) { __dv(this).setUint8(5, v); }
  get bDeviceProtocol() { return __dv(this).getUint8(6); }
  set bDeviceProtocol(v) { __dv(this).setUint8(6, v); }
  get bMaxPacketSize0() { return __dv(this).getUint8(7); }
  set bMaxPacketSize0(v) { __dv(this).setUint8(7, v); }
  get idVendor() { return __dv(this).getUint16(8, true); }
  set idVendor(v) { __dv(this).setUint16(8, v, true); }
  get idProduct() { return __dv(this).getUint16(10, true); }
  set idProduct(v) { __dv(this).setUint16(10, v, true); }
  get bcdDevice() { return __dv(this).getUint16(12, true); }
  set bcdDevice(v) { __dv(this).setUint16(12, v, true); }
  get iManufacturer() { return __dv(this).getUint8(14); }
  set iManufacturer(v) { __dv(this).setUint8(14, v); }
  get iProduct() { return __dv(this).getUint8(15); }
  set iProduct(v) { __dv(this).setUint8(15, v); }
  get iSerialNumber() { return __dv(this).getUint8(16); }
  set iSerialNumber(v) { __dv(this).setUint8(16, v); }
  get bNumConfigurations() { return __dv(this).getUint8(17); }
  set bNumConfigurations(v) { __dv(this).setUint8(17, v); }
}
libusb_device_descriptor.size = 18;
libusb_device_descriptor.align = 2;
libusb_device_descriptor.fields = {bLength:{type:'u8',offset:0},bDescriptorType:{type:'u8',offset:1},bcdUSB:{type:'u16',offset:2},bDeviceClass:{type:'u8',offset:4},bDeviceSubClass:{type:'u8',offset:5},bDeviceProtocol:{type:'u8',offset:6},bMaxPacketSize0:{type:'u8',offset:7},idVendor:{type:'u16',offset:8},idProduct:{type:'u16',offset:10},bcdDevice:{type:'u16',offset:12},iManufacturer:{type:'u8',offset:14},iProduct:{type:'u8',offset:15},iSerialNumber:{type:'u8',offset:16},bNumConfigurations:{type:'u8',offset:17}};

/* struct libusb_endpoint_descriptor, 32 bytes (line 627) */
/**
 * struct libusb_endpoint_descriptor, 32 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=32] - a byte length, or bytes to copy
 * @property {number} bLength - uint8_t, offset 0
 * @property {number} bDescriptorType - uint8_t, offset 1
 * @property {number} bEndpointAddress - uint8_t, offset 2
 * @property {number} bmAttributes - uint8_t, offset 3
 * @property {number} wMaxPacketSize - uint16_t, offset 4
 * @property {number} bInterval - uint8_t, offset 6
 * @property {number} bRefresh - uint8_t, offset 7
 * @property {number} bSynchAddress - uint8_t, offset 8
 * @property {number|bigint|null} extra - const unsigned char *, offset 16
 * @property {number} extra_length - int, offset 24
 */
export class libusb_endpoint_descriptor extends ArrayBuffer {
  constructor(init = 32) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 32) { return __view(libusb_endpoint_descriptor, p, size, owner); }
  get ptr() { return __ptr(this); }
  get bLength() { return __dv(this).getUint8(0); }
  set bLength(v) { __dv(this).setUint8(0, v); }
  get bDescriptorType() { return __dv(this).getUint8(1); }
  set bDescriptorType(v) { __dv(this).setUint8(1, v); }
  get bEndpointAddress() { return __dv(this).getUint8(2); }
  set bEndpointAddress(v) { __dv(this).setUint8(2, v); }
  get bmAttributes() { return __dv(this).getUint8(3); }
  set bmAttributes(v) { __dv(this).setUint8(3, v); }
  get wMaxPacketSize() { return __dv(this).getUint16(4, true); }
  set wMaxPacketSize(v) { __dv(this).setUint16(4, v, true); }
  get bInterval() { return __dv(this).getUint8(6); }
  set bInterval(v) { __dv(this).setUint8(6, v); }
  get bRefresh() { return __dv(this).getUint8(7); }
  set bRefresh(v) { __dv(this).setUint8(7, v); }
  get bSynchAddress() { return __dv(this).getUint8(8); }
  set bSynchAddress(v) { __dv(this).setUint8(8, v); }
  get extra() { return __ptrOut(__dv(this).getBigUint64(16, true)); }
  set extra(v) { __dv(this).setBigUint64(16, __ptrIn(v), true); }
  get extra_length() { return __dv(this).getInt32(24, true); }
  set extra_length(v) { __dv(this).setInt32(24, v, true); }
}
libusb_endpoint_descriptor.size = 32;
libusb_endpoint_descriptor.align = 8;
libusb_endpoint_descriptor.fields = {bLength:{type:'u8',offset:0},bDescriptorType:{type:'u8',offset:1},bEndpointAddress:{type:'u8',offset:2},bmAttributes:{type:'u8',offset:3},wMaxPacketSize:{type:'u16',offset:4},bInterval:{type:'u8',offset:6},bRefresh:{type:'u8',offset:7},bSynchAddress:{type:'u8',offset:8},extra:{type:'unsigned char *',offset:16},extra_length:{type:'i32',offset:24}};

/* struct libusb_interface_association_descriptor, 8 bytes (line 675) */
/**
 * struct libusb_interface_association_descriptor, 8 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=8] - a byte length, or bytes to copy
 * @property {number} bLength - uint8_t, offset 0
 * @property {number} bDescriptorType - uint8_t, offset 1
 * @property {number} bFirstInterface - uint8_t, offset 2
 * @property {number} bInterfaceCount - uint8_t, offset 3
 * @property {number} bFunctionClass - uint8_t, offset 4
 * @property {number} bFunctionSubClass - uint8_t, offset 5
 * @property {number} bFunctionProtocol - uint8_t, offset 6
 * @property {number} iFunction - uint8_t, offset 7
 */
export class libusb_interface_association_descriptor extends ArrayBuffer {
  constructor(init = 8) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 8) { return __view(libusb_interface_association_descriptor, p, size, owner); }
  get ptr() { return __ptr(this); }
  get bLength() { return __dv(this).getUint8(0); }
  set bLength(v) { __dv(this).setUint8(0, v); }
  get bDescriptorType() { return __dv(this).getUint8(1); }
  set bDescriptorType(v) { __dv(this).setUint8(1, v); }
  get bFirstInterface() { return __dv(this).getUint8(2); }
  set bFirstInterface(v) { __dv(this).setUint8(2, v); }
  get bInterfaceCount() { return __dv(this).getUint8(3); }
  set bInterfaceCount(v) { __dv(this).setUint8(3, v); }
  get bFunctionClass() { return __dv(this).getUint8(4); }
  set bFunctionClass(v) { __dv(this).setUint8(4, v); }
  get bFunctionSubClass() { return __dv(this).getUint8(5); }
  set bFunctionSubClass(v) { __dv(this).setUint8(5, v); }
  get bFunctionProtocol() { return __dv(this).getUint8(6); }
  set bFunctionProtocol(v) { __dv(this).setUint8(6, v); }
  get iFunction() { return __dv(this).getUint8(7); }
  set iFunction(v) { __dv(this).setUint8(7, v); }
}
libusb_interface_association_descriptor.size = 8;
libusb_interface_association_descriptor.align = 1;
libusb_interface_association_descriptor.fields = {bLength:{type:'u8',offset:0},bDescriptorType:{type:'u8',offset:1},bFirstInterface:{type:'u8',offset:2},bInterfaceCount:{type:'u8',offset:3},bFunctionClass:{type:'u8',offset:4},bFunctionSubClass:{type:'u8',offset:5},bFunctionProtocol:{type:'u8',offset:6},iFunction:{type:'u8',offset:7}};

/* struct libusb_interface_association_descriptor_array, 16 bytes (line 719) */
/**
 * struct libusb_interface_association_descriptor_array, 16 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=16] - a byte length, or bytes to copy
 * @property {libusb_interface_association_descriptor|null} iad - const struct libusb_interface_association_descriptor *, offset 0
 * @property {number} length - int, offset 8
 */
export class libusb_interface_association_descriptor_array extends ArrayBuffer {
  constructor(init = 16) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 16) { return __view(libusb_interface_association_descriptor_array, p, size, owner); }
  get ptr() { return __ptr(this); }
  get iad() { const p = __dv(this).getBigUint64(0, true); return p === 0n ? null : libusb_interface_association_descriptor.at(p); }
  set iad(v) { __dv(this).setBigUint64(0, __ptrIn(v), true); }
  get length() { return __dv(this).getInt32(8, true); }
  set length(v) { __dv(this).setInt32(8, v, true); }
}
libusb_interface_association_descriptor_array.size = 16;
libusb_interface_association_descriptor_array.align = 8;
libusb_interface_association_descriptor_array.fields = {iad:{type:'struct libusb_interface_association_descriptor *',offset:0},length:{type:'i32',offset:8}};

/* struct libusb_interface_descriptor, 40 bytes (line 734) */
/**
 * struct libusb_interface_descriptor, 40 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=40] - a byte length, or bytes to copy
 * @property {number} bLength - uint8_t, offset 0
 * @property {number} bDescriptorType - uint8_t, offset 1
 * @property {number} bInterfaceNumber - uint8_t, offset 2
 * @property {number} bAlternateSetting - uint8_t, offset 3
 * @property {number} bNumEndpoints - uint8_t, offset 4
 * @property {number} bInterfaceClass - uint8_t, offset 5
 * @property {number} bInterfaceSubClass - uint8_t, offset 6
 * @property {number} bInterfaceProtocol - uint8_t, offset 7
 * @property {number} iInterface - uint8_t, offset 8
 * @property {libusb_endpoint_descriptor|null} endpoint - const struct libusb_endpoint_descriptor *, offset 16
 * @property {number|bigint|null} extra - const unsigned char *, offset 24
 * @property {number} extra_length - int, offset 32
 */
export class libusb_interface_descriptor extends ArrayBuffer {
  constructor(init = 40) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 40) { return __view(libusb_interface_descriptor, p, size, owner); }
  get ptr() { return __ptr(this); }
  get bLength() { return __dv(this).getUint8(0); }
  set bLength(v) { __dv(this).setUint8(0, v); }
  get bDescriptorType() { return __dv(this).getUint8(1); }
  set bDescriptorType(v) { __dv(this).setUint8(1, v); }
  get bInterfaceNumber() { return __dv(this).getUint8(2); }
  set bInterfaceNumber(v) { __dv(this).setUint8(2, v); }
  get bAlternateSetting() { return __dv(this).getUint8(3); }
  set bAlternateSetting(v) { __dv(this).setUint8(3, v); }
  get bNumEndpoints() { return __dv(this).getUint8(4); }
  set bNumEndpoints(v) { __dv(this).setUint8(4, v); }
  get bInterfaceClass() { return __dv(this).getUint8(5); }
  set bInterfaceClass(v) { __dv(this).setUint8(5, v); }
  get bInterfaceSubClass() { return __dv(this).getUint8(6); }
  set bInterfaceSubClass(v) { __dv(this).setUint8(6, v); }
  get bInterfaceProtocol() { return __dv(this).getUint8(7); }
  set bInterfaceProtocol(v) { __dv(this).setUint8(7, v); }
  get iInterface() { return __dv(this).getUint8(8); }
  set iInterface(v) { __dv(this).setUint8(8, v); }
  get endpoint() { const p = __dv(this).getBigUint64(16, true); return p === 0n ? null : libusb_endpoint_descriptor.at(p); }
  set endpoint(v) { __dv(this).setBigUint64(16, __ptrIn(v), true); }
  get extra() { return __ptrOut(__dv(this).getBigUint64(24, true)); }
  set extra(v) { __dv(this).setBigUint64(24, __ptrIn(v), true); }
  get extra_length() { return __dv(this).getInt32(32, true); }
  set extra_length(v) { __dv(this).setInt32(32, v, true); }
}
libusb_interface_descriptor.size = 40;
libusb_interface_descriptor.align = 8;
libusb_interface_descriptor.fields = {bLength:{type:'u8',offset:0},bDescriptorType:{type:'u8',offset:1},bInterfaceNumber:{type:'u8',offset:2},bAlternateSetting:{type:'u8',offset:3},bNumEndpoints:{type:'u8',offset:4},bInterfaceClass:{type:'u8',offset:5},bInterfaceSubClass:{type:'u8',offset:6},bInterfaceProtocol:{type:'u8',offset:7},iInterface:{type:'u8',offset:8},endpoint:{type:'struct libusb_endpoint_descriptor *',offset:16},extra:{type:'unsigned char *',offset:24},extra_length:{type:'i32',offset:32}};

/* struct libusb_interface, 16 bytes (line 782) */
/**
 * struct libusb_interface, 16 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=16] - a byte length, or bytes to copy
 * @property {libusb_interface_descriptor|null} altsetting - const struct libusb_interface_descriptor *, offset 0
 * @property {number} num_altsetting - int, offset 8
 */
export class libusb_interface extends ArrayBuffer {
  constructor(init = 16) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 16) { return __view(libusb_interface, p, size, owner); }
  get ptr() { return __ptr(this); }
  get altsetting() { const p = __dv(this).getBigUint64(0, true); return p === 0n ? null : libusb_interface_descriptor.at(p); }
  set altsetting(v) { __dv(this).setBigUint64(0, __ptrIn(v), true); }
  get num_altsetting() { return __dv(this).getInt32(8, true); }
  set num_altsetting(v) { __dv(this).setInt32(8, v, true); }
}
libusb_interface.size = 16;
libusb_interface.align = 8;
libusb_interface.fields = {altsetting:{type:'struct libusb_interface_descriptor *',offset:0},num_altsetting:{type:'i32',offset:8}};

/* struct libusb_config_descriptor, 40 bytes (line 797) */
/**
 * struct libusb_config_descriptor, 40 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=40] - a byte length, or bytes to copy
 * @property {number} bLength - uint8_t, offset 0
 * @property {number} bDescriptorType - uint8_t, offset 1
 * @property {number} wTotalLength - uint16_t, offset 2
 * @property {number} bNumInterfaces - uint8_t, offset 4
 * @property {number} bConfigurationValue - uint8_t, offset 5
 * @property {number} iConfiguration - uint8_t, offset 6
 * @property {number} bmAttributes - uint8_t, offset 7
 * @property {number} MaxPower - uint8_t, offset 8
 * @property {libusb_interface|null} interface - const struct libusb_interface *, offset 16
 * @property {number|bigint|null} extra - const unsigned char *, offset 24
 * @property {number} extra_length - int, offset 32
 */
export class libusb_config_descriptor extends ArrayBuffer {
  constructor(init = 40) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 40) { return __view(libusb_config_descriptor, p, size, owner); }
  get ptr() { return __ptr(this); }
  get bLength() { return __dv(this).getUint8(0); }
  set bLength(v) { __dv(this).setUint8(0, v); }
  get bDescriptorType() { return __dv(this).getUint8(1); }
  set bDescriptorType(v) { __dv(this).setUint8(1, v); }
  get wTotalLength() { return __dv(this).getUint16(2, true); }
  set wTotalLength(v) { __dv(this).setUint16(2, v, true); }
  get bNumInterfaces() { return __dv(this).getUint8(4); }
  set bNumInterfaces(v) { __dv(this).setUint8(4, v); }
  get bConfigurationValue() { return __dv(this).getUint8(5); }
  set bConfigurationValue(v) { __dv(this).setUint8(5, v); }
  get iConfiguration() { return __dv(this).getUint8(6); }
  set iConfiguration(v) { __dv(this).setUint8(6, v); }
  get bmAttributes() { return __dv(this).getUint8(7); }
  set bmAttributes(v) { __dv(this).setUint8(7, v); }
  get MaxPower() { return __dv(this).getUint8(8); }
  set MaxPower(v) { __dv(this).setUint8(8, v); }
  get interface() { const p = __dv(this).getBigUint64(16, true); return p === 0n ? null : libusb_interface.at(p); }
  set interface(v) { __dv(this).setBigUint64(16, __ptrIn(v), true); }
  get extra() { return __ptrOut(__dv(this).getBigUint64(24, true)); }
  set extra(v) { __dv(this).setBigUint64(24, __ptrIn(v), true); }
  get extra_length() { return __dv(this).getInt32(32, true); }
  set extra_length(v) { __dv(this).setInt32(32, v, true); }
}
libusb_config_descriptor.size = 40;
libusb_config_descriptor.align = 8;
libusb_config_descriptor.fields = {bLength:{type:'u8',offset:0},bDescriptorType:{type:'u8',offset:1},wTotalLength:{type:'u16',offset:2},bNumInterfaces:{type:'u8',offset:4},bConfigurationValue:{type:'u8',offset:5},iConfiguration:{type:'u8',offset:6},bmAttributes:{type:'u8',offset:7},MaxPower:{type:'u8',offset:8},interface:{type:'struct libusb_interface *',offset:16},extra:{type:'unsigned char *',offset:24},extra_length:{type:'i32',offset:32}};

/* struct libusb_ss_endpoint_companion_descriptor, 6 bytes (line 845) */
/**
 * struct libusb_ss_endpoint_companion_descriptor, 6 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=6] - a byte length, or bytes to copy
 * @property {number} bLength - uint8_t, offset 0
 * @property {number} bDescriptorType - uint8_t, offset 1
 * @property {number} bMaxBurst - uint8_t, offset 2
 * @property {number} bmAttributes - uint8_t, offset 3
 * @property {number} wBytesPerInterval - uint16_t, offset 4
 */
export class libusb_ss_endpoint_companion_descriptor extends ArrayBuffer {
  constructor(init = 6) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 6) { return __view(libusb_ss_endpoint_companion_descriptor, p, size, owner); }
  get ptr() { return __ptr(this); }
  get bLength() { return __dv(this).getUint8(0); }
  set bLength(v) { __dv(this).setUint8(0, v); }
  get bDescriptorType() { return __dv(this).getUint8(1); }
  set bDescriptorType(v) { __dv(this).setUint8(1, v); }
  get bMaxBurst() { return __dv(this).getUint8(2); }
  set bMaxBurst(v) { __dv(this).setUint8(2, v); }
  get bmAttributes() { return __dv(this).getUint8(3); }
  set bmAttributes(v) { __dv(this).setUint8(3, v); }
  get wBytesPerInterval() { return __dv(this).getUint16(4, true); }
  set wBytesPerInterval(v) { __dv(this).setUint16(4, v, true); }
}
libusb_ss_endpoint_companion_descriptor.size = 6;
libusb_ss_endpoint_companion_descriptor.align = 2;
libusb_ss_endpoint_companion_descriptor.fields = {bLength:{type:'u8',offset:0},bDescriptorType:{type:'u8',offset:1},bMaxBurst:{type:'u8',offset:2},bmAttributes:{type:'u8',offset:3},wBytesPerInterval:{type:'u16',offset:4}};

/* struct libusb_bos_dev_capability_descriptor, 3 bytes (line 874) */
/**
 * struct libusb_bos_dev_capability_descriptor, 3 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=3] - a byte length, or bytes to copy
 * @property {number} bLength - uint8_t, offset 0
 * @property {number} bDescriptorType - uint8_t, offset 1
 * @property {number} bDevCapabilityType - uint8_t, offset 2
 */
export class libusb_bos_dev_capability_descriptor extends ArrayBuffer {
  constructor(init = 3) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 3) { return __view(libusb_bos_dev_capability_descriptor, p, size, owner); }
  get ptr() { return __ptr(this); }
  get bLength() { return __dv(this).getUint8(0); }
  set bLength(v) { __dv(this).setUint8(0, v); }
  get bDescriptorType() { return __dv(this).getUint8(1); }
  set bDescriptorType(v) { __dv(this).setUint8(1, v); }
  get bDevCapabilityType() { return __dv(this).getUint8(2); }
  set bDevCapabilityType(v) { __dv(this).setUint8(2, v); }
  // dev_capability_data: size unknown
}
libusb_bos_dev_capability_descriptor.size = 3;
libusb_bos_dev_capability_descriptor.align = 1;
libusb_bos_dev_capability_descriptor.fields = {bLength:{type:'u8',offset:0},bDescriptorType:{type:'u8',offset:1},bDevCapabilityType:{type:'u8',offset:2},dev_capability_data:{type:'uint8_t[]',offset:3}};

/* struct libusb_bos_descriptor, 8 bytes (line 895) */
/**
 * struct libusb_bos_descriptor, 8 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=8] - a byte length, or bytes to copy
 * @property {number} bLength - uint8_t, offset 0
 * @property {number} bDescriptorType - uint8_t, offset 1
 * @property {number} wTotalLength - uint16_t, offset 2
 * @property {number} bNumDeviceCaps - uint8_t, offset 4
 */
export class libusb_bos_descriptor extends ArrayBuffer {
  constructor(init = 8) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 8) { return __view(libusb_bos_descriptor, p, size, owner); }
  get ptr() { return __ptr(this); }
  get bLength() { return __dv(this).getUint8(0); }
  set bLength(v) { __dv(this).setUint8(0, v); }
  get bDescriptorType() { return __dv(this).getUint8(1); }
  set bDescriptorType(v) { __dv(this).setUint8(1, v); }
  get wTotalLength() { return __dv(this).getUint16(2, true); }
  set wTotalLength(v) { __dv(this).setUint16(2, v, true); }
  get bNumDeviceCaps() { return __dv(this).getUint8(4); }
  set bNumDeviceCaps(v) { __dv(this).setUint8(4, v); }
  // dev_capability: size unknown
}
libusb_bos_descriptor.size = 8;
libusb_bos_descriptor.align = 8;
libusb_bos_descriptor.fields = {bLength:{type:'u8',offset:0},bDescriptorType:{type:'u8',offset:1},wTotalLength:{type:'u16',offset:2},bNumDeviceCaps:{type:'u8',offset:4},dev_capability:{type:'struct libusb_bos_dev_capability_descriptor *[]',offset:8}};

/* struct libusb_usb_2_0_extension_descriptor, 8 bytes (line 920) */
/**
 * struct libusb_usb_2_0_extension_descriptor, 8 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=8] - a byte length, or bytes to copy
 * @property {number} bLength - uint8_t, offset 0
 * @property {number} bDescriptorType - uint8_t, offset 1
 * @property {number} bDevCapabilityType - uint8_t, offset 2
 * @property {number} bmAttributes - uint32_t, offset 4
 */
export class libusb_usb_2_0_extension_descriptor extends ArrayBuffer {
  constructor(init = 8) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 8) { return __view(libusb_usb_2_0_extension_descriptor, p, size, owner); }
  get ptr() { return __ptr(this); }
  get bLength() { return __dv(this).getUint8(0); }
  set bLength(v) { __dv(this).setUint8(0, v); }
  get bDescriptorType() { return __dv(this).getUint8(1); }
  set bDescriptorType(v) { __dv(this).setUint8(1, v); }
  get bDevCapabilityType() { return __dv(this).getUint8(2); }
  set bDevCapabilityType(v) { __dv(this).setUint8(2, v); }
  get bmAttributes() { return __dv(this).getUint32(4, true); }
  set bmAttributes(v) { __dv(this).setUint32(4, v, true); }
}
libusb_usb_2_0_extension_descriptor.size = 8;
libusb_usb_2_0_extension_descriptor.align = 4;
libusb_usb_2_0_extension_descriptor.fields = {bLength:{type:'u8',offset:0},bDescriptorType:{type:'u8',offset:1},bDevCapabilityType:{type:'u8',offset:2},bmAttributes:{type:'u32',offset:4}};

/* struct libusb_ss_usb_device_capability_descriptor, 10 bytes (line 946) */
/**
 * struct libusb_ss_usb_device_capability_descriptor, 10 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=10] - a byte length, or bytes to copy
 * @property {number} bLength - uint8_t, offset 0
 * @property {number} bDescriptorType - uint8_t, offset 1
 * @property {number} bDevCapabilityType - uint8_t, offset 2
 * @property {number} bmAttributes - uint8_t, offset 3
 * @property {number} wSpeedSupported - uint16_t, offset 4
 * @property {number} bFunctionalitySupport - uint8_t, offset 6
 * @property {number} bU1DevExitLat - uint8_t, offset 7
 * @property {number} bU2DevExitLat - uint16_t, offset 8
 */
export class libusb_ss_usb_device_capability_descriptor extends ArrayBuffer {
  constructor(init = 10) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 10) { return __view(libusb_ss_usb_device_capability_descriptor, p, size, owner); }
  get ptr() { return __ptr(this); }
  get bLength() { return __dv(this).getUint8(0); }
  set bLength(v) { __dv(this).setUint8(0, v); }
  get bDescriptorType() { return __dv(this).getUint8(1); }
  set bDescriptorType(v) { __dv(this).setUint8(1, v); }
  get bDevCapabilityType() { return __dv(this).getUint8(2); }
  set bDevCapabilityType(v) { __dv(this).setUint8(2, v); }
  get bmAttributes() { return __dv(this).getUint8(3); }
  set bmAttributes(v) { __dv(this).setUint8(3, v); }
  get wSpeedSupported() { return __dv(this).getUint16(4, true); }
  set wSpeedSupported(v) { __dv(this).setUint16(4, v, true); }
  get bFunctionalitySupport() { return __dv(this).getUint8(6); }
  set bFunctionalitySupport(v) { __dv(this).setUint8(6, v); }
  get bU1DevExitLat() { return __dv(this).getUint8(7); }
  set bU1DevExitLat(v) { __dv(this).setUint8(7, v); }
  get bU2DevExitLat() { return __dv(this).getUint16(8, true); }
  set bU2DevExitLat(v) { __dv(this).setUint16(8, v, true); }
}
libusb_ss_usb_device_capability_descriptor.size = 10;
libusb_ss_usb_device_capability_descriptor.align = 2;
libusb_ss_usb_device_capability_descriptor.fields = {bLength:{type:'u8',offset:0},bDescriptorType:{type:'u8',offset:1},bDevCapabilityType:{type:'u8',offset:2},bmAttributes:{type:'u8',offset:3},wSpeedSupported:{type:'u16',offset:4},bFunctionalitySupport:{type:'u8',offset:6},bU1DevExitLat:{type:'u8',offset:7},bU2DevExitLat:{type:'u16',offset:8}};

/* struct libusb_container_id_descriptor, 20 bytes (line 988) */
/**
 * struct libusb_container_id_descriptor, 20 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=20] - a byte length, or bytes to copy
 * @property {number} bLength - uint8_t, offset 0
 * @property {number} bDescriptorType - uint8_t, offset 1
 * @property {number} bDevCapabilityType - uint8_t, offset 2
 * @property {number} bReserved - uint8_t, offset 3
 * @property {Uint8Array} ContainerID - uint8_t[16], offset 4
 */
export class libusb_container_id_descriptor extends ArrayBuffer {
  constructor(init = 20) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 20) { return __view(libusb_container_id_descriptor, p, size, owner); }
  get ptr() { return __ptr(this); }
  get bLength() { return __dv(this).getUint8(0); }
  set bLength(v) { __dv(this).setUint8(0, v); }
  get bDescriptorType() { return __dv(this).getUint8(1); }
  set bDescriptorType(v) { __dv(this).setUint8(1, v); }
  get bDevCapabilityType() { return __dv(this).getUint8(2); }
  set bDevCapabilityType(v) { __dv(this).setUint8(2, v); }
  get bReserved() { return __dv(this).getUint8(3); }
  set bReserved(v) { __dv(this).setUint8(3, v); }
  get ContainerID() { return new Uint8Array(this, 4, 16); }
  set ContainerID(v) { new Uint8Array(this, 4, 16).set(v); }
}
libusb_container_id_descriptor.size = 20;
libusb_container_id_descriptor.align = 1;
libusb_container_id_descriptor.fields = {bLength:{type:'u8',offset:0},bDescriptorType:{type:'u8',offset:1},bDevCapabilityType:{type:'u8',offset:2},bReserved:{type:'u8',offset:3},ContainerID:{type:'uint8_t[16]',offset:4}};

/* struct libusb_platform_descriptor, 20 bytes (line 1013) */
/**
 * struct libusb_platform_descriptor, 20 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=20] - a byte length, or bytes to copy
 * @property {number} bLength - uint8_t, offset 0
 * @property {number} bDescriptorType - uint8_t, offset 1
 * @property {number} bDevCapabilityType - uint8_t, offset 2
 * @property {number} bReserved - uint8_t, offset 3
 * @property {Uint8Array} PlatformCapabilityUUID - uint8_t[16], offset 4
 */
export class libusb_platform_descriptor extends ArrayBuffer {
  constructor(init = 20) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 20) { return __view(libusb_platform_descriptor, p, size, owner); }
  get ptr() { return __ptr(this); }
  get bLength() { return __dv(this).getUint8(0); }
  set bLength(v) { __dv(this).setUint8(0, v); }
  get bDescriptorType() { return __dv(this).getUint8(1); }
  set bDescriptorType(v) { __dv(this).setUint8(1, v); }
  get bDevCapabilityType() { return __dv(this).getUint8(2); }
  set bDevCapabilityType(v) { __dv(this).setUint8(2, v); }
  get bReserved() { return __dv(this).getUint8(3); }
  set bReserved(v) { __dv(this).setUint8(3, v); }
  get PlatformCapabilityUUID() { return new Uint8Array(this, 4, 16); }
  set PlatformCapabilityUUID(v) { new Uint8Array(this, 4, 16).set(v); }
  // CapabilityData: size unknown
}
libusb_platform_descriptor.size = 20;
libusb_platform_descriptor.align = 1;
libusb_platform_descriptor.fields = {bLength:{type:'u8',offset:0},bDescriptorType:{type:'u8',offset:1},bDevCapabilityType:{type:'u8',offset:2},bReserved:{type:'u8',offset:3},PlatformCapabilityUUID:{type:'uint8_t[16]',offset:4},CapabilityData:{type:'uint8_t[]',offset:20}};

/* struct libusb_control_setup, 8 bytes (line 1042) */
/**
 * struct libusb_control_setup, 8 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=8] - a byte length, or bytes to copy
 * @property {number} bmRequestType - uint8_t, offset 0
 * @property {number} bRequest - uint8_t, offset 1
 * @property {number} wValue - uint16_t, offset 2
 * @property {number} wIndex - uint16_t, offset 4
 * @property {number} wLength - uint16_t, offset 6
 */
export class libusb_control_setup extends ArrayBuffer {
  constructor(init = 8) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 8) { return __view(libusb_control_setup, p, size, owner); }
  get ptr() { return __ptr(this); }
  get bmRequestType() { return __dv(this).getUint8(0); }
  set bmRequestType(v) { __dv(this).setUint8(0, v); }
  get bRequest() { return __dv(this).getUint8(1); }
  set bRequest(v) { __dv(this).setUint8(1, v); }
  get wValue() { return __dv(this).getUint16(2, true); }
  set wValue(v) { __dv(this).setUint16(2, v, true); }
  get wIndex() { return __dv(this).getUint16(4, true); }
  set wIndex(v) { __dv(this).setUint16(4, v, true); }
  get wLength() { return __dv(this).getUint16(6, true); }
  set wLength(v) { __dv(this).setUint16(6, v, true); }
}
libusb_control_setup.size = 8;
libusb_control_setup.align = 1;
libusb_control_setup.fields = {bmRequestType:{type:'u8',offset:0},bRequest:{type:'u8',offset:1},wValue:{type:'u16',offset:2},wIndex:{type:'u16',offset:4},wLength:{type:'u16',offset:6}};

/* struct libusb_version, 24 bytes (line 1082) */
/**
 * struct libusb_version, 24 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=24] - a byte length, or bytes to copy
 * @property {number} major - const uint16_t, offset 0
 * @property {number} minor - const uint16_t, offset 2
 * @property {number} micro - const uint16_t, offset 4
 * @property {number} nano - const uint16_t, offset 6
 * @property {number|bigint|null} rc - const char *, offset 8
 * @property {number|bigint|null} describe - const char *, offset 16
 */
export class libusb_version extends ArrayBuffer {
  constructor(init = 24) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 24) { return __view(libusb_version, p, size, owner); }
  get ptr() { return __ptr(this); }
  get major() { return __dv(this).getUint16(0, true); }
  set major(v) { __dv(this).setUint16(0, v, true); }
  get minor() { return __dv(this).getUint16(2, true); }
  set minor(v) { __dv(this).setUint16(2, v, true); }
  get micro() { return __dv(this).getUint16(4, true); }
  set micro(v) { __dv(this).setUint16(4, v, true); }
  get nano() { return __dv(this).getUint16(6, true); }
  set nano(v) { __dv(this).setUint16(6, v, true); }
  get rc() { return __ptrOut(__dv(this).getBigUint64(8, true)); }
  set rc(v) { __dv(this).setBigUint64(8, __ptrIn(v), true); }
  get describe() { return __ptrOut(__dv(this).getBigUint64(16, true)); }
  set describe(v) { __dv(this).setBigUint64(16, __ptrIn(v), true); }
}
libusb_version.size = 24;
libusb_version.align = 8;
libusb_version.fields = {major:{type:'u16',offset:0},minor:{type:'u16',offset:2},micro:{type:'u16',offset:4},nano:{type:'u16',offset:6},rc:{type:'cstring',offset:8},describe:{type:'cstring',offset:16}};

/* struct libusb_iso_packet_descriptor, 12 bytes (line 1326) */
/**
 * struct libusb_iso_packet_descriptor, 12 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=12] - a byte length, or bytes to copy
 * @property {number} length - unsigned int, offset 0
 * @property {number} actual_length - unsigned int, offset 4
 * @property {number} status - enum libusb_transfer_status, offset 8
 */
export class libusb_iso_packet_descriptor extends ArrayBuffer {
  constructor(init = 12) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 12) { return __view(libusb_iso_packet_descriptor, p, size, owner); }
  get ptr() { return __ptr(this); }
  get length() { return __dv(this).getUint32(0, true); }
  set length(v) { __dv(this).setUint32(0, v, true); }
  get actual_length() { return __dv(this).getUint32(4, true); }
  set actual_length(v) { __dv(this).setUint32(4, v, true); }
  get status() { return __dv(this).getInt32(8, true); }
  set status(v) { __dv(this).setInt32(8, v, true); }
}
libusb_iso_packet_descriptor.size = 12;
libusb_iso_packet_descriptor.align = 4;
libusb_iso_packet_descriptor.fields = {length:{type:'u32',offset:0},actual_length:{type:'u32',offset:4},status:{type:'i32',offset:8}};

/* struct libusb_transfer, 64 bytes (line 1356) */
/**
 * struct libusb_transfer, 64 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=64] - a byte length, or bytes to copy
 * @property {number|bigint|null} dev_handle - libusb_device_handle *, offset 0
 * @property {number} flags - uint8_t, offset 8
 * @property {number} endpoint - unsigned char, offset 9
 * @property {number} type - unsigned char, offset 10
 * @property {number} timeout - unsigned int, offset 12
 * @property {number} status - enum libusb_transfer_status, offset 16
 * @property {number} length - int, offset 20
 * @property {number} actual_length - int, offset 24
 * @property {number|bigint|null} callback - libusb_transfer_cb_fn, offset 32
 * @property {number|bigint|null} user_data - void *, offset 40
 * @property {number|bigint|null} buffer - unsigned char *, offset 48
 * @property {number} num_iso_packets - int, offset 56
 */
export class libusb_transfer extends ArrayBuffer {
  constructor(init = 64) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 64) { return __view(libusb_transfer, p, size, owner); }
  get ptr() { return __ptr(this); }
  get dev_handle() { return __ptrOut(__dv(this).getBigUint64(0, true)); }
  set dev_handle(v) { __dv(this).setBigUint64(0, __ptrIn(v), true); }
  get flags() { return __dv(this).getUint8(8); }
  set flags(v) { __dv(this).setUint8(8, v); }
  get endpoint() { return __dv(this).getUint8(9); }
  set endpoint(v) { __dv(this).setUint8(9, v); }
  get type() { return __dv(this).getUint8(10); }
  set type(v) { __dv(this).setUint8(10, v); }
  get timeout() { return __dv(this).getUint32(12, true); }
  set timeout(v) { __dv(this).setUint32(12, v, true); }
  get status() { return __dv(this).getInt32(16, true); }
  set status(v) { __dv(this).setInt32(16, v, true); }
  get length() { return __dv(this).getInt32(20, true); }
  set length(v) { __dv(this).setInt32(20, v, true); }
  get actual_length() { return __dv(this).getInt32(24, true); }
  set actual_length(v) { __dv(this).setInt32(24, v, true); }
  get callback() { return __ptrOut(__dv(this).getBigUint64(32, true)); }
  set callback(v) { __dv(this).setBigUint64(32, __ptrIn(v), true); }
  get user_data() { return __ptrOut(__dv(this).getBigUint64(40, true)); }
  set user_data(v) { __dv(this).setBigUint64(40, __ptrIn(v), true); }
  get buffer() { return __ptrOut(__dv(this).getBigUint64(48, true)); }
  set buffer(v) { __dv(this).setBigUint64(48, __ptrIn(v), true); }
  get num_iso_packets() { return __dv(this).getInt32(56, true); }
  set num_iso_packets(v) { __dv(this).setInt32(56, v, true); }
  // iso_packet_desc: size unknown
}
libusb_transfer.size = 64;
libusb_transfer.align = 8;
libusb_transfer.fields = {dev_handle:{type:'libusb_device_handle *',offset:0},flags:{type:'u8',offset:8},endpoint:{type:'u8',offset:9},type:{type:'u8',offset:10},timeout:{type:'u32',offset:12},status:{type:'i32',offset:16},length:{type:'i32',offset:20},actual_length:{type:'i32',offset:24},callback:{type:'function',offset:32},user_data:{type:'void *',offset:40},buffer:{type:'unsigned char *',offset:48},num_iso_packets:{type:'i32',offset:56},iso_packet_desc:{type:'struct libusb_iso_packet_descriptor[]',offset:60}};

/* struct libusb_init_option, 16 bytes (line 1566) */
/**
 * struct libusb_init_option, 16 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=16] - a byte length, or bytes to copy
 * @property {number} option - enum libusb_option, offset 0
 * @property {Uint8Array} value - union (unnamed union at /usr/include/libusb-1.0/libusb.h:1570:3), offset 8
 */
export class libusb_init_option extends ArrayBuffer {
  constructor(init = 16) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 16) { return __view(libusb_init_option, p, size, owner); }
  get ptr() { return __ptr(this); }
  get option() { return __dv(this).getInt32(0, true); }
  set option(v) { __dv(this).setInt32(0, v, true); }
  get value() { return new Uint8Array(this, 8, 8); }
  set value(v) { new Uint8Array(this, 8, 8).set(__bytes(v)); }
}
libusb_init_option.size = 16;
libusb_init_option.align = 8;
libusb_init_option.fields = {option:{type:'i32',offset:0},value:{type:'union (unnamed union at /usr/include/libusb-1.0/libusb.h:1570:3)',offset:8}};

/* struct libusb_pollfd, 8 bytes (line 2121) */
/**
 * struct libusb_pollfd, 8 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=8] - a byte length, or bytes to copy
 * @property {number} fd - int, offset 0
 * @property {number} events - short, offset 4
 */
export class libusb_pollfd extends ArrayBuffer {
  constructor(init = 8) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 8) { return __view(libusb_pollfd, p, size, owner); }
  get ptr() { return __ptr(this); }
  get fd() { return __dv(this).getInt32(0, true); }
  set fd(v) { __dv(this).setInt32(0, v, true); }
  get events() { return __dv(this).getInt16(4, true); }
  set events(v) { __dv(this).setInt16(4, v, true); }
}
libusb_pollfd.size = 8;
libusb_pollfd.align = 4;
libusb_pollfd.fields = {fd:{type:'i32',offset:0},events:{type:'i16',offset:4}};

/**
 * libusb_init
 * @param {object|number|bigint|null} ctx - libusb_context **
 * @returns {number} - i32
 */
export const libusb_init = CFunction({ptr:__sym('libusb_init'),args:['libusb_context **'],returns:'i32'});
/**
 * libusb_init_context
 * @param {object|number|bigint|null} ctx - libusb_context **
 * @param {object|number|bigint|null} options - struct libusb_init_option *
 * @param {number} num_options - i32
 * @returns {number} - i32
 */
export const libusb_init_context = CFunction({ptr:__sym('libusb_init_context'),args:['libusb_context **','struct libusb_init_option *','i32'],returns:'i32'});
/**
 * libusb_exit
 * @param {object|number|bigint|null} ctx - libusb_context *
 * @returns {void}
 */
export const libusb_exit = CFunction({ptr:__sym('libusb_exit'),args:['libusb_context *'],returns:'void'});
/**
 * libusb_set_debug
 * @param {object|number|bigint|null} ctx - libusb_context *
 * @param {number} level - i32
 * @returns {void}
 */
export const libusb_set_debug = CFunction({ptr:__sym('libusb_set_debug'),args:['libusb_context *','i32'],returns:'void'});
/**
 * libusb_set_log_cb
 * @param {object|number|bigint|null} ctx - libusb_context *
 * @param {object|number|bigint|null} cb - function
 * @param {number} mode - i32
 * @returns {void}
 */
export const libusb_set_log_cb = CFunction({ptr:__sym('libusb_set_log_cb'),args:['libusb_context *','function','i32'],returns:'void'});
/**
 * libusb_get_version
 * @returns {number|bigint|null} - struct libusb_version *
 */
export const libusb_get_version = CFunction({ptr:__sym('libusb_get_version'),args:[],returns:'struct libusb_version *'});
/**
 * libusb_has_capability
 * @param {number} capability - u32
 * @returns {number} - i32
 */
export const libusb_has_capability = CFunction({ptr:__sym('libusb_has_capability'),args:['u32'],returns:'i32'});
/**
 * libusb_error_name
 * @param {number} errcode - i32
 * @returns {string} - cstring
 */
export const libusb_error_name = CFunction({ptr:__sym('libusb_error_name'),args:['i32'],returns:'cstring'});
/**
 * libusb_setlocale
 * @param {string|null} locale - cstring
 * @returns {number} - i32
 */
export const libusb_setlocale = CFunction({ptr:__sym('libusb_setlocale'),args:['cstring'],returns:'i32'});
/**
 * libusb_strerror
 * @param {number} errcode - i32
 * @returns {string} - cstring
 */
export const libusb_strerror = CFunction({ptr:__sym('libusb_strerror'),args:['i32'],returns:'cstring'});
/**
 * libusb_get_device_list
 * @param {object|number|bigint|null} ctx - libusb_context *
 * @param {object|number|bigint|null} list - libusb_device ***
 * @returns {bigint} - i64
 */
export const libusb_get_device_list = CFunction({ptr:__sym('libusb_get_device_list'),args:['libusb_context *','libusb_device ***'],returns:'i64'});
/**
 * libusb_free_device_list
 * @param {object|number|bigint|null} list - libusb_device **
 * @param {number} unref_devices - i32
 * @returns {void}
 */
export const libusb_free_device_list = CFunction({ptr:__sym('libusb_free_device_list'),args:['libusb_device **','i32'],returns:'void'});
/**
 * libusb_ref_device
 * @param {object|number|bigint|null} dev - libusb_device *
 * @returns {number|bigint|null} - libusb_device *
 */
export const libusb_ref_device = CFunction({ptr:__sym('libusb_ref_device'),args:['libusb_device *'],returns:'libusb_device *'});
/**
 * libusb_unref_device
 * @param {object|number|bigint|null} dev - libusb_device *
 * @returns {void}
 */
export const libusb_unref_device = CFunction({ptr:__sym('libusb_unref_device'),args:['libusb_device *'],returns:'void'});
/**
 * libusb_get_configuration
 * @param {object|number|bigint|null} dev - libusb_device_handle *
 * @param {object|number|bigint|null} config - int *
 * @returns {number} - i32
 */
export const libusb_get_configuration = CFunction({ptr:__sym('libusb_get_configuration'),args:['libusb_device_handle *','int *'],returns:'i32'});
/**
 * libusb_get_device_descriptor
 * @param {object|number|bigint|null} dev - libusb_device *
 * @param {object|number|bigint|null} desc - struct libusb_device_descriptor *
 * @returns {number} - i32
 */
export const libusb_get_device_descriptor = CFunction({ptr:__sym('libusb_get_device_descriptor'),args:['libusb_device *','struct libusb_device_descriptor *'],returns:'i32'});
/**
 * libusb_get_active_config_descriptor
 * @param {object|number|bigint|null} dev - libusb_device *
 * @param {object|number|bigint|null} config - struct libusb_config_descriptor **
 * @returns {number} - i32
 */
export const libusb_get_active_config_descriptor = CFunction({ptr:__sym('libusb_get_active_config_descriptor'),args:['libusb_device *','struct libusb_config_descriptor **'],returns:'i32'});
/**
 * libusb_get_config_descriptor
 * @param {object|number|bigint|null} dev - libusb_device *
 * @param {number} config_index - u8
 * @param {object|number|bigint|null} config - struct libusb_config_descriptor **
 * @returns {number} - i32
 */
export const libusb_get_config_descriptor = CFunction({ptr:__sym('libusb_get_config_descriptor'),args:['libusb_device *','u8','struct libusb_config_descriptor **'],returns:'i32'});
/**
 * libusb_get_config_descriptor_by_value
 * @param {object|number|bigint|null} dev - libusb_device *
 * @param {number} bConfigurationValue - u8
 * @param {object|number|bigint|null} config - struct libusb_config_descriptor **
 * @returns {number} - i32
 */
export const libusb_get_config_descriptor_by_value = CFunction({ptr:__sym('libusb_get_config_descriptor_by_value'),args:['libusb_device *','u8','struct libusb_config_descriptor **'],returns:'i32'});
/**
 * libusb_free_config_descriptor
 * @param {object|number|bigint|null} config - struct libusb_config_descriptor *
 * @returns {void}
 */
export const libusb_free_config_descriptor = CFunction({ptr:__sym('libusb_free_config_descriptor'),args:['struct libusb_config_descriptor *'],returns:'void'});
/**
 * libusb_get_ss_endpoint_companion_descriptor
 * @param {object|number|bigint|null} ctx - libusb_context *
 * @param {object|number|bigint|null} endpoint - struct libusb_endpoint_descriptor *
 * @param {object|number|bigint|null} ep_comp - struct libusb_ss_endpoint_companion_descriptor **
 * @returns {number} - i32
 */
export const libusb_get_ss_endpoint_companion_descriptor = CFunction({ptr:__sym('libusb_get_ss_endpoint_companion_descriptor'),args:['libusb_context *','struct libusb_endpoint_descriptor *','struct libusb_ss_endpoint_companion_descriptor **'],returns:'i32'});
/**
 * libusb_free_ss_endpoint_companion_descriptor
 * @param {object|number|bigint|null} ep_comp - struct libusb_ss_endpoint_companion_descriptor *
 * @returns {void}
 */
export const libusb_free_ss_endpoint_companion_descriptor = CFunction({ptr:__sym('libusb_free_ss_endpoint_companion_descriptor'),args:['struct libusb_ss_endpoint_companion_descriptor *'],returns:'void'});
/**
 * libusb_get_bos_descriptor
 * @param {object|number|bigint|null} dev_handle - libusb_device_handle *
 * @param {object|number|bigint|null} bos - struct libusb_bos_descriptor **
 * @returns {number} - i32
 */
export const libusb_get_bos_descriptor = CFunction({ptr:__sym('libusb_get_bos_descriptor'),args:['libusb_device_handle *','struct libusb_bos_descriptor **'],returns:'i32'});
/**
 * libusb_free_bos_descriptor
 * @param {object|number|bigint|null} bos - struct libusb_bos_descriptor *
 * @returns {void}
 */
export const libusb_free_bos_descriptor = CFunction({ptr:__sym('libusb_free_bos_descriptor'),args:['struct libusb_bos_descriptor *'],returns:'void'});
/**
 * libusb_get_usb_2_0_extension_descriptor
 * @param {object|number|bigint|null} ctx - libusb_context *
 * @param {object|number|bigint|null} dev_cap - struct libusb_bos_dev_capability_descriptor *
 * @param {object|number|bigint|null} usb_2_0_extension - struct libusb_usb_2_0_extension_descriptor **
 * @returns {number} - i32
 */
export const libusb_get_usb_2_0_extension_descriptor = CFunction({ptr:__sym('libusb_get_usb_2_0_extension_descriptor'),args:['libusb_context *','struct libusb_bos_dev_capability_descriptor *','struct libusb_usb_2_0_extension_descriptor **'],returns:'i32'});
/**
 * libusb_free_usb_2_0_extension_descriptor
 * @param {object|number|bigint|null} usb_2_0_extension - struct libusb_usb_2_0_extension_descriptor *
 * @returns {void}
 */
export const libusb_free_usb_2_0_extension_descriptor = CFunction({ptr:__sym('libusb_free_usb_2_0_extension_descriptor'),args:['struct libusb_usb_2_0_extension_descriptor *'],returns:'void'});
/**
 * libusb_get_ss_usb_device_capability_descriptor
 * @param {object|number|bigint|null} ctx - libusb_context *
 * @param {object|number|bigint|null} dev_cap - struct libusb_bos_dev_capability_descriptor *
 * @param {object|number|bigint|null} ss_usb_device_cap - struct libusb_ss_usb_device_capability_descriptor **
 * @returns {number} - i32
 */
export const libusb_get_ss_usb_device_capability_descriptor = CFunction({ptr:__sym('libusb_get_ss_usb_device_capability_descriptor'),args:['libusb_context *','struct libusb_bos_dev_capability_descriptor *','struct libusb_ss_usb_device_capability_descriptor **'],returns:'i32'});
/**
 * libusb_free_ss_usb_device_capability_descriptor
 * @param {object|number|bigint|null} ss_usb_device_cap - struct libusb_ss_usb_device_capability_descriptor *
 * @returns {void}
 */
export const libusb_free_ss_usb_device_capability_descriptor = CFunction({ptr:__sym('libusb_free_ss_usb_device_capability_descriptor'),args:['struct libusb_ss_usb_device_capability_descriptor *'],returns:'void'});
/**
 * libusb_get_container_id_descriptor
 * @param {object|number|bigint|null} ctx - libusb_context *
 * @param {object|number|bigint|null} dev_cap - struct libusb_bos_dev_capability_descriptor *
 * @param {object|number|bigint|null} container_id - struct libusb_container_id_descriptor **
 * @returns {number} - i32
 */
export const libusb_get_container_id_descriptor = CFunction({ptr:__sym('libusb_get_container_id_descriptor'),args:['libusb_context *','struct libusb_bos_dev_capability_descriptor *','struct libusb_container_id_descriptor **'],returns:'i32'});
/**
 * libusb_free_container_id_descriptor
 * @param {object|number|bigint|null} container_id - struct libusb_container_id_descriptor *
 * @returns {void}
 */
export const libusb_free_container_id_descriptor = CFunction({ptr:__sym('libusb_free_container_id_descriptor'),args:['struct libusb_container_id_descriptor *'],returns:'void'});
/**
 * libusb_get_platform_descriptor
 * @param {object|number|bigint|null} ctx - libusb_context *
 * @param {object|number|bigint|null} dev_cap - struct libusb_bos_dev_capability_descriptor *
 * @param {object|number|bigint|null} platform_descriptor - struct libusb_platform_descriptor **
 * @returns {number} - i32
 */
export const libusb_get_platform_descriptor = CFunction({ptr:__sym('libusb_get_platform_descriptor'),args:['libusb_context *','struct libusb_bos_dev_capability_descriptor *','struct libusb_platform_descriptor **'],returns:'i32'});
/**
 * libusb_free_platform_descriptor
 * @param {object|number|bigint|null} platform_descriptor - struct libusb_platform_descriptor *
 * @returns {void}
 */
export const libusb_free_platform_descriptor = CFunction({ptr:__sym('libusb_free_platform_descriptor'),args:['struct libusb_platform_descriptor *'],returns:'void'});
/**
 * libusb_get_bus_number
 * @param {object|number|bigint|null} dev - libusb_device *
 * @returns {number} - u8
 */
export const libusb_get_bus_number = CFunction({ptr:__sym('libusb_get_bus_number'),args:['libusb_device *'],returns:'u8'});
/**
 * libusb_get_port_number
 * @param {object|number|bigint|null} dev - libusb_device *
 * @returns {number} - u8
 */
export const libusb_get_port_number = CFunction({ptr:__sym('libusb_get_port_number'),args:['libusb_device *'],returns:'u8'});
/**
 * libusb_get_port_numbers
 * @param {object|number|bigint|null} dev - libusb_device *
 * @param {object|number|bigint|null} port_numbers - uint8_t *
 * @param {number} port_numbers_len - i32
 * @returns {number} - i32
 */
export const libusb_get_port_numbers = CFunction({ptr:__sym('libusb_get_port_numbers'),args:['libusb_device *','uint8_t *','i32'],returns:'i32'});
/**
 * libusb_get_port_path
 * @param {object|number|bigint|null} ctx - libusb_context *
 * @param {object|number|bigint|null} dev - libusb_device *
 * @param {object|number|bigint|null} path - uint8_t *
 * @param {number} path_length - u8
 * @returns {number} - i32
 */
export const libusb_get_port_path = CFunction({ptr:__sym('libusb_get_port_path'),args:['libusb_context *','libusb_device *','uint8_t *','u8'],returns:'i32'});
/**
 * libusb_get_parent
 * @param {object|number|bigint|null} dev - libusb_device *
 * @returns {number|bigint|null} - libusb_device *
 */
export const libusb_get_parent = CFunction({ptr:__sym('libusb_get_parent'),args:['libusb_device *'],returns:'libusb_device *'});
/**
 * libusb_get_device_address
 * @param {object|number|bigint|null} dev - libusb_device *
 * @returns {number} - u8
 */
export const libusb_get_device_address = CFunction({ptr:__sym('libusb_get_device_address'),args:['libusb_device *'],returns:'u8'});
/**
 * libusb_get_device_speed
 * @param {object|number|bigint|null} dev - libusb_device *
 * @returns {number} - i32
 */
export const libusb_get_device_speed = CFunction({ptr:__sym('libusb_get_device_speed'),args:['libusb_device *'],returns:'i32'});
/**
 * libusb_get_max_packet_size
 * @param {object|number|bigint|null} dev - libusb_device *
 * @param {number} endpoint - u8
 * @returns {number} - i32
 */
export const libusb_get_max_packet_size = CFunction({ptr:__sym('libusb_get_max_packet_size'),args:['libusb_device *','u8'],returns:'i32'});
/**
 * libusb_get_max_iso_packet_size
 * @param {object|number|bigint|null} dev - libusb_device *
 * @param {number} endpoint - u8
 * @returns {number} - i32
 */
export const libusb_get_max_iso_packet_size = CFunction({ptr:__sym('libusb_get_max_iso_packet_size'),args:['libusb_device *','u8'],returns:'i32'});
/**
 * libusb_get_max_alt_packet_size
 * @param {object|number|bigint|null} dev - libusb_device *
 * @param {number} interface_number - i32
 * @param {number} alternate_setting - i32
 * @param {number} endpoint - u8
 * @returns {number} - i32
 */
export const libusb_get_max_alt_packet_size = CFunction({ptr:__sym('libusb_get_max_alt_packet_size'),args:['libusb_device *','i32','i32','u8'],returns:'i32'});
/**
 * libusb_get_interface_association_descriptors
 * @param {object|number|bigint|null} dev - libusb_device *
 * @param {number} config_index - u8
 * @param {object|number|bigint|null} iad_array - struct libusb_interface_association_descriptor_array **
 * @returns {number} - i32
 */
export const libusb_get_interface_association_descriptors = CFunction({ptr:__sym('libusb_get_interface_association_descriptors'),args:['libusb_device *','u8','struct libusb_interface_association_descriptor_array **'],returns:'i32'});
/**
 * libusb_get_active_interface_association_descriptors
 * @param {object|number|bigint|null} dev - libusb_device *
 * @param {object|number|bigint|null} iad_array - struct libusb_interface_association_descriptor_array **
 * @returns {number} - i32
 */
export const libusb_get_active_interface_association_descriptors = CFunction({ptr:__sym('libusb_get_active_interface_association_descriptors'),args:['libusb_device *','struct libusb_interface_association_descriptor_array **'],returns:'i32'});
/**
 * libusb_free_interface_association_descriptors
 * @param {object|number|bigint|null} iad_array - struct libusb_interface_association_descriptor_array *
 * @returns {void}
 */
export const libusb_free_interface_association_descriptors = CFunction({ptr:__sym('libusb_free_interface_association_descriptors'),args:['struct libusb_interface_association_descriptor_array *'],returns:'void'});
/**
 * libusb_wrap_sys_device
 * @param {object|number|bigint|null} ctx - libusb_context *
 * @param {bigint|number} sys_dev - i64
 * @param {object|number|bigint|null} dev_handle - libusb_device_handle **
 * @returns {number} - i32
 */
export const libusb_wrap_sys_device = CFunction({ptr:__sym('libusb_wrap_sys_device'),args:['libusb_context *','i64','libusb_device_handle **'],returns:'i32'});
/**
 * libusb_open
 * @param {object|number|bigint|null} dev - libusb_device *
 * @param {object|number|bigint|null} dev_handle - libusb_device_handle **
 * @returns {number} - i32
 */
export const libusb_open = CFunction({ptr:__sym('libusb_open'),args:['libusb_device *','libusb_device_handle **'],returns:'i32'});
/**
 * libusb_close
 * @param {object|number|bigint|null} dev_handle - libusb_device_handle *
 * @returns {void}
 */
export const libusb_close = CFunction({ptr:__sym('libusb_close'),args:['libusb_device_handle *'],returns:'void'});
/**
 * libusb_get_device
 * @param {object|number|bigint|null} dev_handle - libusb_device_handle *
 * @returns {number|bigint|null} - libusb_device *
 */
export const libusb_get_device = CFunction({ptr:__sym('libusb_get_device'),args:['libusb_device_handle *'],returns:'libusb_device *'});
/**
 * libusb_set_configuration
 * @param {object|number|bigint|null} dev_handle - libusb_device_handle *
 * @param {number} configuration - i32
 * @returns {number} - i32
 */
export const libusb_set_configuration = CFunction({ptr:__sym('libusb_set_configuration'),args:['libusb_device_handle *','i32'],returns:'i32'});
/**
 * libusb_claim_interface
 * @param {object|number|bigint|null} dev_handle - libusb_device_handle *
 * @param {number} interface_number - i32
 * @returns {number} - i32
 */
export const libusb_claim_interface = CFunction({ptr:__sym('libusb_claim_interface'),args:['libusb_device_handle *','i32'],returns:'i32'});
/**
 * libusb_release_interface
 * @param {object|number|bigint|null} dev_handle - libusb_device_handle *
 * @param {number} interface_number - i32
 * @returns {number} - i32
 */
export const libusb_release_interface = CFunction({ptr:__sym('libusb_release_interface'),args:['libusb_device_handle *','i32'],returns:'i32'});
/**
 * libusb_open_device_with_vid_pid
 * @param {object|number|bigint|null} ctx - libusb_context *
 * @param {number} vendor_id - u16
 * @param {number} product_id - u16
 * @returns {number|bigint|null} - libusb_device_handle *
 */
export const libusb_open_device_with_vid_pid = CFunction({ptr:__sym('libusb_open_device_with_vid_pid'),args:['libusb_context *','u16','u16'],returns:'libusb_device_handle *'});
/**
 * libusb_set_interface_alt_setting
 * @param {object|number|bigint|null} dev_handle - libusb_device_handle *
 * @param {number} interface_number - i32
 * @param {number} alternate_setting - i32
 * @returns {number} - i32
 */
export const libusb_set_interface_alt_setting = CFunction({ptr:__sym('libusb_set_interface_alt_setting'),args:['libusb_device_handle *','i32','i32'],returns:'i32'});
/**
 * libusb_clear_halt
 * @param {object|number|bigint|null} dev_handle - libusb_device_handle *
 * @param {number} endpoint - u8
 * @returns {number} - i32
 */
export const libusb_clear_halt = CFunction({ptr:__sym('libusb_clear_halt'),args:['libusb_device_handle *','u8'],returns:'i32'});
/**
 * libusb_reset_device
 * @param {object|number|bigint|null} dev_handle - libusb_device_handle *
 * @returns {number} - i32
 */
export const libusb_reset_device = CFunction({ptr:__sym('libusb_reset_device'),args:['libusb_device_handle *'],returns:'i32'});
/**
 * libusb_alloc_streams
 * @param {object|number|bigint|null} dev_handle - libusb_device_handle *
 * @param {number} num_streams - u32
 * @param {object|number|bigint|null} endpoints - unsigned char *
 * @param {number} num_endpoints - i32
 * @returns {number} - i32
 */
export const libusb_alloc_streams = CFunction({ptr:__sym('libusb_alloc_streams'),args:['libusb_device_handle *','u32','unsigned char *','i32'],returns:'i32'});
/**
 * libusb_free_streams
 * @param {object|number|bigint|null} dev_handle - libusb_device_handle *
 * @param {object|number|bigint|null} endpoints - unsigned char *
 * @param {number} num_endpoints - i32
 * @returns {number} - i32
 */
export const libusb_free_streams = CFunction({ptr:__sym('libusb_free_streams'),args:['libusb_device_handle *','unsigned char *','i32'],returns:'i32'});
/**
 * libusb_dev_mem_alloc
 * @param {object|number|bigint|null} dev_handle - libusb_device_handle *
 * @param {bigint|number} length - u64
 * @returns {number|bigint|null} - unsigned char *
 */
export const libusb_dev_mem_alloc = CFunction({ptr:__sym('libusb_dev_mem_alloc'),args:['libusb_device_handle *','u64'],returns:'unsigned char *'});
/**
 * libusb_dev_mem_free
 * @param {object|number|bigint|null} dev_handle - libusb_device_handle *
 * @param {object|number|bigint|null} buffer - unsigned char *
 * @param {bigint|number} length - u64
 * @returns {number} - i32
 */
export const libusb_dev_mem_free = CFunction({ptr:__sym('libusb_dev_mem_free'),args:['libusb_device_handle *','unsigned char *','u64'],returns:'i32'});
/**
 * libusb_kernel_driver_active
 * @param {object|number|bigint|null} dev_handle - libusb_device_handle *
 * @param {number} interface_number - i32
 * @returns {number} - i32
 */
export const libusb_kernel_driver_active = CFunction({ptr:__sym('libusb_kernel_driver_active'),args:['libusb_device_handle *','i32'],returns:'i32'});
/**
 * libusb_detach_kernel_driver
 * @param {object|number|bigint|null} dev_handle - libusb_device_handle *
 * @param {number} interface_number - i32
 * @returns {number} - i32
 */
export const libusb_detach_kernel_driver = CFunction({ptr:__sym('libusb_detach_kernel_driver'),args:['libusb_device_handle *','i32'],returns:'i32'});
/**
 * libusb_attach_kernel_driver
 * @param {object|number|bigint|null} dev_handle - libusb_device_handle *
 * @param {number} interface_number - i32
 * @returns {number} - i32
 */
export const libusb_attach_kernel_driver = CFunction({ptr:__sym('libusb_attach_kernel_driver'),args:['libusb_device_handle *','i32'],returns:'i32'});
/**
 * libusb_set_auto_detach_kernel_driver
 * @param {object|number|bigint|null} dev_handle - libusb_device_handle *
 * @param {number} enable - i32
 * @returns {number} - i32
 */
export const libusb_set_auto_detach_kernel_driver = CFunction({ptr:__sym('libusb_set_auto_detach_kernel_driver'),args:['libusb_device_handle *','i32'],returns:'i32'});
/**
 * libusb_alloc_transfer
 * @param {number} iso_packets - i32
 * @returns {number|bigint|null} - struct libusb_transfer *
 */
export const libusb_alloc_transfer = CFunction({ptr:__sym('libusb_alloc_transfer'),args:['i32'],returns:'struct libusb_transfer *'});
/**
 * libusb_submit_transfer
 * @param {object|number|bigint|null} transfer - struct libusb_transfer *
 * @returns {number} - i32
 */
export const libusb_submit_transfer = CFunction({ptr:__sym('libusb_submit_transfer'),args:['struct libusb_transfer *'],returns:'i32'});
/**
 * libusb_cancel_transfer
 * @param {object|number|bigint|null} transfer - struct libusb_transfer *
 * @returns {number} - i32
 */
export const libusb_cancel_transfer = CFunction({ptr:__sym('libusb_cancel_transfer'),args:['struct libusb_transfer *'],returns:'i32'});
/**
 * libusb_free_transfer
 * @param {object|number|bigint|null} transfer - struct libusb_transfer *
 * @returns {void}
 */
export const libusb_free_transfer = CFunction({ptr:__sym('libusb_free_transfer'),args:['struct libusb_transfer *'],returns:'void'});
/**
 * libusb_transfer_set_stream_id
 * @param {object|number|bigint|null} transfer - struct libusb_transfer *
 * @param {number} stream_id - u32
 * @returns {void}
 */
export const libusb_transfer_set_stream_id = CFunction({ptr:__sym('libusb_transfer_set_stream_id'),args:['struct libusb_transfer *','u32'],returns:'void'});
/**
 * libusb_transfer_get_stream_id
 * @param {object|number|bigint|null} transfer - struct libusb_transfer *
 * @returns {number} - u32
 */
export const libusb_transfer_get_stream_id = CFunction({ptr:__sym('libusb_transfer_get_stream_id'),args:['struct libusb_transfer *'],returns:'u32'});
/**
 * libusb_control_transfer
 * @param {object|number|bigint|null} dev_handle - libusb_device_handle *
 * @param {number} request_type - u8
 * @param {number} bRequest - u8
 * @param {number} wValue - u16
 * @param {number} wIndex - u16
 * @param {object|number|bigint|null} data - unsigned char *
 * @param {number} wLength - u16
 * @param {number} timeout - u32
 * @returns {number} - i32
 */
export const libusb_control_transfer = CFunction({ptr:__sym('libusb_control_transfer'),args:['libusb_device_handle *','u8','u8','u16','u16','unsigned char *','u16','u32'],returns:'i32'});
/**
 * libusb_bulk_transfer
 * @param {object|number|bigint|null} dev_handle - libusb_device_handle *
 * @param {number} endpoint - u8
 * @param {object|number|bigint|null} data - unsigned char *
 * @param {number} length - i32
 * @param {object|number|bigint|null} actual_length - int *
 * @param {number} timeout - u32
 * @returns {number} - i32
 */
export const libusb_bulk_transfer = CFunction({ptr:__sym('libusb_bulk_transfer'),args:['libusb_device_handle *','u8','unsigned char *','i32','int *','u32'],returns:'i32'});
/**
 * libusb_interrupt_transfer
 * @param {object|number|bigint|null} dev_handle - libusb_device_handle *
 * @param {number} endpoint - u8
 * @param {object|number|bigint|null} data - unsigned char *
 * @param {number} length - i32
 * @param {object|number|bigint|null} actual_length - int *
 * @param {number} timeout - u32
 * @returns {number} - i32
 */
export const libusb_interrupt_transfer = CFunction({ptr:__sym('libusb_interrupt_transfer'),args:['libusb_device_handle *','u8','unsigned char *','i32','int *','u32'],returns:'i32'});
/**
 * libusb_get_string_descriptor_ascii
 * @param {object|number|bigint|null} dev_handle - libusb_device_handle *
 * @param {number} desc_index - u8
 * @param {object|number|bigint|null} data - unsigned char *
 * @param {number} length - i32
 * @returns {number} - i32
 */
export const libusb_get_string_descriptor_ascii = CFunction({ptr:__sym('libusb_get_string_descriptor_ascii'),args:['libusb_device_handle *','u8','unsigned char *','i32'],returns:'i32'});
/**
 * libusb_try_lock_events
 * @param {object|number|bigint|null} ctx - libusb_context *
 * @returns {number} - i32
 */
export const libusb_try_lock_events = CFunction({ptr:__sym('libusb_try_lock_events'),args:['libusb_context *'],returns:'i32'});
/**
 * libusb_lock_events
 * @param {object|number|bigint|null} ctx - libusb_context *
 * @returns {void}
 */
export const libusb_lock_events = CFunction({ptr:__sym('libusb_lock_events'),args:['libusb_context *'],returns:'void'});
/**
 * libusb_unlock_events
 * @param {object|number|bigint|null} ctx - libusb_context *
 * @returns {void}
 */
export const libusb_unlock_events = CFunction({ptr:__sym('libusb_unlock_events'),args:['libusb_context *'],returns:'void'});
/**
 * libusb_event_handling_ok
 * @param {object|number|bigint|null} ctx - libusb_context *
 * @returns {number} - i32
 */
export const libusb_event_handling_ok = CFunction({ptr:__sym('libusb_event_handling_ok'),args:['libusb_context *'],returns:'i32'});
/**
 * libusb_event_handler_active
 * @param {object|number|bigint|null} ctx - libusb_context *
 * @returns {number} - i32
 */
export const libusb_event_handler_active = CFunction({ptr:__sym('libusb_event_handler_active'),args:['libusb_context *'],returns:'i32'});
/**
 * libusb_interrupt_event_handler
 * @param {object|number|bigint|null} ctx - libusb_context *
 * @returns {void}
 */
export const libusb_interrupt_event_handler = CFunction({ptr:__sym('libusb_interrupt_event_handler'),args:['libusb_context *'],returns:'void'});
/**
 * libusb_lock_event_waiters
 * @param {object|number|bigint|null} ctx - libusb_context *
 * @returns {void}
 */
export const libusb_lock_event_waiters = CFunction({ptr:__sym('libusb_lock_event_waiters'),args:['libusb_context *'],returns:'void'});
/**
 * libusb_unlock_event_waiters
 * @param {object|number|bigint|null} ctx - libusb_context *
 * @returns {void}
 */
export const libusb_unlock_event_waiters = CFunction({ptr:__sym('libusb_unlock_event_waiters'),args:['libusb_context *'],returns:'void'});
/**
 * libusb_wait_for_event
 * @param {object|number|bigint|null} ctx - libusb_context *
 * @param {object|number|bigint|null} tv - struct timeval *
 * @returns {number} - i32
 */
export const libusb_wait_for_event = CFunction({ptr:__sym('libusb_wait_for_event'),args:['libusb_context *','struct timeval *'],returns:'i32'});
/**
 * libusb_handle_events_timeout
 * @param {object|number|bigint|null} ctx - libusb_context *
 * @param {object|number|bigint|null} tv - struct timeval *
 * @returns {number} - i32
 */
export const libusb_handle_events_timeout = CFunction({ptr:__sym('libusb_handle_events_timeout'),args:['libusb_context *','struct timeval *'],returns:'i32'});
/**
 * libusb_handle_events_timeout_completed
 * @param {object|number|bigint|null} ctx - libusb_context *
 * @param {object|number|bigint|null} tv - struct timeval *
 * @param {object|number|bigint|null} completed - int *
 * @returns {number} - i32
 */
export const libusb_handle_events_timeout_completed = CFunction({ptr:__sym('libusb_handle_events_timeout_completed'),args:['libusb_context *','struct timeval *','int *'],returns:'i32'});
/**
 * libusb_handle_events
 * @param {object|number|bigint|null} ctx - libusb_context *
 * @returns {number} - i32
 */
export const libusb_handle_events = CFunction({ptr:__sym('libusb_handle_events'),args:['libusb_context *'],returns:'i32'});
/**
 * libusb_handle_events_completed
 * @param {object|number|bigint|null} ctx - libusb_context *
 * @param {object|number|bigint|null} completed - int *
 * @returns {number} - i32
 */
export const libusb_handle_events_completed = CFunction({ptr:__sym('libusb_handle_events_completed'),args:['libusb_context *','int *'],returns:'i32'});
/**
 * libusb_handle_events_locked
 * @param {object|number|bigint|null} ctx - libusb_context *
 * @param {object|number|bigint|null} tv - struct timeval *
 * @returns {number} - i32
 */
export const libusb_handle_events_locked = CFunction({ptr:__sym('libusb_handle_events_locked'),args:['libusb_context *','struct timeval *'],returns:'i32'});
/**
 * libusb_pollfds_handle_timeouts
 * @param {object|number|bigint|null} ctx - libusb_context *
 * @returns {number} - i32
 */
export const libusb_pollfds_handle_timeouts = CFunction({ptr:__sym('libusb_pollfds_handle_timeouts'),args:['libusb_context *'],returns:'i32'});
/**
 * libusb_get_next_timeout
 * @param {object|number|bigint|null} ctx - libusb_context *
 * @param {object|number|bigint|null} tv - struct timeval *
 * @returns {number} - i32
 */
export const libusb_get_next_timeout = CFunction({ptr:__sym('libusb_get_next_timeout'),args:['libusb_context *','struct timeval *'],returns:'i32'});
/**
 * libusb_get_pollfds
 * @param {object|number|bigint|null} ctx - libusb_context *
 * @returns {number|bigint|null} - struct libusb_pollfd **
 */
export const libusb_get_pollfds = CFunction({ptr:__sym('libusb_get_pollfds'),args:['libusb_context *'],returns:'struct libusb_pollfd **'});
/**
 * libusb_free_pollfds
 * @param {object|number|bigint|null} pollfds - struct libusb_pollfd **
 * @returns {void}
 */
export const libusb_free_pollfds = CFunction({ptr:__sym('libusb_free_pollfds'),args:['struct libusb_pollfd **'],returns:'void'});
/**
 * libusb_set_pollfd_notifiers
 * @param {object|number|bigint|null} ctx - libusb_context *
 * @param {object|number|bigint|null} added_cb - function
 * @param {object|number|bigint|null} removed_cb - function
 * @param {object|number|bigint|null} user_data - void *
 * @returns {void}
 */
export const libusb_set_pollfd_notifiers = CFunction({ptr:__sym('libusb_set_pollfd_notifiers'),args:['libusb_context *','function','function','void *'],returns:'void'});
/**
 * libusb_hotplug_register_callback
 * @param {object|number|bigint|null} ctx - libusb_context *
 * @param {number} events - i32
 * @param {number} flags - i32
 * @param {number} vendor_id - i32
 * @param {number} product_id - i32
 * @param {number} dev_class - i32
 * @param {object|number|bigint|null} cb_fn - function
 * @param {object|number|bigint|null} user_data - void *
 * @param {object|number|bigint|null} callback_handle - libusb_hotplug_callback_handle *
 * @returns {number} - i32
 */
export const libusb_hotplug_register_callback = CFunction({ptr:__sym('libusb_hotplug_register_callback'),args:['libusb_context *','i32','i32','i32','i32','i32','function','void *','libusb_hotplug_callback_handle *'],returns:'i32'});
/**
 * libusb_hotplug_deregister_callback
 * @param {object|number|bigint|null} ctx - libusb_context *
 * @param {number} callback_handle - i32
 * @returns {void}
 */
export const libusb_hotplug_deregister_callback = CFunction({ptr:__sym('libusb_hotplug_deregister_callback'),args:['libusb_context *','i32'],returns:'void'});
/**
 * libusb_hotplug_get_user_data
 * @param {object|number|bigint|null} ctx - libusb_context *
 * @param {number} callback_handle - i32
 * @returns {number|bigint|null} - void *
 */
export const libusb_hotplug_get_user_data = CFunction({ptr:__sym('libusb_hotplug_get_user_data'),args:['libusb_context *','i32'],returns:'void *'});

// Skipped (unsupported):
//   - libusb_set_option: variadic functions are not supported
