import { invocationName } from '../args.js';
import { isCxx, langArgs } from '../clang.js';
import { mapCType } from '../types.js';

const RESERVED = new Set([
  'break',
  'case',
  'catch',
  'class',
  'const',
  'continue',
  'debugger',
  'default',
  'delete',
  'do',
  'else',
  'export',
  'extends',
  'finally',
  'for',
  'function',
  'if',
  'import',
  'in',
  'instanceof',
  'new',
  'return',
  'super',
  'switch',
  'this',
  'throw',
  'try',
  'typeof',
  'var',
  'void',
  'while',
  'with',
  'yield',
  'let',
  'static',
  'enum',
  'await',
  'implements',
  'package',
  'protected',
  'interface',
  'private',
  'public',
  'null',
  'true',
  'false',
]);

let stripNamespaces = [];

/* The --namespace values, whose prefixes flattenName() drops. */
export function setNamespaces(namespaces) {
  stripNamespaces = namespaces.filter(Boolean).map(ns => ns + '::');
}

/* "ns::Name" -> "ns_Name", or "Name" when ns is one of the --namespace values
 * being stripped; every listed namespace goes, so "a::b::Name" is "Name" with
 * both a and b listed. */
export function flattenName(name) {
  for(let again = true; again; ) {
    const prefix = stripNamespaces.find(p => name.startsWith(p));

    if((again = !!prefix)) name = name.slice(prefix.length);
  }

  return name.replace(/::/g, '_');
}

export function safeIdent(name) {
  return RESERVED.has(name) || !/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? '_' + name : name;
}

export function header(opts) {
  const argv = [opts.clang, '-Xclang', '-ast-dump=json', '-fsyntax-only', ...langArgs(opts, opts.sources.find(s => isCxx(opts, s)) || ''), ...opts.includes.map(i => '-I' + i), ...opts.defines.map(d => '-D' + d), '<source>'];

  return (
    '/* Auto-generated by ' +
    invocationName() +
    ' from ' +
    opts.sources.join(', ') +
    ' -- do not edit by hand.\n' +
    ' * Regenerate with:\n' +
    ' *   ' +
    invocationName() +
    ' --api=' +
    opts.api +
    (opts.library ? ' --library=' + opts.library : '') +
    (opts.ffiType ? ' --ffitype' : '') +
    (opts.structs ? ' --structs' : '') +
    opts.namespaces.map(n => ' --namespace=' + n).join('') +
    (opts.describe ? ' --describe' : '') +
    (opts.finalize ? ' --finalize' : '') +
    (opts.jsdoc ? ' --jsdoc' : '') +
    (opts.cxx ? ' --c++' : '') +
    (opts.std ? ' --std=' + opts.std : '') +
    (opts.followIncludes ? ' --follow-includes' : '') +
    opts.excludes.map(n => ' --exclude=' + n).join('') +
    ' ' +
    opts.includes.map(i => '-I' + i).join(' ') +
    ' ' +
    opts.sources.join(' ') +
    '\n' +
    ' * (clang invocation used to build the AST, once per source: ' +
    argv.join(' ') +
    ')\n' +
    ' */\n'
  );
}

export function skippedComment(skipped) {
  if(!skipped.length) return '';
  return '\n// Skipped (unsupported):\n' + skipped.map(s => '//   - ' + s.name + ': ' + s.reason).join('\n') + '\n';
}

/* The functions to bind, and the enums reachable from their signatures in
 * order of first use (an enum only declared, never used, is not emitted). */
export function bindable(ir, opts) {
  const all = ir.methods.filter(m => m.kind === 'function' && !opts.excludes.includes(m.name));
  const functions = all.filter(m => !m.mangledName);
  const cxxFunctions = all.filter(m => m.mangledName);
  const classes = (ir.classes || []).filter(c => !opts.excludes.includes(c.name));
  const enumsById = new Map(ir.enums.map(e => [e.id, e]));
  const used = [...all, ...classes.flatMap(c => [...c.constructors, ...c.methods])].flatMap(fn => fn.enums);
  const enums = [...new Set(used)].map(id => enumsById.get(id)).filter(Boolean);

  return { functions, cxxFunctions, classes, enums };
}

export function paramTypes(fn) {
  return fn.args.map(p => p.slice(p.indexOf(': ') + 2));
}

/* --describe: the parameter names of an IR entry as JS identifiers. */
export function paramNames(fn) {
  const seen = new Set();

  return fn.args.map((p, i) => {
    let n = safeIdent(p.slice(0, p.indexOf(': ')) || 'arg' + i);

    if(n === 'arguments' || n === 'eval' || seen.has(n)) n += '_' + i;
    seen.add(n);
    return n;
  });
}

/* --describe: the overload with the most parameters, whose names a shared
 * JS signature then uses. */
export function widest(entries) {
  return entries.reduce((a, b) => (b.args.length > a.args.length ? b : a));
}

/* JSON, except that keys which are identifiers are left unquoted and strings
 * are single-quoted. */
export function jsLiteral(v) {
  if(Array.isArray(v)) return '[' + v.map(jsLiteral).join(',') + ']';
  if(v && typeof v === 'object') return '{' + Object.keys(v).filter(k => v[k] !== undefined).map(k => (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(k) ? k : jsLiteral(k)) + ':' + jsLiteral(v[k])).join(',') + '}';
  if(typeof v === 'string') return "'" + JSON.stringify(v).slice(1, -1).replace(/\\"/g, '"').replace(/'/g, "\\'") + "'";
  return JSON.stringify(v);
}

export function memberAccess(name) {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? '.' + name : '[' + jsLiteral(name) + ']';
}

/* The names of the FFIType members (ffi-type.c), i.e. the type strings
 * mapCType() may put in `.cf`. */
const FFI_TYPE_NAMES = new Set(['void', 'bool', 'i8', 'u8', 'i16', 'u16', 'i32', 'u32', 'i64', 'u64', 'i64_fast', 'u64_fast', 'f32', 'f64', 'pointer', 'ptr', 'function', 'cstring']);

/* A pointer type is spelled "T *", for any T. */
export function isFfiType(name) {
  return FFI_TYPE_NAMES.has(name) || name.endsWith('*');
}

/* Whether the type string is `struct NAME`, a struct passed or returned by
 * value, as opposed to a typed pointer such as `struct NAME *`. */
export function isByValue(t) {
  return !!t && t.startsWith('struct ') && !t.endsWith('*');
}

/* The name of the const holding the element list of `struct NAME`, which
 * CFunction takes as the type of a struct passed or returned by value. */
function structTypeName(name) {
  return '__s_' + safeIdent(name.slice('struct '.length).replace(/::/g, '_'));
}

export function cfType(name, opts) {
  if(isByValue(name)) return structTypeName(name);

  return opts.ffiType && FFI_TYPE_NAMES.has(name) ? 'FFIType.' + name : jsLiteral(name);
}

/* `const __s_NAME = [...];` for each struct in `used` (names), the member
 * types in memory order from ir.byValue (see by-value.js). */
export function structTypesCode(ir, used, opts) {
  const code = el => (Array.isArray(el) ? '[' + el.map(code).join(',') + ']' : cfType(el, opts));

  return [...used].map(name => 'const ' + structTypeName('struct ' + name) + ' = ' + code(ir.byValue[name]) + ';\n').join('');
}

/* The names of the structs the given function entries pass or return by
 * value. */
export function usedStructs(entries) {
  const used = new Set();

  for(const e of entries) for(const t of [e.returns, ...paramTypes(e)]) if(isByValue(t)) used.add(t.slice('struct '.length));

  return used;
}

/* Wraps the call `expr` of a function returning `returnType` so that a struct
 * comes back as its class (opts.structClasses, see prepareByValue()), not as
 * the bare ArrayBuffer CFunction makes. */
export function wrapReturn(returnType, expr, opts) {
  const ident = isByValue(returnType) && opts.structClasses && opts.structClasses.get(returnType.slice('struct '.length));

  return ident ? '__ret(' + ident + ',' + expr + ')' : expr;
}

export const DEFINE_SYM = 'function __sym(name) {\n  const p = dlsym(__LIB__, name);\n  if(p == null) throw new Error("gen-bindings: symbol not found: " + name);\n  return p;\n}\n';
