/* Auto-generated by qjsm tools/gen-bindings.js from /usr/include/freetype2/freetype/freetype.h -- do not edit by hand.
 * Regenerate with:
 *   qjsm tools/gen-bindings.js --api=cfunction --library=libfreetype.so.6 -I/usr/include/freetype2 /usr/include/freetype2/freetype/freetype.h
 * (clang invocation used to build the AST: clang -Xclang -ast-dump=json -fsyntax-only -I/usr/include/freetype2 /usr/include/freetype2/freetype/freetype.h)
 */
import { CFunction, dlsym, dlopen, RTLD_NOW } from 'ffi';

const __lib = dlopen("libfreetype.so.6", RTLD_NOW);
if (__lib == null) throw new Error("gen-bindings: dlopen(libfreetype.so.6) failed");

function __sym(name) {
  const p = dlsym(__lib, name);
  if (p == null) throw new Error("gen-bindings: symbol not found: " + name);
  return p;
}

export const FT_Init_FreeType = CFunction({ ptr: __sym("FT_Init_FreeType"), args: ["pointer"], returns: "i32" });
export const FT_Done_FreeType = CFunction({ ptr: __sym("FT_Done_FreeType"), args: ["pointer"], returns: "i32" });
export const FT_New_Face = CFunction({ ptr: __sym("FT_New_Face"), args: ["pointer", "cstring", "i64", "pointer"], returns: "i32" });
export const FT_New_Memory_Face = CFunction({ ptr: __sym("FT_New_Memory_Face"), args: ["pointer", "pointer", "i64", "i64", "pointer"], returns: "i32" });
export const FT_Open_Face = CFunction({ ptr: __sym("FT_Open_Face"), args: ["pointer", "pointer", "i64", "pointer"], returns: "i32" });
export const FT_Attach_File = CFunction({ ptr: __sym("FT_Attach_File"), args: ["pointer", "cstring"], returns: "i32" });
export const FT_Attach_Stream = CFunction({ ptr: __sym("FT_Attach_Stream"), args: ["pointer", "pointer"], returns: "i32" });
export const FT_Reference_Face = CFunction({ ptr: __sym("FT_Reference_Face"), args: ["pointer"], returns: "i32" });
export const FT_Done_Face = CFunction({ ptr: __sym("FT_Done_Face"), args: ["pointer"], returns: "i32" });
export const FT_Select_Size = CFunction({ ptr: __sym("FT_Select_Size"), args: ["pointer", "i32"], returns: "i32" });
export const FT_Request_Size = CFunction({ ptr: __sym("FT_Request_Size"), args: ["pointer", "pointer"], returns: "i32" });
export const FT_Set_Char_Size = CFunction({ ptr: __sym("FT_Set_Char_Size"), args: ["pointer", "i64", "i64", "u32", "u32"], returns: "i32" });
export const FT_Set_Pixel_Sizes = CFunction({ ptr: __sym("FT_Set_Pixel_Sizes"), args: ["pointer", "u32", "u32"], returns: "i32" });
export const FT_Load_Glyph = CFunction({ ptr: __sym("FT_Load_Glyph"), args: ["pointer", "u32", "i32"], returns: "i32" });
export const FT_Load_Char = CFunction({ ptr: __sym("FT_Load_Char"), args: ["pointer", "u64", "i32"], returns: "i32" });
export const FT_Set_Transform = CFunction({ ptr: __sym("FT_Set_Transform"), args: ["pointer", "pointer", "pointer"], returns: "void" });
export const FT_Get_Transform = CFunction({ ptr: __sym("FT_Get_Transform"), args: ["pointer", "pointer", "pointer"], returns: "void" });
export const FT_Render_Glyph = CFunction({ ptr: __sym("FT_Render_Glyph"), args: ["pointer", "i32"], returns: "i32" });
export const FT_Get_Kerning = CFunction({ ptr: __sym("FT_Get_Kerning"), args: ["pointer", "u32", "u32", "u32", "pointer"], returns: "i32" });
export const FT_Get_Track_Kerning = CFunction({ ptr: __sym("FT_Get_Track_Kerning"), args: ["pointer", "i64", "i32", "pointer"], returns: "i32" });
export const FT_Select_Charmap = CFunction({ ptr: __sym("FT_Select_Charmap"), args: ["pointer", "i32"], returns: "i32" });
export const FT_Set_Charmap = CFunction({ ptr: __sym("FT_Set_Charmap"), args: ["pointer", "pointer"], returns: "i32" });
export const FT_Get_Charmap_Index = CFunction({ ptr: __sym("FT_Get_Charmap_Index"), args: ["pointer"], returns: "i32" });
export const FT_Get_Char_Index = CFunction({ ptr: __sym("FT_Get_Char_Index"), args: ["pointer", "u64"], returns: "u32" });
export const FT_Get_First_Char = CFunction({ ptr: __sym("FT_Get_First_Char"), args: ["pointer", "pointer"], returns: "u64" });
export const FT_Get_Next_Char = CFunction({ ptr: __sym("FT_Get_Next_Char"), args: ["pointer", "u64", "pointer"], returns: "u64" });
export const FT_Face_Properties = CFunction({ ptr: __sym("FT_Face_Properties"), args: ["pointer", "u32", "pointer"], returns: "i32" });
export const FT_Get_Name_Index = CFunction({ ptr: __sym("FT_Get_Name_Index"), args: ["pointer", "pointer"], returns: "u32" });
export const FT_Get_Glyph_Name = CFunction({ ptr: __sym("FT_Get_Glyph_Name"), args: ["pointer", "u32", "pointer", "u32"], returns: "i32" });
export const FT_Get_Postscript_Name = CFunction({ ptr: __sym("FT_Get_Postscript_Name"), args: ["pointer"], returns: "cstring" });
export const FT_Get_SubGlyph_Info = CFunction({ ptr: __sym("FT_Get_SubGlyph_Info"), args: ["pointer", "u32", "pointer", "pointer", "pointer", "pointer", "pointer"], returns: "i32" });
export const FT_Get_FSType_Flags = CFunction({ ptr: __sym("FT_Get_FSType_Flags"), args: ["pointer"], returns: "u16" });
export const FT_Face_GetCharVariantIndex = CFunction({ ptr: __sym("FT_Face_GetCharVariantIndex"), args: ["pointer", "u64", "u64"], returns: "u32" });
export const FT_Face_GetCharVariantIsDefault = CFunction({ ptr: __sym("FT_Face_GetCharVariantIsDefault"), args: ["pointer", "u64", "u64"], returns: "i32" });
export const FT_Face_GetVariantSelectors = CFunction({ ptr: __sym("FT_Face_GetVariantSelectors"), args: ["pointer"], returns: "pointer" });
export const FT_Face_GetVariantsOfChar = CFunction({ ptr: __sym("FT_Face_GetVariantsOfChar"), args: ["pointer", "u64"], returns: "pointer" });
export const FT_Face_GetCharsOfVariant = CFunction({ ptr: __sym("FT_Face_GetCharsOfVariant"), args: ["pointer", "u64"], returns: "pointer" });
export const FT_MulDiv = CFunction({ ptr: __sym("FT_MulDiv"), args: ["i64", "i64", "i64"], returns: "i64" });
export const FT_MulFix = CFunction({ ptr: __sym("FT_MulFix"), args: ["i64", "i64"], returns: "i64" });
export const FT_DivFix = CFunction({ ptr: __sym("FT_DivFix"), args: ["i64", "i64"], returns: "i64" });
export const FT_RoundFix = CFunction({ ptr: __sym("FT_RoundFix"), args: ["i64"], returns: "i64" });
export const FT_CeilFix = CFunction({ ptr: __sym("FT_CeilFix"), args: ["i64"], returns: "i64" });
export const FT_FloorFix = CFunction({ ptr: __sym("FT_FloorFix"), args: ["i64"], returns: "i64" });
export const FT_Vector_Transform = CFunction({ ptr: __sym("FT_Vector_Transform"), args: ["pointer", "pointer"], returns: "void" });
export const FT_Library_Version = CFunction({ ptr: __sym("FT_Library_Version"), args: ["pointer", "pointer", "pointer", "pointer"], returns: "void" });
export const FT_Face_CheckTrueTypePatents = CFunction({ ptr: __sym("FT_Face_CheckTrueTypePatents"), args: ["pointer"], returns: "u8" });
export const FT_Face_SetUnpatentedHinting = CFunction({ ptr: __sym("FT_Face_SetUnpatentedHinting"), args: ["pointer", "u8"], returns: "u8" });
