/* Auto-generated by qjsm tools/gen-bindings.js from /usr/include/freetype2/freetype/freetype.h -- do not edit by hand.
 * Regenerate with:
 *   qjsm tools/gen-bindings.js --api=cfunction --library=libfreetype.so.6 --ffitype -I/usr/include/freetype2 /usr/include/freetype2/freetype/freetype.h
 * (clang invocation used to build the AST, once per source: clang -Xclang -ast-dump=json -fsyntax-only -I/usr/include/freetype2 <source>)
 */
import { CFunction, FFIType, dlsym, dlopen, RTLD_NOW } from 'ffi';

const __lib = dlopen("libfreetype.so.6", RTLD_NOW);
if (__lib == null) throw new Error("gen-bindings: dlopen(libfreetype.so.6) failed");

function __sym(name) {
  const p = dlsym(__lib, name);
  if (p == null) throw new Error("gen-bindings: symbol not found: " + name);
  return p;
}

// enum FT_Render_Mode_
export const FT_RENDER_MODE_NORMAL = 0;
export const FT_RENDER_MODE_LIGHT = 1;
export const FT_RENDER_MODE_MONO = 2;
export const FT_RENDER_MODE_LCD = 3;
export const FT_RENDER_MODE_LCD_V = 4;
export const FT_RENDER_MODE_SDF = 5;
export const FT_RENDER_MODE_MAX = 6;

// enum FT_Encoding_
export const FT_ENCODING_NONE = 0;
export const FT_ENCODING_MS_SYMBOL = 1;
export const FT_ENCODING_UNICODE = 2;
export const FT_ENCODING_SJIS = 3;
export const FT_ENCODING_PRC = 4;
export const FT_ENCODING_BIG5 = 5;
export const FT_ENCODING_WANSUNG = 6;
export const FT_ENCODING_JOHAB = 7;
export const FT_ENCODING_GB2312 = 1734484000;
export const FT_ENCODING_MS_SJIS = 1936353651;
export const FT_ENCODING_MS_GB2312 = 1734484000;
export const FT_ENCODING_MS_BIG5 = 1651074869;
export const FT_ENCODING_MS_WANSUNG = 2002873971;
export const FT_ENCODING_MS_JOHAB = 1785686113;
export const FT_ENCODING_ADOBE_STANDARD = 1785686114;
export const FT_ENCODING_ADOBE_EXPERT = 1785686115;
export const FT_ENCODING_ADOBE_CUSTOM = 1785686116;
export const FT_ENCODING_ADOBE_LATIN_1 = 1785686117;
export const FT_ENCODING_OLD_LATIN_2 = 1785686118;
export const FT_ENCODING_APPLE_ROMAN = 1785686119;

export const FT_Init_FreeType = CFunction({ ptr: __sym("FT_Init_FreeType"), args: [FFIType.pointer], returns: FFIType.i32 });
export const FT_Done_FreeType = CFunction({ ptr: __sym("FT_Done_FreeType"), args: [FFIType.pointer], returns: FFIType.i32 });
export const FT_New_Face = CFunction({ ptr: __sym("FT_New_Face"), args: [FFIType.pointer, FFIType.cstring, FFIType.i64, FFIType.pointer], returns: FFIType.i32 });
export const FT_New_Memory_Face = CFunction({ ptr: __sym("FT_New_Memory_Face"), args: [FFIType.pointer, FFIType.pointer, FFIType.i64, FFIType.i64, FFIType.pointer], returns: FFIType.i32 });
export const FT_Open_Face = CFunction({ ptr: __sym("FT_Open_Face"), args: [FFIType.pointer, FFIType.pointer, FFIType.i64, FFIType.pointer], returns: FFIType.i32 });
export const FT_Attach_File = CFunction({ ptr: __sym("FT_Attach_File"), args: [FFIType.pointer, FFIType.cstring], returns: FFIType.i32 });
export const FT_Attach_Stream = CFunction({ ptr: __sym("FT_Attach_Stream"), args: [FFIType.pointer, FFIType.pointer], returns: FFIType.i32 });
export const FT_Reference_Face = CFunction({ ptr: __sym("FT_Reference_Face"), args: [FFIType.pointer], returns: FFIType.i32 });
export const FT_Done_Face = CFunction({ ptr: __sym("FT_Done_Face"), args: [FFIType.pointer], returns: FFIType.i32 });
export const FT_Select_Size = CFunction({ ptr: __sym("FT_Select_Size"), args: [FFIType.pointer, FFIType.i32], returns: FFIType.i32 });
export const FT_Request_Size = CFunction({ ptr: __sym("FT_Request_Size"), args: [FFIType.pointer, FFIType.pointer], returns: FFIType.i32 });
export const FT_Set_Char_Size = CFunction({ ptr: __sym("FT_Set_Char_Size"), args: [FFIType.pointer, FFIType.i64, FFIType.i64, FFIType.u32, FFIType.u32], returns: FFIType.i32 });
export const FT_Set_Pixel_Sizes = CFunction({ ptr: __sym("FT_Set_Pixel_Sizes"), args: [FFIType.pointer, FFIType.u32, FFIType.u32], returns: FFIType.i32 });
export const FT_Load_Glyph = CFunction({ ptr: __sym("FT_Load_Glyph"), args: [FFIType.pointer, FFIType.u32, FFIType.i32], returns: FFIType.i32 });
export const FT_Load_Char = CFunction({ ptr: __sym("FT_Load_Char"), args: [FFIType.pointer, FFIType.u64, FFIType.i32], returns: FFIType.i32 });
export const FT_Set_Transform = CFunction({ ptr: __sym("FT_Set_Transform"), args: [FFIType.pointer, FFIType.pointer, FFIType.pointer], returns: FFIType.void });
export const FT_Get_Transform = CFunction({ ptr: __sym("FT_Get_Transform"), args: [FFIType.pointer, FFIType.pointer, FFIType.pointer], returns: FFIType.void });
export const FT_Render_Glyph = CFunction({ ptr: __sym("FT_Render_Glyph"), args: [FFIType.pointer, FFIType.i32], returns: FFIType.i32 });
export const FT_Get_Kerning = CFunction({ ptr: __sym("FT_Get_Kerning"), args: [FFIType.pointer, FFIType.u32, FFIType.u32, FFIType.u32, FFIType.pointer], returns: FFIType.i32 });
export const FT_Get_Track_Kerning = CFunction({ ptr: __sym("FT_Get_Track_Kerning"), args: [FFIType.pointer, FFIType.i64, FFIType.i32, FFIType.pointer], returns: FFIType.i32 });
export const FT_Select_Charmap = CFunction({ ptr: __sym("FT_Select_Charmap"), args: [FFIType.pointer, FFIType.i32], returns: FFIType.i32 });
export const FT_Set_Charmap = CFunction({ ptr: __sym("FT_Set_Charmap"), args: [FFIType.pointer, FFIType.pointer], returns: FFIType.i32 });
export const FT_Get_Charmap_Index = CFunction({ ptr: __sym("FT_Get_Charmap_Index"), args: [FFIType.pointer], returns: FFIType.i32 });
export const FT_Get_Char_Index = CFunction({ ptr: __sym("FT_Get_Char_Index"), args: [FFIType.pointer, FFIType.u64], returns: FFIType.u32 });
export const FT_Get_First_Char = CFunction({ ptr: __sym("FT_Get_First_Char"), args: [FFIType.pointer, FFIType.pointer], returns: FFIType.u64 });
export const FT_Get_Next_Char = CFunction({ ptr: __sym("FT_Get_Next_Char"), args: [FFIType.pointer, FFIType.u64, FFIType.pointer], returns: FFIType.u64 });
export const FT_Face_Properties = CFunction({ ptr: __sym("FT_Face_Properties"), args: [FFIType.pointer, FFIType.u32, FFIType.pointer], returns: FFIType.i32 });
export const FT_Get_Name_Index = CFunction({ ptr: __sym("FT_Get_Name_Index"), args: [FFIType.pointer, FFIType.pointer], returns: FFIType.u32 });
export const FT_Get_Glyph_Name = CFunction({ ptr: __sym("FT_Get_Glyph_Name"), args: [FFIType.pointer, FFIType.u32, FFIType.pointer, FFIType.u32], returns: FFIType.i32 });
export const FT_Get_Postscript_Name = CFunction({ ptr: __sym("FT_Get_Postscript_Name"), args: [FFIType.pointer], returns: FFIType.cstring });
export const FT_Get_SubGlyph_Info = CFunction({ ptr: __sym("FT_Get_SubGlyph_Info"), args: [FFIType.pointer, FFIType.u32, FFIType.pointer, FFIType.pointer, FFIType.pointer, FFIType.pointer, FFIType.pointer], returns: FFIType.i32 });
export const FT_Get_FSType_Flags = CFunction({ ptr: __sym("FT_Get_FSType_Flags"), args: [FFIType.pointer], returns: FFIType.u16 });
export const FT_Face_GetCharVariantIndex = CFunction({ ptr: __sym("FT_Face_GetCharVariantIndex"), args: [FFIType.pointer, FFIType.u64, FFIType.u64], returns: FFIType.u32 });
export const FT_Face_GetCharVariantIsDefault = CFunction({ ptr: __sym("FT_Face_GetCharVariantIsDefault"), args: [FFIType.pointer, FFIType.u64, FFIType.u64], returns: FFIType.i32 });
export const FT_Face_GetVariantSelectors = CFunction({ ptr: __sym("FT_Face_GetVariantSelectors"), args: [FFIType.pointer], returns: FFIType.pointer });
export const FT_Face_GetVariantsOfChar = CFunction({ ptr: __sym("FT_Face_GetVariantsOfChar"), args: [FFIType.pointer, FFIType.u64], returns: FFIType.pointer });
export const FT_Face_GetCharsOfVariant = CFunction({ ptr: __sym("FT_Face_GetCharsOfVariant"), args: [FFIType.pointer, FFIType.u64], returns: FFIType.pointer });
export const FT_MulDiv = CFunction({ ptr: __sym("FT_MulDiv"), args: [FFIType.i64, FFIType.i64, FFIType.i64], returns: FFIType.i64 });
export const FT_MulFix = CFunction({ ptr: __sym("FT_MulFix"), args: [FFIType.i64, FFIType.i64], returns: FFIType.i64 });
export const FT_DivFix = CFunction({ ptr: __sym("FT_DivFix"), args: [FFIType.i64, FFIType.i64], returns: FFIType.i64 });
export const FT_RoundFix = CFunction({ ptr: __sym("FT_RoundFix"), args: [FFIType.i64], returns: FFIType.i64 });
export const FT_CeilFix = CFunction({ ptr: __sym("FT_CeilFix"), args: [FFIType.i64], returns: FFIType.i64 });
export const FT_FloorFix = CFunction({ ptr: __sym("FT_FloorFix"), args: [FFIType.i64], returns: FFIType.i64 });
export const FT_Vector_Transform = CFunction({ ptr: __sym("FT_Vector_Transform"), args: [FFIType.pointer, FFIType.pointer], returns: FFIType.void });
export const FT_Library_Version = CFunction({ ptr: __sym("FT_Library_Version"), args: [FFIType.pointer, FFIType.pointer, FFIType.pointer, FFIType.pointer], returns: FFIType.void });
export const FT_Face_CheckTrueTypePatents = CFunction({ ptr: __sym("FT_Face_CheckTrueTypePatents"), args: [FFIType.pointer], returns: FFIType.u8 });
export const FT_Face_SetUnpatentedHinting = CFunction({ ptr: __sym("FT_Face_SetUnpatentedHinting"), args: [FFIType.pointer, FFIType.u8], returns: FFIType.u8 });
