/* Auto-generated by qjsm tools/gen-bindings.js from /usr/include/freetype2/freetype/freetype.h -- do not edit by hand.
 * Regenerate with:
 *   qjsm tools/gen-bindings.js --api=cfunction --library=libfreetype.so.6 --structs --jsdoc -I/usr/include/freetype2 /usr/include/freetype2/freetype/freetype.h
 * (clang invocation used to build the AST, once per source: clang -Xclang -ast-dump=json -fsyntax-only -I/usr/include/freetype2 <source>)
 */
import { CFunction, toArrayBuffer, ptr as __ptr, toString as __cstr, dlsym, dlopen, RTLD_NOW } from 'ffi';

const __lib = dlopen("libfreetype.so.6", RTLD_NOW);
if (__lib == null) throw new Error("gen-bindings: dlopen(libfreetype.so.6) failed");

function __sym(name) {
  const p = dlsym(__lib, name);
  if(p == null) throw new Error("gen-bindings: symbol not found: " + name);
  return p;
}

// enum FT_Render_Mode_
export const FT_RENDER_MODE_NORMAL = 0;
export const FT_RENDER_MODE_LIGHT = 1;
export const FT_RENDER_MODE_MONO = 2;
export const FT_RENDER_MODE_LCD = 3;
export const FT_RENDER_MODE_LCD_V = 4;
export const FT_RENDER_MODE_SDF = 5;
export const FT_RENDER_MODE_MAX = 6;

// enum FT_Encoding_
export const FT_ENCODING_NONE = 0;
export const FT_ENCODING_MS_SYMBOL = 1;
export const FT_ENCODING_UNICODE = 2;
export const FT_ENCODING_SJIS = 3;
export const FT_ENCODING_PRC = 4;
export const FT_ENCODING_BIG5 = 5;
export const FT_ENCODING_WANSUNG = 6;
export const FT_ENCODING_JOHAB = 7;
export const FT_ENCODING_GB2312 = 1734484000;
export const FT_ENCODING_MS_SJIS = 1936353651;
export const FT_ENCODING_MS_GB2312 = 1734484000;
export const FT_ENCODING_MS_BIG5 = 1651074869;
export const FT_ENCODING_MS_WANSUNG = 2002873971;
export const FT_ENCODING_MS_JOHAB = 1785686113;
export const FT_ENCODING_ADOBE_STANDARD = 1785686114;
export const FT_ENCODING_ADOBE_EXPERT = 1785686115;
export const FT_ENCODING_ADOBE_CUSTOM = 1785686116;
export const FT_ENCODING_ADOBE_LATIN_1 = 1785686117;
export const FT_ENCODING_OLD_LATIN_2 = 1785686118;
export const FT_ENCODING_APPLE_ROMAN = 1785686119;

const __dvs = new WeakMap();

function __dv(o) {
  let d = __dvs.get(o);
  if(!d) __dvs.set(o, (d = new DataView(o)));
  return d;
}

function __ptrOut(v) {
  return v === 0n ? null : v <= 0xffffffffn ? Number(v) : v;
}

function __ptrIn(v) {
  return v === null || v === undefined ? 0n : typeof v === "object" ? BigInt(v.ptr !== undefined ? v.ptr : __ptr(v)) : BigInt(v);
}

const __index = /^(0|[1-9]\d*)$/;

function __ptrArray(a, wrap) {
  const at = i => {
    const p = a[i];
    return p === 0n ? null : wrap ? wrap(p) : __ptrOut(p);
  };

  return new Proxy(a, {
    get(t, k) {
      if(typeof k === "string" && __index.test(k)) return Number(k) < t.length ? at(Number(k)) : undefined;
      if(k === Symbol.iterator) return function*() { for(let i = 0; i < t.length; i++) yield at(i); };

      const v = Reflect.get(t, k, t);
      return typeof v === "function" ? v.bind(t) : v;
    },
    set(t, k, v) {
      if(typeof k === "string" && __index.test(k)) {
        if(Number(k) >= t.length) return false;
        t[k] = __ptrIn(v);
        return true;
      }
      return Reflect.set(t, k, v, t);
    },
  });
}

function __bytes(v) {
  return ArrayBuffer.isView(v) ? new Uint8Array(v.buffer, v.byteOffset, v.byteLength) : new Uint8Array(v);
}

function __view(cls, p, size, owner) {
  const b = toArrayBuffer(BigInt(p), size, false);

  Object.setPrototypeOf(b, cls.prototype);
  if(owner) Object.defineProperty(b, "__owner", { value: owner });
  return b;
}

const __sizes = { bool: 1, i8: 1, u8: 1, i16: 2, u16: 2, i32: 4, u32: 4, i64: 8, u64: 8, i64_fast: 8, u64_fast: 8, f32: 4, f64: 8, pointer: 8, ptr: 8, function: 8, cstring: 8 };

/* A type spelled "T *" is a pointer, whatever T is. */
function __sz(type) {
  return __sizes[type.endsWith("*") ? "pointer" : type];
}

function __read(dv, type, off) {
  if(type.endsWith("*")) type = "pointer";
  switch(type) {
    case "bool": return dv.getUint8(off) !== 0;
    case "i8": return dv.getInt8(off);
    case "u8": return dv.getUint8(off);
    case "i16": return dv.getInt16(off, true);
    case "u16": return dv.getUint16(off, true);
    case "i32": return dv.getInt32(off, true);
    case "u32": return dv.getUint32(off, true);
    case "i64": return dv.getBigInt64(off, true);
    case "u64": return dv.getBigUint64(off, true);
    case "i64_fast": return Number(dv.getBigInt64(off, true));
    case "u64_fast": return Number(dv.getBigUint64(off, true));
    case "f32": return dv.getFloat32(off, true);
    case "f64": return dv.getFloat64(off, true);
    case "pointer": case "ptr": case "function": return __ptrOut(dv.getBigUint64(off, true));
    case "cstring": { const p = __ptrOut(dv.getBigUint64(off, true)); return p === null ? null : __cstr(p); }
  }
}

function __write(dv, type, off, v) {
  if(type.endsWith("*")) type = "pointer";
  switch(type) {
    case "bool": return dv.setUint8(off, v ? 1 : 0);
    case "i8": return dv.setInt8(off, v);
    case "u8": return dv.setUint8(off, v);
    case "i16": return dv.setInt16(off, v, true);
    case "u16": return dv.setUint16(off, v, true);
    case "i32": return dv.setInt32(off, v, true);
    case "u32": return dv.setUint32(off, v, true);
    case "i64": case "i64_fast": return dv.setBigInt64(off, BigInt(v), true);
    case "u64": case "u64_fast": case "pointer": case "ptr": case "function": return dv.setBigUint64(off, v === null ? 0n : BigInt(v), true);
    case "f32": return dv.setFloat32(off, v, true);
    case "f64": return dv.setFloat64(off, v, true);
  }
  throw new TypeError("cannot write a " + type + " field");
}

function __variable(name, type) {
  const v = { get ptr() { return __sym(name); } };
  if(__sz(type) !== undefined) {
    const dv = () => new DataView(toArrayBuffer(__sym(name), __sz(type), false));
    Object.defineProperty(v, "value", { enumerable: true, get: () => __read(dv(), type, 0), set: x => __write(dv(), type, 0, x) });
  }
  return v;
}

function __ret(cls, f) {
  return (...args) => Object.setPrototypeOf(f(...args), cls.prototype);
}

// classes and structs

/* struct FT_Glyph_Metrics_, 64 bytes (line 444) */
/**
 * struct FT_Glyph_Metrics_, 64 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=64] - a byte length, or bytes to copy
 * @property {bigint} width - FT_Pos, offset 0
 * @property {bigint} height - FT_Pos, offset 8
 * @property {bigint} horiBearingX - FT_Pos, offset 16
 * @property {bigint} horiBearingY - FT_Pos, offset 24
 * @property {bigint} horiAdvance - FT_Pos, offset 32
 * @property {bigint} vertBearingX - FT_Pos, offset 40
 * @property {bigint} vertBearingY - FT_Pos, offset 48
 * @property {bigint} vertAdvance - FT_Pos, offset 56
 */
export class FT_Glyph_Metrics_ extends ArrayBuffer {
  constructor(init = 64) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 64) { return __view(FT_Glyph_Metrics_, p, size, owner); }
  get ptr() { return __ptr(this); }
  get width() { return __dv(this).getBigInt64(0, true); }
  set width(v) { __dv(this).setBigInt64(0, BigInt(v), true); }
  get height() { return __dv(this).getBigInt64(8, true); }
  set height(v) { __dv(this).setBigInt64(8, BigInt(v), true); }
  get horiBearingX() { return __dv(this).getBigInt64(16, true); }
  set horiBearingX(v) { __dv(this).setBigInt64(16, BigInt(v), true); }
  get horiBearingY() { return __dv(this).getBigInt64(24, true); }
  set horiBearingY(v) { __dv(this).setBigInt64(24, BigInt(v), true); }
  get horiAdvance() { return __dv(this).getBigInt64(32, true); }
  set horiAdvance(v) { __dv(this).setBigInt64(32, BigInt(v), true); }
  get vertBearingX() { return __dv(this).getBigInt64(40, true); }
  set vertBearingX(v) { __dv(this).setBigInt64(40, BigInt(v), true); }
  get vertBearingY() { return __dv(this).getBigInt64(48, true); }
  set vertBearingY(v) { __dv(this).setBigInt64(48, BigInt(v), true); }
  get vertAdvance() { return __dv(this).getBigInt64(56, true); }
  set vertAdvance(v) { __dv(this).setBigInt64(56, BigInt(v), true); }
}
FT_Glyph_Metrics_.size = 64;
FT_Glyph_Metrics_.align = 8;
FT_Glyph_Metrics_.fields = {width:{type:'i64',offset:0},height:{type:'i64',offset:8},horiBearingX:{type:'i64',offset:16},horiBearingY:{type:'i64',offset:24},horiAdvance:{type:'i64',offset:32},vertBearingX:{type:'i64',offset:40},vertBearingY:{type:'i64',offset:48},vertAdvance:{type:'i64',offset:56}};

/* struct FT_Bitmap_Size_, 32 bytes (line 506) */
/**
 * struct FT_Bitmap_Size_, 32 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=32] - a byte length, or bytes to copy
 * @property {number} height - FT_Short, offset 0
 * @property {number} width - FT_Short, offset 2
 * @property {bigint} size - FT_Pos, offset 8
 * @property {bigint} x_ppem - FT_Pos, offset 16
 * @property {bigint} y_ppem - FT_Pos, offset 24
 */
export class FT_Bitmap_Size_ extends ArrayBuffer {
  constructor(init = 32) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 32) { return __view(FT_Bitmap_Size_, p, size, owner); }
  get ptr() { return __ptr(this); }
  get height() { return __dv(this).getInt16(0, true); }
  set height(v) { __dv(this).setInt16(0, v, true); }
  get width() { return __dv(this).getInt16(2, true); }
  set width(v) { __dv(this).setInt16(2, v, true); }
  get size() { return __dv(this).getBigInt64(8, true); }
  set size(v) { __dv(this).setBigInt64(8, BigInt(v), true); }
  get x_ppem() { return __dv(this).getBigInt64(16, true); }
  set x_ppem(v) { __dv(this).setBigInt64(16, BigInt(v), true); }
  get y_ppem() { return __dv(this).getBigInt64(24, true); }
  set y_ppem(v) { __dv(this).setBigInt64(24, BigInt(v), true); }
}
FT_Bitmap_Size_.size = 32;
FT_Bitmap_Size_.align = 8;
FT_Bitmap_Size_.fields = {height:{type:'i16',offset:0},width:{type:'i16',offset:2},size:{type:'i64',offset:8},x_ppem:{type:'i64',offset:16},y_ppem:{type:'i64',offset:24}};

/* struct FT_CharMapRec_, 16 bytes (line 1004) */
/**
 * struct FT_CharMapRec_, 16 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=16] - a byte length, or bytes to copy
 * @property {number|bigint|null} face - FT_Face, offset 0
 * @property {number} encoding - FT_Encoding, offset 8
 * @property {number} platform_id - FT_UShort, offset 12
 * @property {number} encoding_id - FT_UShort, offset 14
 */
export class FT_CharMapRec_ extends ArrayBuffer {
  constructor(init = 16) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 16) { return __view(FT_CharMapRec_, p, size, owner); }
  get ptr() { return __ptr(this); }
  get face() { return __ptrOut(__dv(this).getBigUint64(0, true)); }
  set face(v) { __dv(this).setBigUint64(0, __ptrIn(v), true); }
  get encoding() { return __dv(this).getInt32(8, true); }
  set encoding(v) { __dv(this).setInt32(8, v, true); }
  get platform_id() { return __dv(this).getUint16(12, true); }
  set platform_id(v) { __dv(this).setUint16(12, v, true); }
  get encoding_id() { return __dv(this).getUint16(14, true); }
  set encoding_id(v) { __dv(this).setUint16(14, v, true); }
}
FT_CharMapRec_.size = 16;
FT_CharMapRec_.align = 8;
FT_CharMapRec_.fields = {face:{type:'struct FT_FaceRec_ *',offset:0},encoding:{type:'i32',offset:8},platform_id:{type:'u16',offset:12},encoding_id:{type:'u16',offset:14}};

/* struct FT_FaceRec_, 248 bytes (line 1229) */
/**
 * struct FT_FaceRec_, 248 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=248] - a byte length, or bytes to copy
 * @property {bigint} num_faces - FT_Long, offset 0
 * @property {bigint} face_index - FT_Long, offset 8
 * @property {bigint} face_flags - FT_Long, offset 16
 * @property {bigint} style_flags - FT_Long, offset 24
 * @property {bigint} num_glyphs - FT_Long, offset 32
 * @property {number|bigint|null} family_name - FT_String *, offset 40
 * @property {number|bigint|null} style_name - FT_String *, offset 48
 * @property {number} num_fixed_sizes - FT_Int, offset 56
 * @property {FT_Bitmap_Size_|null} available_sizes - FT_Bitmap_Size *, offset 64
 * @property {number} num_charmaps - FT_Int, offset 72
 * @property {number|bigint|null} charmaps - FT_CharMap *, offset 80
 * @property {Uint8Array} generic - FT_Generic, offset 88
 * @property {Uint8Array} bbox - FT_BBox, offset 104
 * @property {number} units_per_EM - FT_UShort, offset 136
 * @property {number} ascender - FT_Short, offset 138
 * @property {number} descender - FT_Short, offset 140
 * @property {number} height - FT_Short, offset 142
 * @property {number} max_advance_width - FT_Short, offset 144
 * @property {number} max_advance_height - FT_Short, offset 146
 * @property {number} underline_position - FT_Short, offset 148
 * @property {number} underline_thickness - FT_Short, offset 150
 * @property {number|bigint|null} glyph - FT_GlyphSlot, offset 152
 * @property {number|bigint|null} size - FT_Size, offset 160
 * @property {number|bigint|null} charmap - FT_CharMap, offset 168
 * @property {number|bigint|null} driver - FT_Driver, offset 176
 * @property {Uint8Array} memory - FT_Memory, offset 184
 * @property {Uint8Array} stream - FT_Stream, offset 192
 * @property {Uint8Array} sizes_list - FT_ListRec, offset 200
 * @property {Uint8Array} autohint - FT_Generic, offset 216
 * @property {number|bigint|null} extensions - void *, offset 232
 * @property {number|bigint|null} internal - FT_Face_Internal, offset 240
 */
export class FT_FaceRec_ extends ArrayBuffer {
  constructor(init = 248) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 248) { return __view(FT_FaceRec_, p, size, owner); }
  get ptr() { return __ptr(this); }
  get num_faces() { return __dv(this).getBigInt64(0, true); }
  set num_faces(v) { __dv(this).setBigInt64(0, BigInt(v), true); }
  get face_index() { return __dv(this).getBigInt64(8, true); }
  set face_index(v) { __dv(this).setBigInt64(8, BigInt(v), true); }
  get face_flags() { return __dv(this).getBigInt64(16, true); }
  set face_flags(v) { __dv(this).setBigInt64(16, BigInt(v), true); }
  get style_flags() { return __dv(this).getBigInt64(24, true); }
  set style_flags(v) { __dv(this).setBigInt64(24, BigInt(v), true); }
  get num_glyphs() { return __dv(this).getBigInt64(32, true); }
  set num_glyphs(v) { __dv(this).setBigInt64(32, BigInt(v), true); }
  get family_name() { return __ptrOut(__dv(this).getBigUint64(40, true)); }
  set family_name(v) { __dv(this).setBigUint64(40, __ptrIn(v), true); }
  get style_name() { return __ptrOut(__dv(this).getBigUint64(48, true)); }
  set style_name(v) { __dv(this).setBigUint64(48, __ptrIn(v), true); }
  get num_fixed_sizes() { return __dv(this).getInt32(56, true); }
  set num_fixed_sizes(v) { __dv(this).setInt32(56, v, true); }
  get available_sizes() { const p = __dv(this).getBigUint64(64, true); return p === 0n ? null : FT_Bitmap_Size_.at(p); }
  set available_sizes(v) { __dv(this).setBigUint64(64, __ptrIn(v), true); }
  get num_charmaps() { return __dv(this).getInt32(72, true); }
  set num_charmaps(v) { __dv(this).setInt32(72, v, true); }
  get charmaps() { return __ptrOut(__dv(this).getBigUint64(80, true)); }
  set charmaps(v) { __dv(this).setBigUint64(80, __ptrIn(v), true); }
  get generic() { return new Uint8Array(this, 88, 16); }
  set generic(v) { new Uint8Array(this, 88, 16).set(__bytes(v)); }
  get bbox() { return new Uint8Array(this, 104, 32); }
  set bbox(v) { new Uint8Array(this, 104, 32).set(__bytes(v)); }
  get units_per_EM() { return __dv(this).getUint16(136, true); }
  set units_per_EM(v) { __dv(this).setUint16(136, v, true); }
  get ascender() { return __dv(this).getInt16(138, true); }
  set ascender(v) { __dv(this).setInt16(138, v, true); }
  get descender() { return __dv(this).getInt16(140, true); }
  set descender(v) { __dv(this).setInt16(140, v, true); }
  get height() { return __dv(this).getInt16(142, true); }
  set height(v) { __dv(this).setInt16(142, v, true); }
  get max_advance_width() { return __dv(this).getInt16(144, true); }
  set max_advance_width(v) { __dv(this).setInt16(144, v, true); }
  get max_advance_height() { return __dv(this).getInt16(146, true); }
  set max_advance_height(v) { __dv(this).setInt16(146, v, true); }
  get underline_position() { return __dv(this).getInt16(148, true); }
  set underline_position(v) { __dv(this).setInt16(148, v, true); }
  get underline_thickness() { return __dv(this).getInt16(150, true); }
  set underline_thickness(v) { __dv(this).setInt16(150, v, true); }
  get glyph() { return __ptrOut(__dv(this).getBigUint64(152, true)); }
  set glyph(v) { __dv(this).setBigUint64(152, __ptrIn(v), true); }
  get size() { return __ptrOut(__dv(this).getBigUint64(160, true)); }
  set size(v) { __dv(this).setBigUint64(160, __ptrIn(v), true); }
  get charmap() { return __ptrOut(__dv(this).getBigUint64(168, true)); }
  set charmap(v) { __dv(this).setBigUint64(168, __ptrIn(v), true); }
  get driver() { return __ptrOut(__dv(this).getBigUint64(176, true)); }
  set driver(v) { __dv(this).setBigUint64(176, __ptrIn(v), true); }
  get memory() { return new Uint8Array(this, 184, 8); }
  set memory(v) { new Uint8Array(this, 184, 8).set(__bytes(v)); }
  get stream() { return new Uint8Array(this, 192, 8); }
  set stream(v) { new Uint8Array(this, 192, 8).set(__bytes(v)); }
  get sizes_list() { return new Uint8Array(this, 200, 16); }
  set sizes_list(v) { new Uint8Array(this, 200, 16).set(__bytes(v)); }
  get autohint() { return new Uint8Array(this, 216, 16); }
  set autohint(v) { new Uint8Array(this, 216, 16).set(__bytes(v)); }
  get extensions() { return __ptrOut(__dv(this).getBigUint64(232, true)); }
  set extensions(v) { __dv(this).setBigUint64(232, __ptrIn(v), true); }
  get internal() { return __ptrOut(__dv(this).getBigUint64(240, true)); }
  set internal(v) { __dv(this).setBigUint64(240, __ptrIn(v), true); }
}
FT_FaceRec_.size = 248;
FT_FaceRec_.align = 8;
FT_FaceRec_.fields = {num_faces:{type:'i64',offset:0},face_index:{type:'i64',offset:8},face_flags:{type:'i64',offset:16},style_flags:{type:'i64',offset:24},num_glyphs:{type:'i64',offset:32},family_name:{type:'FT_String *',offset:40},style_name:{type:'FT_String *',offset:48},num_fixed_sizes:{type:'i32',offset:56},available_sizes:{type:'FT_Bitmap_Size *',offset:64},num_charmaps:{type:'i32',offset:72},charmaps:{type:'FT_CharMap *',offset:80},generic:{type:'FT_Generic',offset:88},bbox:{type:'FT_BBox',offset:104},units_per_EM:{type:'u16',offset:136},ascender:{type:'i16',offset:138},descender:{type:'i16',offset:140},height:{type:'i16',offset:142},max_advance_width:{type:'i16',offset:144},max_advance_height:{type:'i16',offset:146},underline_position:{type:'i16',offset:148},underline_thickness:{type:'i16',offset:150},glyph:{type:'struct FT_GlyphSlotRec_ *',offset:152},size:{type:'struct FT_SizeRec_ *',offset:160},charmap:{type:'struct FT_CharMapRec_ *',offset:168},driver:{type:'struct FT_DriverRec_ *',offset:176},memory:{type:'struct FT_MemoryRec_ *',offset:184},stream:{type:'struct FT_StreamRec_ *',offset:192},sizes_list:{type:'FT_ListRec',offset:200},autohint:{type:'FT_Generic',offset:216},extensions:{type:'void *',offset:232},internal:{type:'struct FT_Face_InternalRec_ *',offset:240}};

/* struct FT_Size_Metrics_, 56 bytes (line 1970) */
/**
 * struct FT_Size_Metrics_, 56 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=56] - a byte length, or bytes to copy
 * @property {number} x_ppem - FT_UShort, offset 0
 * @property {number} y_ppem - FT_UShort, offset 2
 * @property {bigint} x_scale - FT_Fixed, offset 8
 * @property {bigint} y_scale - FT_Fixed, offset 16
 * @property {bigint} ascender - FT_Pos, offset 24
 * @property {bigint} descender - FT_Pos, offset 32
 * @property {bigint} height - FT_Pos, offset 40
 * @property {bigint} max_advance - FT_Pos, offset 48
 */
export class FT_Size_Metrics_ extends ArrayBuffer {
  constructor(init = 56) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 56) { return __view(FT_Size_Metrics_, p, size, owner); }
  get ptr() { return __ptr(this); }
  get x_ppem() { return __dv(this).getUint16(0, true); }
  set x_ppem(v) { __dv(this).setUint16(0, v, true); }
  get y_ppem() { return __dv(this).getUint16(2, true); }
  set y_ppem(v) { __dv(this).setUint16(2, v, true); }
  get x_scale() { return __dv(this).getBigInt64(8, true); }
  set x_scale(v) { __dv(this).setBigInt64(8, BigInt(v), true); }
  get y_scale() { return __dv(this).getBigInt64(16, true); }
  set y_scale(v) { __dv(this).setBigInt64(16, BigInt(v), true); }
  get ascender() { return __dv(this).getBigInt64(24, true); }
  set ascender(v) { __dv(this).setBigInt64(24, BigInt(v), true); }
  get descender() { return __dv(this).getBigInt64(32, true); }
  set descender(v) { __dv(this).setBigInt64(32, BigInt(v), true); }
  get height() { return __dv(this).getBigInt64(40, true); }
  set height(v) { __dv(this).setBigInt64(40, BigInt(v), true); }
  get max_advance() { return __dv(this).getBigInt64(48, true); }
  set max_advance(v) { __dv(this).setBigInt64(48, BigInt(v), true); }
}
FT_Size_Metrics_.size = 56;
FT_Size_Metrics_.align = 8;
FT_Size_Metrics_.fields = {x_ppem:{type:'u16',offset:0},y_ppem:{type:'u16',offset:2},x_scale:{type:'i64',offset:8},y_scale:{type:'i64',offset:16},ascender:{type:'i64',offset:24},descender:{type:'i64',offset:32},height:{type:'i64',offset:40},max_advance:{type:'i64',offset:48}};

/* struct FT_SizeRec_, 88 bytes (line 2007) */
/**
 * struct FT_SizeRec_, 88 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=88] - a byte length, or bytes to copy
 * @property {number|bigint|null} face - FT_Face, offset 0
 * @property {Uint8Array} generic - FT_Generic, offset 8
 * @property {FT_Size_Metrics_} metrics - FT_Size_Metrics, offset 24
 * @property {number|bigint|null} internal - FT_Size_Internal, offset 80
 */
export class FT_SizeRec_ extends ArrayBuffer {
  constructor(init = 88) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 88) { return __view(FT_SizeRec_, p, size, owner); }
  get ptr() { return __ptr(this); }
  get face() { return __ptrOut(__dv(this).getBigUint64(0, true)); }
  set face(v) { __dv(this).setBigUint64(0, __ptrIn(v), true); }
  get generic() { return new Uint8Array(this, 8, 16); }
  set generic(v) { new Uint8Array(this, 8, 16).set(__bytes(v)); }
  get metrics() { return FT_Size_Metrics_.at(__ptr(this, 24), this); }
  set metrics(v) { new Uint8Array(this, 24, 56).set(__bytes(v)); }
  get internal() { return __ptrOut(__dv(this).getBigUint64(80, true)); }
  set internal(v) { __dv(this).setBigUint64(80, __ptrIn(v), true); }
}
FT_SizeRec_.size = 88;
FT_SizeRec_.align = 8;
FT_SizeRec_.fields = {face:{type:'struct FT_FaceRec_ *',offset:0},generic:{type:'FT_Generic',offset:8},metrics:{type:'FT_Size_Metrics',offset:24},internal:{type:'struct FT_Size_InternalRec_ *',offset:80}};

/* struct FT_GlyphSlotRec_, 304 bytes (line 2260) */
/**
 * struct FT_GlyphSlotRec_, 304 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=304] - a byte length, or bytes to copy
 * @property {number|bigint|null} library - FT_Library, offset 0
 * @property {number|bigint|null} face - FT_Face, offset 8
 * @property {number|bigint|null} next - FT_GlyphSlot, offset 16
 * @property {number} glyph_index - FT_UInt, offset 24
 * @property {Uint8Array} generic - FT_Generic, offset 32
 * @property {FT_Glyph_Metrics_} metrics - FT_Glyph_Metrics, offset 48
 * @property {bigint} linearHoriAdvance - FT_Fixed, offset 112
 * @property {bigint} linearVertAdvance - FT_Fixed, offset 120
 * @property {Uint8Array} advance - FT_Vector, offset 128
 * @property {number} format - FT_Glyph_Format, offset 144
 * @property {Uint8Array} bitmap - FT_Bitmap, offset 152
 * @property {number} bitmap_left - FT_Int, offset 192
 * @property {number} bitmap_top - FT_Int, offset 196
 * @property {Uint8Array} outline - FT_Outline, offset 200
 * @property {number} num_subglyphs - FT_UInt, offset 240
 * @property {number|bigint|null} subglyphs - FT_SubGlyph, offset 248
 * @property {number|bigint|null} control_data - void *, offset 256
 * @property {bigint} control_len - long, offset 264
 * @property {bigint} lsb_delta - FT_Pos, offset 272
 * @property {bigint} rsb_delta - FT_Pos, offset 280
 * @property {number|bigint|null} other - void *, offset 288
 * @property {number|bigint|null} internal - FT_Slot_Internal, offset 296
 */
export class FT_GlyphSlotRec_ extends ArrayBuffer {
  constructor(init = 304) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 304) { return __view(FT_GlyphSlotRec_, p, size, owner); }
  get ptr() { return __ptr(this); }
  get library() { return __ptrOut(__dv(this).getBigUint64(0, true)); }
  set library(v) { __dv(this).setBigUint64(0, __ptrIn(v), true); }
  get face() { return __ptrOut(__dv(this).getBigUint64(8, true)); }
  set face(v) { __dv(this).setBigUint64(8, __ptrIn(v), true); }
  get next() { return __ptrOut(__dv(this).getBigUint64(16, true)); }
  set next(v) { __dv(this).setBigUint64(16, __ptrIn(v), true); }
  get glyph_index() { return __dv(this).getUint32(24, true); }
  set glyph_index(v) { __dv(this).setUint32(24, v, true); }
  get generic() { return new Uint8Array(this, 32, 16); }
  set generic(v) { new Uint8Array(this, 32, 16).set(__bytes(v)); }
  get metrics() { return FT_Glyph_Metrics_.at(__ptr(this, 48), this); }
  set metrics(v) { new Uint8Array(this, 48, 64).set(__bytes(v)); }
  get linearHoriAdvance() { return __dv(this).getBigInt64(112, true); }
  set linearHoriAdvance(v) { __dv(this).setBigInt64(112, BigInt(v), true); }
  get linearVertAdvance() { return __dv(this).getBigInt64(120, true); }
  set linearVertAdvance(v) { __dv(this).setBigInt64(120, BigInt(v), true); }
  get advance() { return new Uint8Array(this, 128, 16); }
  set advance(v) { new Uint8Array(this, 128, 16).set(__bytes(v)); }
  get format() { return __dv(this).getInt32(144, true); }
  set format(v) { __dv(this).setInt32(144, v, true); }
  get bitmap() { return new Uint8Array(this, 152, 40); }
  set bitmap(v) { new Uint8Array(this, 152, 40).set(__bytes(v)); }
  get bitmap_left() { return __dv(this).getInt32(192, true); }
  set bitmap_left(v) { __dv(this).setInt32(192, v, true); }
  get bitmap_top() { return __dv(this).getInt32(196, true); }
  set bitmap_top(v) { __dv(this).setInt32(196, v, true); }
  get outline() { return new Uint8Array(this, 200, 40); }
  set outline(v) { new Uint8Array(this, 200, 40).set(__bytes(v)); }
  get num_subglyphs() { return __dv(this).getUint32(240, true); }
  set num_subglyphs(v) { __dv(this).setUint32(240, v, true); }
  get subglyphs() { return __ptrOut(__dv(this).getBigUint64(248, true)); }
  set subglyphs(v) { __dv(this).setBigUint64(248, __ptrIn(v), true); }
  get control_data() { return __ptrOut(__dv(this).getBigUint64(256, true)); }
  set control_data(v) { __dv(this).setBigUint64(256, __ptrIn(v), true); }
  get control_len() { return __dv(this).getBigInt64(264, true); }
  set control_len(v) { __dv(this).setBigInt64(264, BigInt(v), true); }
  get lsb_delta() { return __dv(this).getBigInt64(272, true); }
  set lsb_delta(v) { __dv(this).setBigInt64(272, BigInt(v), true); }
  get rsb_delta() { return __dv(this).getBigInt64(280, true); }
  set rsb_delta(v) { __dv(this).setBigInt64(280, BigInt(v), true); }
  get other() { return __ptrOut(__dv(this).getBigUint64(288, true)); }
  set other(v) { __dv(this).setBigUint64(288, __ptrIn(v), true); }
  get internal() { return __ptrOut(__dv(this).getBigUint64(296, true)); }
  set internal(v) { __dv(this).setBigUint64(296, __ptrIn(v), true); }
}
FT_GlyphSlotRec_.size = 304;
FT_GlyphSlotRec_.align = 8;
FT_GlyphSlotRec_.fields = {library:{type:'struct FT_LibraryRec_ *',offset:0},face:{type:'struct FT_FaceRec_ *',offset:8},next:{type:'struct FT_GlyphSlotRec_ *',offset:16},glyph_index:{type:'u32',offset:24},generic:{type:'FT_Generic',offset:32},metrics:{type:'FT_Glyph_Metrics',offset:48},linearHoriAdvance:{type:'i64',offset:112},linearVertAdvance:{type:'i64',offset:120},advance:{type:'FT_Vector',offset:128},format:{type:'i32',offset:144},bitmap:{type:'FT_Bitmap',offset:152},bitmap_left:{type:'i32',offset:192},bitmap_top:{type:'i32',offset:196},outline:{type:'FT_Outline',offset:200},num_subglyphs:{type:'u32',offset:240},subglyphs:{type:'struct FT_SubGlyphRec_ *',offset:248},control_data:{type:'void *',offset:256},control_len:{type:'i64',offset:264},lsb_delta:{type:'i64',offset:272},rsb_delta:{type:'i64',offset:280},other:{type:'void *',offset:288},internal:{type:'struct FT_Slot_InternalRec_ *',offset:296}};

/* struct FT_Parameter_, 16 bytes (line 2442) */
/**
 * struct FT_Parameter_, 16 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=16] - a byte length, or bytes to copy
 * @property {bigint} tag - FT_ULong, offset 0
 * @property {Uint8Array} data - FT_Pointer, offset 8
 */
export class FT_Parameter_ extends ArrayBuffer {
  constructor(init = 16) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 16) { return __view(FT_Parameter_, p, size, owner); }
  get ptr() { return __ptr(this); }
  get tag() { return __dv(this).getBigUint64(0, true); }
  set tag(v) { __dv(this).setBigUint64(0, BigInt(v), true); }
  get data() { return new Uint8Array(this, 8, 8); }
  set data(v) { new Uint8Array(this, 8, 8).set(__bytes(v)); }
}
FT_Parameter_.size = 16;
FT_Parameter_.align = 8;
FT_Parameter_.fields = {tag:{type:'u64',offset:0},data:{type:'void *',offset:8}};

/* struct FT_Open_Args_, 64 bytes (line 2517) */
/**
 * struct FT_Open_Args_, 64 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=64] - a byte length, or bytes to copy
 * @property {number} flags - FT_UInt, offset 0
 * @property {number|bigint|null} memory_base - const FT_Byte *, offset 8
 * @property {bigint} memory_size - FT_Long, offset 16
 * @property {number|bigint|null} pathname - FT_String *, offset 24
 * @property {Uint8Array} stream - FT_Stream, offset 32
 * @property {number|bigint|null} driver - FT_Module, offset 40
 * @property {number} num_params - FT_Int, offset 48
 * @property {FT_Parameter_|null} params - FT_Parameter *, offset 56
 */
export class FT_Open_Args_ extends ArrayBuffer {
  constructor(init = 64) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 64) { return __view(FT_Open_Args_, p, size, owner); }
  get ptr() { return __ptr(this); }
  get flags() { return __dv(this).getUint32(0, true); }
  set flags(v) { __dv(this).setUint32(0, v, true); }
  get memory_base() { return __ptrOut(__dv(this).getBigUint64(8, true)); }
  set memory_base(v) { __dv(this).setBigUint64(8, __ptrIn(v), true); }
  get memory_size() { return __dv(this).getBigInt64(16, true); }
  set memory_size(v) { __dv(this).setBigInt64(16, BigInt(v), true); }
  get pathname() { return __ptrOut(__dv(this).getBigUint64(24, true)); }
  set pathname(v) { __dv(this).setBigUint64(24, __ptrIn(v), true); }
  get stream() { return new Uint8Array(this, 32, 8); }
  set stream(v) { new Uint8Array(this, 32, 8).set(__bytes(v)); }
  get driver() { return __ptrOut(__dv(this).getBigUint64(40, true)); }
  set driver(v) { __dv(this).setBigUint64(40, __ptrIn(v), true); }
  get num_params() { return __dv(this).getInt32(48, true); }
  set num_params(v) { __dv(this).setInt32(48, v, true); }
  get params() { const p = __dv(this).getBigUint64(56, true); return p === 0n ? null : FT_Parameter_.at(p); }
  set params(v) { __dv(this).setBigUint64(56, __ptrIn(v), true); }
}
FT_Open_Args_.size = 64;
FT_Open_Args_.align = 8;
FT_Open_Args_.fields = {flags:{type:'u32',offset:0},memory_base:{type:'FT_Byte *',offset:8},memory_size:{type:'i64',offset:16},pathname:{type:'FT_String *',offset:24},stream:{type:'struct FT_StreamRec_ *',offset:32},driver:{type:'struct FT_ModuleRec_ *',offset:40},num_params:{type:'i32',offset:48},params:{type:'FT_Parameter *',offset:56}};

/* struct FT_Size_RequestRec_, 32 bytes (line 3027) */
/**
 * struct FT_Size_RequestRec_, 32 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=32] - a byte length, or bytes to copy
 * @property {number} type - FT_Size_Request_Type, offset 0
 * @property {bigint} width - FT_Long, offset 8
 * @property {bigint} height - FT_Long, offset 16
 * @property {number} horiResolution - FT_UInt, offset 24
 * @property {number} vertResolution - FT_UInt, offset 28
 */
export class FT_Size_RequestRec_ extends ArrayBuffer {
  constructor(init = 32) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 32) { return __view(FT_Size_RequestRec_, p, size, owner); }
  get ptr() { return __ptr(this); }
  get type() { return __dv(this).getInt32(0, true); }
  set type(v) { __dv(this).setInt32(0, v, true); }
  get width() { return __dv(this).getBigInt64(8, true); }
  set width(v) { __dv(this).setBigInt64(8, BigInt(v), true); }
  get height() { return __dv(this).getBigInt64(16, true); }
  set height(v) { __dv(this).setBigInt64(16, BigInt(v), true); }
  get horiResolution() { return __dv(this).getUint32(24, true); }
  set horiResolution(v) { __dv(this).setUint32(24, v, true); }
  get vertResolution() { return __dv(this).getUint32(28, true); }
  set vertResolution(v) { __dv(this).setUint32(28, v, true); }
}
FT_Size_RequestRec_.size = 32;
FT_Size_RequestRec_.align = 8;
FT_Size_RequestRec_.fields = {type:{type:'i32',offset:0},width:{type:'i64',offset:8},height:{type:'i64',offset:16},horiResolution:{type:'u32',offset:24},vertResolution:{type:'u32',offset:28}};

export const FT_Glyph_Metrics = FT_Glyph_Metrics_;
export const FT_Bitmap_Size = FT_Bitmap_Size_;
export const FT_CharMapRec = FT_CharMapRec_;
export const FT_FaceRec = FT_FaceRec_;
export const FT_Size_Metrics = FT_Size_Metrics_;
export const FT_SizeRec = FT_SizeRec_;
export const FT_GlyphSlotRec = FT_GlyphSlotRec_;
export const FT_Parameter = FT_Parameter_;
export const FT_Open_Args = FT_Open_Args_;
export const FT_Size_RequestRec = FT_Size_RequestRec_;

/**
 * FT_Init_FreeType
 * @param {object|number|bigint|null} alibrary - FT_Library *
 * @returns {number} - i32
 */
export const FT_Init_FreeType = CFunction({ptr:__sym('FT_Init_FreeType'),args:['FT_Library *'],returns:'i32'});
/**
 * FT_Done_FreeType
 * @param {object|number|bigint|null} library - struct FT_LibraryRec_ *
 * @returns {number} - i32
 */
export const FT_Done_FreeType = CFunction({ptr:__sym('FT_Done_FreeType'),args:['struct FT_LibraryRec_ *'],returns:'i32'});
/**
 * FT_New_Face
 * @param {object|number|bigint|null} library - struct FT_LibraryRec_ *
 * @param {string|null} filepathname - cstring
 * @param {bigint|number} face_index - i64
 * @param {object|number|bigint|null} aface - FT_Face *
 * @returns {number} - i32
 */
export const FT_New_Face = CFunction({ptr:__sym('FT_New_Face'),args:['struct FT_LibraryRec_ *','cstring','i64','FT_Face *'],returns:'i32'});
/**
 * FT_New_Memory_Face
 * @param {object|number|bigint|null} library - struct FT_LibraryRec_ *
 * @param {object|number|bigint|null} file_base - FT_Byte *
 * @param {bigint|number} file_size - i64
 * @param {bigint|number} face_index - i64
 * @param {object|number|bigint|null} aface - FT_Face *
 * @returns {number} - i32
 */
export const FT_New_Memory_Face = CFunction({ptr:__sym('FT_New_Memory_Face'),args:['struct FT_LibraryRec_ *','FT_Byte *','i64','i64','FT_Face *'],returns:'i32'});
/**
 * FT_Open_Face
 * @param {object|number|bigint|null} library - struct FT_LibraryRec_ *
 * @param {object|number|bigint|null} args - FT_Open_Args *
 * @param {bigint|number} face_index - i64
 * @param {object|number|bigint|null} aface - FT_Face *
 * @returns {number} - i32
 */
export const FT_Open_Face = CFunction({ptr:__sym('FT_Open_Face'),args:['struct FT_LibraryRec_ *','FT_Open_Args *','i64','FT_Face *'],returns:'i32'});
/**
 * FT_Attach_File
 * @param {object|number|bigint|null} face - struct FT_FaceRec_ *
 * @param {string|null} filepathname - cstring
 * @returns {number} - i32
 */
export const FT_Attach_File = CFunction({ptr:__sym('FT_Attach_File'),args:['struct FT_FaceRec_ *','cstring'],returns:'i32'});
/**
 * FT_Attach_Stream
 * @param {object|number|bigint|null} face - struct FT_FaceRec_ *
 * @param {object|number|bigint|null} parameters - FT_Open_Args *
 * @returns {number} - i32
 */
export const FT_Attach_Stream = CFunction({ptr:__sym('FT_Attach_Stream'),args:['struct FT_FaceRec_ *','FT_Open_Args *'],returns:'i32'});
/**
 * FT_Reference_Face
 * @param {object|number|bigint|null} face - struct FT_FaceRec_ *
 * @returns {number} - i32
 */
export const FT_Reference_Face = CFunction({ptr:__sym('FT_Reference_Face'),args:['struct FT_FaceRec_ *'],returns:'i32'});
/**
 * FT_Done_Face
 * @param {object|number|bigint|null} face - struct FT_FaceRec_ *
 * @returns {number} - i32
 */
export const FT_Done_Face = CFunction({ptr:__sym('FT_Done_Face'),args:['struct FT_FaceRec_ *'],returns:'i32'});
/**
 * FT_Select_Size
 * @param {object|number|bigint|null} face - struct FT_FaceRec_ *
 * @param {number} strike_index - i32
 * @returns {number} - i32
 */
export const FT_Select_Size = CFunction({ptr:__sym('FT_Select_Size'),args:['struct FT_FaceRec_ *','i32'],returns:'i32'});
/**
 * FT_Request_Size
 * @param {object|number|bigint|null} face - struct FT_FaceRec_ *
 * @param {object|number|bigint|null} req - struct FT_Size_RequestRec_ *
 * @returns {number} - i32
 */
export const FT_Request_Size = CFunction({ptr:__sym('FT_Request_Size'),args:['struct FT_FaceRec_ *','struct FT_Size_RequestRec_ *'],returns:'i32'});
/**
 * FT_Set_Char_Size
 * @param {object|number|bigint|null} face - struct FT_FaceRec_ *
 * @param {bigint|number} char_width - i64
 * @param {bigint|number} char_height - i64
 * @param {number} horz_resolution - u32
 * @param {number} vert_resolution - u32
 * @returns {number} - i32
 */
export const FT_Set_Char_Size = CFunction({ptr:__sym('FT_Set_Char_Size'),args:['struct FT_FaceRec_ *','i64','i64','u32','u32'],returns:'i32'});
/**
 * FT_Set_Pixel_Sizes
 * @param {object|number|bigint|null} face - struct FT_FaceRec_ *
 * @param {number} pixel_width - u32
 * @param {number} pixel_height - u32
 * @returns {number} - i32
 */
export const FT_Set_Pixel_Sizes = CFunction({ptr:__sym('FT_Set_Pixel_Sizes'),args:['struct FT_FaceRec_ *','u32','u32'],returns:'i32'});
/**
 * FT_Load_Glyph
 * @param {object|number|bigint|null} face - struct FT_FaceRec_ *
 * @param {number} glyph_index - u32
 * @param {number} load_flags - i32
 * @returns {number} - i32
 */
export const FT_Load_Glyph = CFunction({ptr:__sym('FT_Load_Glyph'),args:['struct FT_FaceRec_ *','u32','i32'],returns:'i32'});
/**
 * FT_Load_Char
 * @param {object|number|bigint|null} face - struct FT_FaceRec_ *
 * @param {bigint|number} char_code - u64
 * @param {number} load_flags - i32
 * @returns {number} - i32
 */
export const FT_Load_Char = CFunction({ptr:__sym('FT_Load_Char'),args:['struct FT_FaceRec_ *','u64','i32'],returns:'i32'});
/**
 * FT_Set_Transform
 * @param {object|number|bigint|null} face - struct FT_FaceRec_ *
 * @param {object|number|bigint|null} matrix - FT_Matrix *
 * @param {object|number|bigint|null} delta - FT_Vector *
 * @returns {void}
 */
export const FT_Set_Transform = CFunction({ptr:__sym('FT_Set_Transform'),args:['struct FT_FaceRec_ *','FT_Matrix *','FT_Vector *'],returns:'void'});
/**
 * FT_Get_Transform
 * @param {object|number|bigint|null} face - struct FT_FaceRec_ *
 * @param {object|number|bigint|null} matrix - FT_Matrix *
 * @param {object|number|bigint|null} delta - FT_Vector *
 * @returns {void}
 */
export const FT_Get_Transform = CFunction({ptr:__sym('FT_Get_Transform'),args:['struct FT_FaceRec_ *','FT_Matrix *','FT_Vector *'],returns:'void'});
/**
 * FT_Render_Glyph
 * @param {object|number|bigint|null} slot - struct FT_GlyphSlotRec_ *
 * @param {number} render_mode - i32
 * @returns {number} - i32
 */
export const FT_Render_Glyph = CFunction({ptr:__sym('FT_Render_Glyph'),args:['struct FT_GlyphSlotRec_ *','i32'],returns:'i32'});
/**
 * FT_Get_Kerning
 * @param {object|number|bigint|null} face - struct FT_FaceRec_ *
 * @param {number} left_glyph - u32
 * @param {number} right_glyph - u32
 * @param {number} kern_mode - u32
 * @param {object|number|bigint|null} akerning - FT_Vector *
 * @returns {number} - i32
 */
export const FT_Get_Kerning = CFunction({ptr:__sym('FT_Get_Kerning'),args:['struct FT_FaceRec_ *','u32','u32','u32','FT_Vector *'],returns:'i32'});
/**
 * FT_Get_Track_Kerning
 * @param {object|number|bigint|null} face - struct FT_FaceRec_ *
 * @param {bigint|number} point_size - i64
 * @param {number} degree - i32
 * @param {object|number|bigint|null} akerning - FT_Fixed *
 * @returns {number} - i32
 */
export const FT_Get_Track_Kerning = CFunction({ptr:__sym('FT_Get_Track_Kerning'),args:['struct FT_FaceRec_ *','i64','i32','FT_Fixed *'],returns:'i32'});
/**
 * FT_Select_Charmap
 * @param {object|number|bigint|null} face - struct FT_FaceRec_ *
 * @param {number} encoding - i32
 * @returns {number} - i32
 */
export const FT_Select_Charmap = CFunction({ptr:__sym('FT_Select_Charmap'),args:['struct FT_FaceRec_ *','i32'],returns:'i32'});
/**
 * FT_Set_Charmap
 * @param {object|number|bigint|null} face - struct FT_FaceRec_ *
 * @param {object|number|bigint|null} charmap - struct FT_CharMapRec_ *
 * @returns {number} - i32
 */
export const FT_Set_Charmap = CFunction({ptr:__sym('FT_Set_Charmap'),args:['struct FT_FaceRec_ *','struct FT_CharMapRec_ *'],returns:'i32'});
/**
 * FT_Get_Charmap_Index
 * @param {object|number|bigint|null} charmap - struct FT_CharMapRec_ *
 * @returns {number} - i32
 */
export const FT_Get_Charmap_Index = CFunction({ptr:__sym('FT_Get_Charmap_Index'),args:['struct FT_CharMapRec_ *'],returns:'i32'});
/**
 * FT_Get_Char_Index
 * @param {object|number|bigint|null} face - struct FT_FaceRec_ *
 * @param {bigint|number} charcode - u64
 * @returns {number} - u32
 */
export const FT_Get_Char_Index = CFunction({ptr:__sym('FT_Get_Char_Index'),args:['struct FT_FaceRec_ *','u64'],returns:'u32'});
/**
 * FT_Get_First_Char
 * @param {object|number|bigint|null} face - struct FT_FaceRec_ *
 * @param {object|number|bigint|null} agindex - FT_UInt *
 * @returns {bigint} - u64
 */
export const FT_Get_First_Char = CFunction({ptr:__sym('FT_Get_First_Char'),args:['struct FT_FaceRec_ *','FT_UInt *'],returns:'u64'});
/**
 * FT_Get_Next_Char
 * @param {object|number|bigint|null} face - struct FT_FaceRec_ *
 * @param {bigint|number} char_code - u64
 * @param {object|number|bigint|null} agindex - FT_UInt *
 * @returns {bigint} - u64
 */
export const FT_Get_Next_Char = CFunction({ptr:__sym('FT_Get_Next_Char'),args:['struct FT_FaceRec_ *','u64','FT_UInt *'],returns:'u64'});
/**
 * FT_Face_Properties
 * @param {object|number|bigint|null} face - struct FT_FaceRec_ *
 * @param {number} num_properties - u32
 * @param {object|number|bigint|null} properties - FT_Parameter *
 * @returns {number} - i32
 */
export const FT_Face_Properties = CFunction({ptr:__sym('FT_Face_Properties'),args:['struct FT_FaceRec_ *','u32','FT_Parameter *'],returns:'i32'});
/**
 * FT_Get_Name_Index
 * @param {object|number|bigint|null} face - struct FT_FaceRec_ *
 * @param {object|number|bigint|null} glyph_name - FT_String *
 * @returns {number} - u32
 */
export const FT_Get_Name_Index = CFunction({ptr:__sym('FT_Get_Name_Index'),args:['struct FT_FaceRec_ *','FT_String *'],returns:'u32'});
/**
 * FT_Get_Glyph_Name
 * @param {object|number|bigint|null} face - struct FT_FaceRec_ *
 * @param {number} glyph_index - u32
 * @param {object|number|bigint|null} buffer - void *
 * @param {number} buffer_max - u32
 * @returns {number} - i32
 */
export const FT_Get_Glyph_Name = CFunction({ptr:__sym('FT_Get_Glyph_Name'),args:['struct FT_FaceRec_ *','u32','void *','u32'],returns:'i32'});
/**
 * FT_Get_Postscript_Name
 * @param {object|number|bigint|null} face - struct FT_FaceRec_ *
 * @returns {string} - cstring
 */
export const FT_Get_Postscript_Name = CFunction({ptr:__sym('FT_Get_Postscript_Name'),args:['struct FT_FaceRec_ *'],returns:'cstring'});
/**
 * FT_Get_SubGlyph_Info
 * @param {object|number|bigint|null} glyph - struct FT_GlyphSlotRec_ *
 * @param {number} sub_index - u32
 * @param {object|number|bigint|null} p_index - FT_Int *
 * @param {object|number|bigint|null} p_flags - FT_UInt *
 * @param {object|number|bigint|null} p_arg1 - FT_Int *
 * @param {object|number|bigint|null} p_arg2 - FT_Int *
 * @param {object|number|bigint|null} p_transform - FT_Matrix *
 * @returns {number} - i32
 */
export const FT_Get_SubGlyph_Info = CFunction({ptr:__sym('FT_Get_SubGlyph_Info'),args:['struct FT_GlyphSlotRec_ *','u32','FT_Int *','FT_UInt *','FT_Int *','FT_Int *','FT_Matrix *'],returns:'i32'});
/**
 * FT_Get_FSType_Flags
 * @param {object|number|bigint|null} face - struct FT_FaceRec_ *
 * @returns {number} - u16
 */
export const FT_Get_FSType_Flags = CFunction({ptr:__sym('FT_Get_FSType_Flags'),args:['struct FT_FaceRec_ *'],returns:'u16'});
/**
 * FT_Face_GetCharVariantIndex
 * @param {object|number|bigint|null} face - struct FT_FaceRec_ *
 * @param {bigint|number} charcode - u64
 * @param {bigint|number} variantSelector - u64
 * @returns {number} - u32
 */
export const FT_Face_GetCharVariantIndex = CFunction({ptr:__sym('FT_Face_GetCharVariantIndex'),args:['struct FT_FaceRec_ *','u64','u64'],returns:'u32'});
/**
 * FT_Face_GetCharVariantIsDefault
 * @param {object|number|bigint|null} face - struct FT_FaceRec_ *
 * @param {bigint|number} charcode - u64
 * @param {bigint|number} variantSelector - u64
 * @returns {number} - i32
 */
export const FT_Face_GetCharVariantIsDefault = CFunction({ptr:__sym('FT_Face_GetCharVariantIsDefault'),args:['struct FT_FaceRec_ *','u64','u64'],returns:'i32'});
/**
 * FT_Face_GetVariantSelectors
 * @param {object|number|bigint|null} face - struct FT_FaceRec_ *
 * @returns {number|bigint|null} - FT_UInt32 *
 */
export const FT_Face_GetVariantSelectors = CFunction({ptr:__sym('FT_Face_GetVariantSelectors'),args:['struct FT_FaceRec_ *'],returns:'FT_UInt32 *'});
/**
 * FT_Face_GetVariantsOfChar
 * @param {object|number|bigint|null} face - struct FT_FaceRec_ *
 * @param {bigint|number} charcode - u64
 * @returns {number|bigint|null} - FT_UInt32 *
 */
export const FT_Face_GetVariantsOfChar = CFunction({ptr:__sym('FT_Face_GetVariantsOfChar'),args:['struct FT_FaceRec_ *','u64'],returns:'FT_UInt32 *'});
/**
 * FT_Face_GetCharsOfVariant
 * @param {object|number|bigint|null} face - struct FT_FaceRec_ *
 * @param {bigint|number} variantSelector - u64
 * @returns {number|bigint|null} - FT_UInt32 *
 */
export const FT_Face_GetCharsOfVariant = CFunction({ptr:__sym('FT_Face_GetCharsOfVariant'),args:['struct FT_FaceRec_ *','u64'],returns:'FT_UInt32 *'});
/**
 * FT_MulDiv
 * @param {bigint|number} a - i64
 * @param {bigint|number} b - i64
 * @param {bigint|number} c - i64
 * @returns {bigint} - i64
 */
export const FT_MulDiv = CFunction({ptr:__sym('FT_MulDiv'),args:['i64','i64','i64'],returns:'i64'});
/**
 * FT_MulFix
 * @param {bigint|number} a - i64
 * @param {bigint|number} b - i64
 * @returns {bigint} - i64
 */
export const FT_MulFix = CFunction({ptr:__sym('FT_MulFix'),args:['i64','i64'],returns:'i64'});
/**
 * FT_DivFix
 * @param {bigint|number} a - i64
 * @param {bigint|number} b - i64
 * @returns {bigint} - i64
 */
export const FT_DivFix = CFunction({ptr:__sym('FT_DivFix'),args:['i64','i64'],returns:'i64'});
/**
 * FT_RoundFix
 * @param {bigint|number} a - i64
 * @returns {bigint} - i64
 */
export const FT_RoundFix = CFunction({ptr:__sym('FT_RoundFix'),args:['i64'],returns:'i64'});
/**
 * FT_CeilFix
 * @param {bigint|number} a - i64
 * @returns {bigint} - i64
 */
export const FT_CeilFix = CFunction({ptr:__sym('FT_CeilFix'),args:['i64'],returns:'i64'});
/**
 * FT_FloorFix
 * @param {bigint|number} a - i64
 * @returns {bigint} - i64
 */
export const FT_FloorFix = CFunction({ptr:__sym('FT_FloorFix'),args:['i64'],returns:'i64'});
/**
 * FT_Vector_Transform
 * @param {object|number|bigint|null} vector - FT_Vector *
 * @param {object|number|bigint|null} matrix - FT_Matrix *
 * @returns {void}
 */
export const FT_Vector_Transform = CFunction({ptr:__sym('FT_Vector_Transform'),args:['FT_Vector *','FT_Matrix *'],returns:'void'});
/**
 * FT_Library_Version
 * @param {object|number|bigint|null} library - struct FT_LibraryRec_ *
 * @param {object|number|bigint|null} amajor - FT_Int *
 * @param {object|number|bigint|null} aminor - FT_Int *
 * @param {object|number|bigint|null} apatch - FT_Int *
 * @returns {void}
 */
export const FT_Library_Version = CFunction({ptr:__sym('FT_Library_Version'),args:['struct FT_LibraryRec_ *','FT_Int *','FT_Int *','FT_Int *'],returns:'void'});
/**
 * FT_Face_CheckTrueTypePatents
 * @param {object|number|bigint|null} face - struct FT_FaceRec_ *
 * @returns {number} - u8
 */
export const FT_Face_CheckTrueTypePatents = CFunction({ptr:__sym('FT_Face_CheckTrueTypePatents'),args:['struct FT_FaceRec_ *'],returns:'u8'});
/**
 * FT_Face_SetUnpatentedHinting
 * @param {object|number|bigint|null} face - struct FT_FaceRec_ *
 * @param {number} value - u8
 * @returns {number} - u8
 */
export const FT_Face_SetUnpatentedHinting = CFunction({ptr:__sym('FT_Face_SetUnpatentedHinting'),args:['struct FT_FaceRec_ *','u8'],returns:'u8'});
