/* Auto-generated by qjsm tools/gen-bindings.js from /usr/include/x86_64-linux-gnu/curl/curl.h -- do not edit by hand.
 * Regenerate with:
 *   qjsm tools/gen-bindings.js --api=cfunction --library=libcurl.so.4 --structs --jsdoc --follow-includes  /usr/include/x86_64-linux-gnu/curl/curl.h
 * (clang invocation used to build the AST, once per source: clang -Xclang -ast-dump=json -fsyntax-only <source>)
 */
import { CFunction, toArrayBuffer, ptr as __ptr, toString as __cstr, dlsym, dlopen, RTLD_NOW } from 'ffi';

const __lib = dlopen("libcurl.so.4", RTLD_NOW);
if (__lib == null) throw new Error("gen-bindings: dlopen(libcurl.so.4) failed");

function __sym(name) {
  const p = dlsym(__lib, name);
  if(p == null) throw new Error("gen-bindings: symbol not found: " + name);
  return p;
}

// enum (anonymous)
export const CURLE_OK = 0;
export const CURLE_UNSUPPORTED_PROTOCOL = 1;
export const CURLE_FAILED_INIT = 2;
export const CURLE_URL_MALFORMAT = 3;
export const CURLE_NOT_BUILT_IN = 4;
export const CURLE_COULDNT_RESOLVE_PROXY = 5;
export const CURLE_COULDNT_RESOLVE_HOST = 6;
export const CURLE_COULDNT_CONNECT = 7;
export const CURLE_WEIRD_SERVER_REPLY = 8;
export const CURLE_REMOTE_ACCESS_DENIED = 9;
export const CURLE_FTP_ACCEPT_FAILED = 10;
export const CURLE_FTP_WEIRD_PASS_REPLY = 11;
export const CURLE_FTP_ACCEPT_TIMEOUT = 12;
export const CURLE_FTP_WEIRD_PASV_REPLY = 13;
export const CURLE_FTP_WEIRD_227_FORMAT = 14;
export const CURLE_FTP_CANT_GET_HOST = 15;
export const CURLE_HTTP2 = 16;
export const CURLE_FTP_COULDNT_SET_TYPE = 17;
export const CURLE_PARTIAL_FILE = 18;
export const CURLE_FTP_COULDNT_RETR_FILE = 19;
export const CURLE_OBSOLETE20 = 20;
export const CURLE_QUOTE_ERROR = 21;
export const CURLE_HTTP_RETURNED_ERROR = 22;
export const CURLE_WRITE_ERROR = 23;
export const CURLE_OBSOLETE24 = 24;
export const CURLE_UPLOAD_FAILED = 25;
export const CURLE_READ_ERROR = 26;
export const CURLE_OUT_OF_MEMORY = 27;
export const CURLE_OPERATION_TIMEDOUT = 28;
export const CURLE_OBSOLETE29 = 29;
export const CURLE_FTP_PORT_FAILED = 30;
export const CURLE_FTP_COULDNT_USE_REST = 31;
export const CURLE_OBSOLETE32 = 32;
export const CURLE_RANGE_ERROR = 33;
export const CURLE_HTTP_POST_ERROR = 34;
export const CURLE_SSL_CONNECT_ERROR = 35;
export const CURLE_BAD_DOWNLOAD_RESUME = 36;
export const CURLE_FILE_COULDNT_READ_FILE = 37;
export const CURLE_LDAP_CANNOT_BIND = 38;
export const CURLE_LDAP_SEARCH_FAILED = 39;
export const CURLE_OBSOLETE40 = 40;
export const CURLE_FUNCTION_NOT_FOUND = 41;
export const CURLE_ABORTED_BY_CALLBACK = 42;
export const CURLE_BAD_FUNCTION_ARGUMENT = 43;
export const CURLE_OBSOLETE44 = 44;
export const CURLE_INTERFACE_FAILED = 45;
export const CURLE_OBSOLETE46 = 46;
export const CURLE_TOO_MANY_REDIRECTS = 47;
export const CURLE_UNKNOWN_OPTION = 48;
export const CURLE_SETOPT_OPTION_SYNTAX = 49;
export const CURLE_OBSOLETE50 = 50;
export const CURLE_OBSOLETE51 = 51;
export const CURLE_GOT_NOTHING = 52;
export const CURLE_SSL_ENGINE_NOTFOUND = 53;
export const CURLE_SSL_ENGINE_SETFAILED = 54;
export const CURLE_SEND_ERROR = 55;
export const CURLE_RECV_ERROR = 56;
export const CURLE_OBSOLETE57 = 57;
export const CURLE_SSL_CERTPROBLEM = 58;
export const CURLE_SSL_CIPHER = 59;
export const CURLE_PEER_FAILED_VERIFICATION = 60;
export const CURLE_BAD_CONTENT_ENCODING = 61;
export const CURLE_OBSOLETE62 = 62;
export const CURLE_FILESIZE_EXCEEDED = 63;
export const CURLE_USE_SSL_FAILED = 64;
export const CURLE_SEND_FAIL_REWIND = 65;
export const CURLE_SSL_ENGINE_INITFAILED = 66;
export const CURLE_LOGIN_DENIED = 67;
export const CURLE_TFTP_NOTFOUND = 68;
export const CURLE_TFTP_PERM = 69;
export const CURLE_REMOTE_DISK_FULL = 70;
export const CURLE_TFTP_ILLEGAL = 71;
export const CURLE_TFTP_UNKNOWNID = 72;
export const CURLE_REMOTE_FILE_EXISTS = 73;
export const CURLE_TFTP_NOSUCHUSER = 74;
export const CURLE_OBSOLETE75 = 75;
export const CURLE_OBSOLETE76 = 76;
export const CURLE_SSL_CACERT_BADFILE = 77;
export const CURLE_REMOTE_FILE_NOT_FOUND = 78;
export const CURLE_SSH = 79;
export const CURLE_SSL_SHUTDOWN_FAILED = 80;
export const CURLE_AGAIN = 81;
export const CURLE_SSL_CRL_BADFILE = 82;
export const CURLE_SSL_ISSUER_ERROR = 83;
export const CURLE_FTP_PRET_FAILED = 84;
export const CURLE_RTSP_CSEQ_ERROR = 85;
export const CURLE_RTSP_SESSION_ERROR = 86;
export const CURLE_FTP_BAD_FILE_LIST = 87;
export const CURLE_CHUNK_FAILED = 88;
export const CURLE_NO_CONNECTION_AVAILABLE = 89;
export const CURLE_SSL_PINNEDPUBKEYNOTMATCH = 90;
export const CURLE_SSL_INVALIDCERTSTATUS = 91;
export const CURLE_HTTP2_STREAM = 92;
export const CURLE_RECURSIVE_API_CALL = 93;
export const CURLE_AUTH_ERROR = 94;
export const CURLE_HTTP3 = 95;
export const CURLE_QUIC_CONNECT_ERROR = 96;
export const CURLE_PROXY = 97;
export const CURLE_SSL_CLIENTCERT = 98;
export const CURLE_UNRECOVERABLE_POLL = 99;
export const CURL_LAST = 100;

// enum (anonymous)
export const CURLSSLSET_OK = 0;
export const CURLSSLSET_UNKNOWN_BACKEND = 1;
export const CURLSSLSET_TOO_LATE = 2;
export const CURLSSLSET_NO_BACKENDS = 3;

// enum (anonymous)
export const CURLSSLBACKEND_NONE = 0;
export const CURLSSLBACKEND_OPENSSL = 1;
export const CURLSSLBACKEND_GNUTLS = 2;
export const CURLSSLBACKEND_NSS = 3;
export const CURLSSLBACKEND_OBSOLETE4 = 4;
export const CURLSSLBACKEND_GSKIT = 5;
export const CURLSSLBACKEND_POLARSSL = 6;
export const CURLSSLBACKEND_WOLFSSL = 7;
export const CURLSSLBACKEND_SCHANNEL = 8;
export const CURLSSLBACKEND_SECURETRANSPORT = 9;
export const CURLSSLBACKEND_AXTLS = 10;
export const CURLSSLBACKEND_MBEDTLS = 11;
export const CURLSSLBACKEND_MESALINK = 12;
export const CURLSSLBACKEND_BEARSSL = 13;
export const CURLSSLBACKEND_RUSTLS = 14;

// enum (anonymous)
export const CURLSHE_OK = 0;
export const CURLSHE_BAD_OPTION = 1;
export const CURLSHE_IN_USE = 2;
export const CURLSHE_INVALID = 3;
export const CURLSHE_NOMEM = 4;
export const CURLSHE_NOT_BUILT_IN = 5;
export const CURLSHE_LAST = 6;

// enum (anonymous)
export const CURLVERSION_FIRST = 0;
export const CURLVERSION_SECOND = 1;
export const CURLVERSION_THIRD = 2;
export const CURLVERSION_FOURTH = 3;
export const CURLVERSION_FIFTH = 4;
export const CURLVERSION_SIXTH = 5;
export const CURLVERSION_SEVENTH = 6;
export const CURLVERSION_EIGHTH = 7;
export const CURLVERSION_NINTH = 8;
export const CURLVERSION_TENTH = 9;
export const CURLVERSION_ELEVENTH = 10;
export const CURLVERSION_LAST = 11;

// enum (anonymous)
export const CURLM_CALL_MULTI_PERFORM = -1;
export const CURLM_OK = 0;
export const CURLM_BAD_HANDLE = 1;
export const CURLM_BAD_EASY_HANDLE = 2;
export const CURLM_OUT_OF_MEMORY = 3;
export const CURLM_INTERNAL_ERROR = 4;
export const CURLM_BAD_SOCKET = 5;
export const CURLM_UNKNOWN_OPTION = 6;
export const CURLM_ADDED_ALREADY = 7;
export const CURLM_RECURSIVE_API_CALL = 8;
export const CURLM_WAKEUP_FAILURE = 9;
export const CURLM_BAD_FUNCTION_ARGUMENT = 10;
export const CURLM_ABORTED_BY_CALLBACK = 11;
export const CURLM_UNRECOVERABLE_POLL = 12;
export const CURLM_LAST = 13;

// enum (anonymous)
export const CURLUE_OK = 0;
export const CURLUE_BAD_HANDLE = 1;
export const CURLUE_BAD_PARTPOINTER = 2;
export const CURLUE_MALFORMED_INPUT = 3;
export const CURLUE_BAD_PORT_NUMBER = 4;
export const CURLUE_UNSUPPORTED_SCHEME = 5;
export const CURLUE_URLDECODE = 6;
export const CURLUE_OUT_OF_MEMORY = 7;
export const CURLUE_USER_NOT_ALLOWED = 8;
export const CURLUE_UNKNOWN_PART = 9;
export const CURLUE_NO_SCHEME = 10;
export const CURLUE_NO_USER = 11;
export const CURLUE_NO_PASSWORD = 12;
export const CURLUE_NO_OPTIONS = 13;
export const CURLUE_NO_HOST = 14;
export const CURLUE_NO_PORT = 15;
export const CURLUE_NO_QUERY = 16;
export const CURLUE_NO_FRAGMENT = 17;
export const CURLUE_NO_ZONEID = 18;
export const CURLUE_BAD_FILE_URL = 19;
export const CURLUE_BAD_FRAGMENT = 20;
export const CURLUE_BAD_HOSTNAME = 21;
export const CURLUE_BAD_IPV6 = 22;
export const CURLUE_BAD_LOGIN = 23;
export const CURLUE_BAD_PASSWORD = 24;
export const CURLUE_BAD_PATH = 25;
export const CURLUE_BAD_QUERY = 26;
export const CURLUE_BAD_SCHEME = 27;
export const CURLUE_BAD_SLASHES = 28;
export const CURLUE_BAD_USER = 29;
export const CURLUE_LACKS_IDN = 30;
export const CURLUE_LAST = 31;

// enum (anonymous)
export const CURLUPART_URL = 0;
export const CURLUPART_SCHEME = 1;
export const CURLUPART_USER = 2;
export const CURLUPART_PASSWORD = 3;
export const CURLUPART_OPTIONS = 4;
export const CURLUPART_HOST = 5;
export const CURLUPART_PORT = 6;
export const CURLUPART_PATH = 7;
export const CURLUPART_QUERY = 8;
export const CURLUPART_FRAGMENT = 9;
export const CURLUPART_ZONEID = 10;

// enum (anonymous)
export const CURLOPT_WRITEDATA = 10001;
export const CURLOPT_URL = 10002;
export const CURLOPT_PORT = 3;
export const CURLOPT_PROXY = 10004;
export const CURLOPT_USERPWD = 10005;
export const CURLOPT_PROXYUSERPWD = 10006;
export const CURLOPT_RANGE = 10007;
export const CURLOPT_READDATA = 10009;
export const CURLOPT_ERRORBUFFER = 10010;
export const CURLOPT_WRITEFUNCTION = 20011;
export const CURLOPT_READFUNCTION = 20012;
export const CURLOPT_TIMEOUT = 13;
export const CURLOPT_INFILESIZE = 14;
export const CURLOPT_POSTFIELDS = 10015;
export const CURLOPT_REFERER = 10016;
export const CURLOPT_FTPPORT = 10017;
export const CURLOPT_USERAGENT = 10018;
export const CURLOPT_LOW_SPEED_LIMIT = 19;
export const CURLOPT_LOW_SPEED_TIME = 20;
export const CURLOPT_RESUME_FROM = 21;
export const CURLOPT_COOKIE = 10022;
export const CURLOPT_HTTPHEADER = 10023;
export const CURLOPT_HTTPPOST = 10024;
export const CURLOPT_SSLCERT = 10025;
export const CURLOPT_KEYPASSWD = 10026;
export const CURLOPT_CRLF = 27;
export const CURLOPT_QUOTE = 10028;
export const CURLOPT_HEADERDATA = 10029;
export const CURLOPT_COOKIEFILE = 10031;
export const CURLOPT_SSLVERSION = 32;
export const CURLOPT_TIMECONDITION = 33;
export const CURLOPT_TIMEVALUE = 34;
export const CURLOPT_CUSTOMREQUEST = 10036;
export const CURLOPT_STDERR = 10037;
export const CURLOPT_POSTQUOTE = 10039;
export const CURLOPT_OBSOLETE40 = 10040;
export const CURLOPT_VERBOSE = 41;
export const CURLOPT_HEADER = 42;
export const CURLOPT_NOPROGRESS = 43;
export const CURLOPT_NOBODY = 44;
export const CURLOPT_FAILONERROR = 45;
export const CURLOPT_UPLOAD = 46;
export const CURLOPT_POST = 47;
export const CURLOPT_DIRLISTONLY = 48;
export const CURLOPT_APPEND = 50;
export const CURLOPT_NETRC = 51;
export const CURLOPT_FOLLOWLOCATION = 52;
export const CURLOPT_TRANSFERTEXT = 53;
export const CURLOPT_PUT = 54;
export const CURLOPT_PROGRESSFUNCTION = 20056;
export const CURLOPT_XFERINFODATA = 10057;
export const CURLOPT_AUTOREFERER = 58;
export const CURLOPT_PROXYPORT = 59;
export const CURLOPT_POSTFIELDSIZE = 60;
export const CURLOPT_HTTPPROXYTUNNEL = 61;
export const CURLOPT_INTERFACE = 10062;
export const CURLOPT_KRBLEVEL = 10063;
export const CURLOPT_SSL_VERIFYPEER = 64;
export const CURLOPT_CAINFO = 10065;
export const CURLOPT_MAXREDIRS = 68;
export const CURLOPT_FILETIME = 69;
export const CURLOPT_TELNETOPTIONS = 10070;
export const CURLOPT_MAXCONNECTS = 71;
export const CURLOPT_OBSOLETE72 = 72;
export const CURLOPT_FRESH_CONNECT = 74;
export const CURLOPT_FORBID_REUSE = 75;
export const CURLOPT_RANDOM_FILE = 10076;
export const CURLOPT_EGDSOCKET = 10077;
export const CURLOPT_CONNECTTIMEOUT = 78;
export const CURLOPT_HEADERFUNCTION = 20079;
export const CURLOPT_HTTPGET = 80;
export const CURLOPT_SSL_VERIFYHOST = 81;
export const CURLOPT_COOKIEJAR = 10082;
export const CURLOPT_SSL_CIPHER_LIST = 10083;
export const CURLOPT_HTTP_VERSION = 84;
export const CURLOPT_FTP_USE_EPSV = 85;
export const CURLOPT_SSLCERTTYPE = 10086;
export const CURLOPT_SSLKEY = 10087;
export const CURLOPT_SSLKEYTYPE = 10088;
export const CURLOPT_SSLENGINE = 10089;
export const CURLOPT_SSLENGINE_DEFAULT = 90;
export const CURLOPT_DNS_USE_GLOBAL_CACHE = 91;
export const CURLOPT_DNS_CACHE_TIMEOUT = 92;
export const CURLOPT_PREQUOTE = 10093;
export const CURLOPT_DEBUGFUNCTION = 20094;
export const CURLOPT_DEBUGDATA = 10095;
export const CURLOPT_COOKIESESSION = 96;
export const CURLOPT_CAPATH = 10097;
export const CURLOPT_BUFFERSIZE = 98;
export const CURLOPT_NOSIGNAL = 99;
export const CURLOPT_SHARE = 10100;
export const CURLOPT_PROXYTYPE = 101;
export const CURLOPT_ACCEPT_ENCODING = 10102;
export const CURLOPT_PRIVATE = 10103;
export const CURLOPT_HTTP200ALIASES = 10104;
export const CURLOPT_UNRESTRICTED_AUTH = 105;
export const CURLOPT_FTP_USE_EPRT = 106;
export const CURLOPT_HTTPAUTH = 107;
export const CURLOPT_SSL_CTX_FUNCTION = 20108;
export const CURLOPT_SSL_CTX_DATA = 10109;
export const CURLOPT_FTP_CREATE_MISSING_DIRS = 110;
export const CURLOPT_PROXYAUTH = 111;
export const CURLOPT_SERVER_RESPONSE_TIMEOUT = 112;
export const CURLOPT_IPRESOLVE = 113;
export const CURLOPT_MAXFILESIZE = 114;
export const CURLOPT_INFILESIZE_LARGE = 30115;
export const CURLOPT_RESUME_FROM_LARGE = 30116;
export const CURLOPT_MAXFILESIZE_LARGE = 30117;
export const CURLOPT_NETRC_FILE = 10118;
export const CURLOPT_USE_SSL = 119;
export const CURLOPT_POSTFIELDSIZE_LARGE = 30120;
export const CURLOPT_TCP_NODELAY = 121;
export const CURLOPT_FTPSSLAUTH = 129;
export const CURLOPT_IOCTLFUNCTION = 20130;
export const CURLOPT_IOCTLDATA = 10131;
export const CURLOPT_FTP_ACCOUNT = 10134;
export const CURLOPT_COOKIELIST = 10135;
export const CURLOPT_IGNORE_CONTENT_LENGTH = 136;
export const CURLOPT_FTP_SKIP_PASV_IP = 137;
export const CURLOPT_FTP_FILEMETHOD = 138;
export const CURLOPT_LOCALPORT = 139;
export const CURLOPT_LOCALPORTRANGE = 140;
export const CURLOPT_CONNECT_ONLY = 141;
export const CURLOPT_CONV_FROM_NETWORK_FUNCTION = 20142;
export const CURLOPT_CONV_TO_NETWORK_FUNCTION = 20143;
export const CURLOPT_CONV_FROM_UTF8_FUNCTION = 20144;
export const CURLOPT_MAX_SEND_SPEED_LARGE = 30145;
export const CURLOPT_MAX_RECV_SPEED_LARGE = 30146;
export const CURLOPT_FTP_ALTERNATIVE_TO_USER = 10147;
export const CURLOPT_SOCKOPTFUNCTION = 20148;
export const CURLOPT_SOCKOPTDATA = 10149;
export const CURLOPT_SSL_SESSIONID_CACHE = 150;
export const CURLOPT_SSH_AUTH_TYPES = 151;
export const CURLOPT_SSH_PUBLIC_KEYFILE = 10152;
export const CURLOPT_SSH_PRIVATE_KEYFILE = 10153;
export const CURLOPT_FTP_SSL_CCC = 154;
export const CURLOPT_TIMEOUT_MS = 155;
export const CURLOPT_CONNECTTIMEOUT_MS = 156;
export const CURLOPT_HTTP_TRANSFER_DECODING = 157;
export const CURLOPT_HTTP_CONTENT_DECODING = 158;
export const CURLOPT_NEW_FILE_PERMS = 159;
export const CURLOPT_NEW_DIRECTORY_PERMS = 160;
export const CURLOPT_POSTREDIR = 161;
export const CURLOPT_SSH_HOST_PUBLIC_KEY_MD5 = 10162;
export const CURLOPT_OPENSOCKETFUNCTION = 20163;
export const CURLOPT_OPENSOCKETDATA = 10164;
export const CURLOPT_COPYPOSTFIELDS = 10165;
export const CURLOPT_PROXY_TRANSFER_MODE = 166;
export const CURLOPT_SEEKFUNCTION = 20167;
export const CURLOPT_SEEKDATA = 10168;
export const CURLOPT_CRLFILE = 10169;
export const CURLOPT_ISSUERCERT = 10170;
export const CURLOPT_ADDRESS_SCOPE = 171;
export const CURLOPT_CERTINFO = 172;
export const CURLOPT_USERNAME = 10173;
export const CURLOPT_PASSWORD = 10174;
export const CURLOPT_PROXYUSERNAME = 10175;
export const CURLOPT_PROXYPASSWORD = 10176;
export const CURLOPT_NOPROXY = 10177;
export const CURLOPT_TFTP_BLKSIZE = 178;
export const CURLOPT_SOCKS5_GSSAPI_SERVICE = 10179;
export const CURLOPT_SOCKS5_GSSAPI_NEC = 180;
export const CURLOPT_PROTOCOLS = 181;
export const CURLOPT_REDIR_PROTOCOLS = 182;
export const CURLOPT_SSH_KNOWNHOSTS = 10183;
export const CURLOPT_SSH_KEYFUNCTION = 20184;
export const CURLOPT_SSH_KEYDATA = 10185;
export const CURLOPT_MAIL_FROM = 10186;
export const CURLOPT_MAIL_RCPT = 10187;
export const CURLOPT_FTP_USE_PRET = 188;
export const CURLOPT_RTSP_REQUEST = 189;
export const CURLOPT_RTSP_SESSION_ID = 10190;
export const CURLOPT_RTSP_STREAM_URI = 10191;
export const CURLOPT_RTSP_TRANSPORT = 10192;
export const CURLOPT_RTSP_CLIENT_CSEQ = 193;
export const CURLOPT_RTSP_SERVER_CSEQ = 194;
export const CURLOPT_INTERLEAVEDATA = 10195;
export const CURLOPT_INTERLEAVEFUNCTION = 20196;
export const CURLOPT_WILDCARDMATCH = 197;
export const CURLOPT_CHUNK_BGN_FUNCTION = 20198;
export const CURLOPT_CHUNK_END_FUNCTION = 20199;
export const CURLOPT_FNMATCH_FUNCTION = 20200;
export const CURLOPT_CHUNK_DATA = 10201;
export const CURLOPT_FNMATCH_DATA = 10202;
export const CURLOPT_RESOLVE = 10203;
export const CURLOPT_TLSAUTH_USERNAME = 10204;
export const CURLOPT_TLSAUTH_PASSWORD = 10205;
export const CURLOPT_TLSAUTH_TYPE = 10206;
export const CURLOPT_TRANSFER_ENCODING = 207;
export const CURLOPT_CLOSESOCKETFUNCTION = 20208;
export const CURLOPT_CLOSESOCKETDATA = 10209;
export const CURLOPT_GSSAPI_DELEGATION = 210;
export const CURLOPT_DNS_SERVERS = 10211;
export const CURLOPT_ACCEPTTIMEOUT_MS = 212;
export const CURLOPT_TCP_KEEPALIVE = 213;
export const CURLOPT_TCP_KEEPIDLE = 214;
export const CURLOPT_TCP_KEEPINTVL = 215;
export const CURLOPT_SSL_OPTIONS = 216;
export const CURLOPT_MAIL_AUTH = 10217;
export const CURLOPT_SASL_IR = 218;
export const CURLOPT_XFERINFOFUNCTION = 20219;
export const CURLOPT_XOAUTH2_BEARER = 10220;
export const CURLOPT_DNS_INTERFACE = 10221;
export const CURLOPT_DNS_LOCAL_IP4 = 10222;
export const CURLOPT_DNS_LOCAL_IP6 = 10223;
export const CURLOPT_LOGIN_OPTIONS = 10224;
export const CURLOPT_SSL_ENABLE_NPN = 225;
export const CURLOPT_SSL_ENABLE_ALPN = 226;
export const CURLOPT_EXPECT_100_TIMEOUT_MS = 227;
export const CURLOPT_PROXYHEADER = 10228;
export const CURLOPT_HEADEROPT = 229;
export const CURLOPT_PINNEDPUBLICKEY = 10230;
export const CURLOPT_UNIX_SOCKET_PATH = 10231;
export const CURLOPT_SSL_VERIFYSTATUS = 232;
export const CURLOPT_SSL_FALSESTART = 233;
export const CURLOPT_PATH_AS_IS = 234;
export const CURLOPT_PROXY_SERVICE_NAME = 10235;
export const CURLOPT_SERVICE_NAME = 10236;
export const CURLOPT_PIPEWAIT = 237;
export const CURLOPT_DEFAULT_PROTOCOL = 10238;
export const CURLOPT_STREAM_WEIGHT = 239;
export const CURLOPT_STREAM_DEPENDS = 10240;
export const CURLOPT_STREAM_DEPENDS_E = 10241;
export const CURLOPT_TFTP_NO_OPTIONS = 242;
export const CURLOPT_CONNECT_TO = 10243;
export const CURLOPT_TCP_FASTOPEN = 244;
export const CURLOPT_KEEP_SENDING_ON_ERROR = 245;
export const CURLOPT_PROXY_CAINFO = 10246;
export const CURLOPT_PROXY_CAPATH = 10247;
export const CURLOPT_PROXY_SSL_VERIFYPEER = 248;
export const CURLOPT_PROXY_SSL_VERIFYHOST = 249;
export const CURLOPT_PROXY_SSLVERSION = 250;
export const CURLOPT_PROXY_TLSAUTH_USERNAME = 10251;
export const CURLOPT_PROXY_TLSAUTH_PASSWORD = 10252;
export const CURLOPT_PROXY_TLSAUTH_TYPE = 10253;
export const CURLOPT_PROXY_SSLCERT = 10254;
export const CURLOPT_PROXY_SSLCERTTYPE = 10255;
export const CURLOPT_PROXY_SSLKEY = 10256;
export const CURLOPT_PROXY_SSLKEYTYPE = 10257;
export const CURLOPT_PROXY_KEYPASSWD = 10258;
export const CURLOPT_PROXY_SSL_CIPHER_LIST = 10259;
export const CURLOPT_PROXY_CRLFILE = 10260;
export const CURLOPT_PROXY_SSL_OPTIONS = 261;
export const CURLOPT_PRE_PROXY = 10262;
export const CURLOPT_PROXY_PINNEDPUBLICKEY = 10263;
export const CURLOPT_ABSTRACT_UNIX_SOCKET = 10264;
export const CURLOPT_SUPPRESS_CONNECT_HEADERS = 265;
export const CURLOPT_REQUEST_TARGET = 10266;
export const CURLOPT_SOCKS5_AUTH = 267;
export const CURLOPT_SSH_COMPRESSION = 268;
export const CURLOPT_MIMEPOST = 10269;
export const CURLOPT_TIMEVALUE_LARGE = 30270;
export const CURLOPT_HAPPY_EYEBALLS_TIMEOUT_MS = 271;
export const CURLOPT_RESOLVER_START_FUNCTION = 20272;
export const CURLOPT_RESOLVER_START_DATA = 10273;
export const CURLOPT_HAPROXYPROTOCOL = 274;
export const CURLOPT_DNS_SHUFFLE_ADDRESSES = 275;
export const CURLOPT_TLS13_CIPHERS = 10276;
export const CURLOPT_PROXY_TLS13_CIPHERS = 10277;
export const CURLOPT_DISALLOW_USERNAME_IN_URL = 278;
export const CURLOPT_DOH_URL = 10279;
export const CURLOPT_UPLOAD_BUFFERSIZE = 280;
export const CURLOPT_UPKEEP_INTERVAL_MS = 281;
export const CURLOPT_CURLU = 10282;
export const CURLOPT_TRAILERFUNCTION = 20283;
export const CURLOPT_TRAILERDATA = 10284;
export const CURLOPT_HTTP09_ALLOWED = 285;
export const CURLOPT_ALTSVC_CTRL = 286;
export const CURLOPT_ALTSVC = 10287;
export const CURLOPT_MAXAGE_CONN = 288;
export const CURLOPT_SASL_AUTHZID = 10289;
export const CURLOPT_MAIL_RCPT_ALLOWFAILS = 290;
export const CURLOPT_SSLCERT_BLOB = 40291;
export const CURLOPT_SSLKEY_BLOB = 40292;
export const CURLOPT_PROXY_SSLCERT_BLOB = 40293;
export const CURLOPT_PROXY_SSLKEY_BLOB = 40294;
export const CURLOPT_ISSUERCERT_BLOB = 40295;
export const CURLOPT_PROXY_ISSUERCERT = 10296;
export const CURLOPT_PROXY_ISSUERCERT_BLOB = 40297;
export const CURLOPT_SSL_EC_CURVES = 10298;
export const CURLOPT_HSTS_CTRL = 299;
export const CURLOPT_HSTS = 10300;
export const CURLOPT_HSTSREADFUNCTION = 20301;
export const CURLOPT_HSTSREADDATA = 10302;
export const CURLOPT_HSTSWRITEFUNCTION = 20303;
export const CURLOPT_HSTSWRITEDATA = 10304;
export const CURLOPT_AWS_SIGV4 = 10305;
export const CURLOPT_DOH_SSL_VERIFYPEER = 306;
export const CURLOPT_DOH_SSL_VERIFYHOST = 307;
export const CURLOPT_DOH_SSL_VERIFYSTATUS = 308;
export const CURLOPT_CAINFO_BLOB = 40309;
export const CURLOPT_PROXY_CAINFO_BLOB = 40310;
export const CURLOPT_SSH_HOST_PUBLIC_KEY_SHA256 = 10311;
export const CURLOPT_PREREQFUNCTION = 20312;
export const CURLOPT_PREREQDATA = 10313;
export const CURLOPT_MAXLIFETIME_CONN = 314;
export const CURLOPT_MIME_OPTIONS = 315;
export const CURLOPT_SSH_HOSTKEYFUNCTION = 20316;
export const CURLOPT_SSH_HOSTKEYDATA = 10317;
export const CURLOPT_PROTOCOLS_STR = 10318;
export const CURLOPT_REDIR_PROTOCOLS_STR = 10319;
export const CURLOPT_WS_OPTIONS = 320;
export const CURLOPT_CA_CACHE_TIMEOUT = 321;
export const CURLOPT_QUICK_EXIT = 322;
export const CURLOPT_HAPROXY_CLIENT_IP = 10323;
export const CURLOPT_LASTENTRY = 10324;

// enum (anonymous)
export const CURLHE_OK = 0;
export const CURLHE_BADINDEX = 1;
export const CURLHE_MISSING = 2;
export const CURLHE_NOHEADERS = 3;
export const CURLHE_NOREQUEST = 4;
export const CURLHE_OUT_OF_MEMORY = 5;
export const CURLHE_BAD_ARGUMENT = 6;
export const CURLHE_NOT_BUILT_IN = 7;

const __dvs = new WeakMap();

function __dv(o) {
  let d = __dvs.get(o);
  if(!d) __dvs.set(o, (d = new DataView(o)));
  return d;
}

function __ptrOut(v) {
  return v === 0n ? null : v <= 0xffffffffn ? Number(v) : v;
}

function __ptrIn(v) {
  return v === null || v === undefined ? 0n : typeof v === "object" ? BigInt(v.ptr !== undefined ? v.ptr : __ptr(v)) : BigInt(v);
}

const __index = /^(0|[1-9]\d*)$/;

function __ptrArray(a, wrap) {
  const at = i => {
    const p = a[i];
    return p === 0n ? null : wrap ? wrap(p) : __ptrOut(p);
  };

  return new Proxy(a, {
    get(t, k) {
      if(typeof k === "string" && __index.test(k)) return Number(k) < t.length ? at(Number(k)) : undefined;
      if(k === Symbol.iterator) return function*() { for(let i = 0; i < t.length; i++) yield at(i); };

      const v = Reflect.get(t, k, t);
      return typeof v === "function" ? v.bind(t) : v;
    },
    set(t, k, v) {
      if(typeof k === "string" && __index.test(k)) {
        if(Number(k) >= t.length) return false;
        t[k] = __ptrIn(v);
        return true;
      }
      return Reflect.set(t, k, v, t);
    },
  });
}

function __bytes(v) {
  return ArrayBuffer.isView(v) ? new Uint8Array(v.buffer, v.byteOffset, v.byteLength) : new Uint8Array(v);
}

function __view(cls, p, size, owner) {
  const b = toArrayBuffer(BigInt(p), 0, size);

  Object.setPrototypeOf(b, cls.prototype);
  if(owner) Object.defineProperty(b, "__owner", { value: owner });
  return b;
}

const __sizes = { bool: 1, i8: 1, u8: 1, i16: 2, u16: 2, i32: 4, u32: 4, i64: 8, u64: 8, i64_fast: 8, u64_fast: 8, f32: 4, f64: 8, pointer: 8, ptr: 8, function: 8, cstring: 8 };

/* A type spelled "T *" is a pointer, whatever T is. */
function __sz(type) {
  return __sizes[type.endsWith("*") ? "pointer" : type];
}

function __read(dv, type, off) {
  if(type.endsWith("*")) type = "pointer";
  switch(type) {
    case "bool": return dv.getUint8(off) !== 0;
    case "i8": return dv.getInt8(off);
    case "u8": return dv.getUint8(off);
    case "i16": return dv.getInt16(off, true);
    case "u16": return dv.getUint16(off, true);
    case "i32": return dv.getInt32(off, true);
    case "u32": return dv.getUint32(off, true);
    case "i64": return dv.getBigInt64(off, true);
    case "u64": return dv.getBigUint64(off, true);
    case "i64_fast": return Number(dv.getBigInt64(off, true));
    case "u64_fast": return Number(dv.getBigUint64(off, true));
    case "f32": return dv.getFloat32(off, true);
    case "f64": return dv.getFloat64(off, true);
    case "pointer": case "ptr": case "function": return __ptrOut(dv.getBigUint64(off, true));
    case "cstring": { const p = __ptrOut(dv.getBigUint64(off, true)); return p === null ? null : __cstr(p); }
  }
}

function __write(dv, type, off, v) {
  if(type.endsWith("*")) type = "pointer";
  switch(type) {
    case "bool": return dv.setUint8(off, v ? 1 : 0);
    case "i8": return dv.setInt8(off, v);
    case "u8": return dv.setUint8(off, v);
    case "i16": return dv.setInt16(off, v, true);
    case "u16": return dv.setUint16(off, v, true);
    case "i32": return dv.setInt32(off, v, true);
    case "u32": return dv.setUint32(off, v, true);
    case "i64": case "i64_fast": return dv.setBigInt64(off, BigInt(v), true);
    case "u64": case "u64_fast": case "pointer": case "ptr": case "function": return dv.setBigUint64(off, v === null ? 0n : BigInt(v), true);
    case "f32": return dv.setFloat32(off, v, true);
    case "f64": return dv.setFloat64(off, v, true);
  }
  throw new TypeError("cannot write a " + type + " field");
}

function __variable(name, type) {
  const v = { get ptr() { return __sym(name); } };
  if(__sz(type) !== undefined) {
    const dv = () => new DataView(toArrayBuffer(__sym(name), 0, __sz(type)));
    Object.defineProperty(v, "value", { enumerable: true, get: () => __read(dv(), type, 0), set: x => __write(dv(), type, 0, x) });
  }
  return v;
}

function __ret(cls, f) {
  return (...args) => Object.setPrototypeOf(f(...args), cls.prototype);
}

// classes and structs

/* struct curl_slist, 16 bytes (line 2742) */
/**
 * struct curl_slist, 16 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=16] - a byte length, or bytes to copy
 * @property {number|bigint|null} data - char *, offset 0
 * @property {curl_slist|null} next - struct curl_slist *, offset 8
 */
export class curl_slist extends ArrayBuffer {
  constructor(init = 16) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 16) { return __view(curl_slist, p, size, owner); }
  get ptr() { return __ptr(this); }
  get data() { return __ptrOut(__dv(this).getBigUint64(0, true)); }
  set data(v) { __dv(this).setBigUint64(0, __ptrIn(v), true); }
  get next() { const p = __dv(this).getBigUint64(8, true); return p === 0n ? null : curl_slist.at(p); }
  set next(v) { __dv(this).setBigUint64(8, __ptrIn(v), true); }
}
curl_slist.size = 16;
curl_slist.align = 8;
curl_slist.fields = {data:{type:'cstring',offset:0},next:{type:'struct curl_slist *',offset:8}};

/* struct curl_httppost, 112 bytes (line 176) */
/**
 * struct curl_httppost, 112 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=112] - a byte length, or bytes to copy
 * @property {curl_httppost|null} next - struct curl_httppost *, offset 0
 * @property {number|bigint|null} name - char *, offset 8
 * @property {bigint} namelength - long, offset 16
 * @property {number|bigint|null} contents - char *, offset 24
 * @property {bigint} contentslength - long, offset 32
 * @property {number|bigint|null} buffer - char *, offset 40
 * @property {bigint} bufferlength - long, offset 48
 * @property {number|bigint|null} contenttype - char *, offset 56
 * @property {curl_slist|null} contentheader - struct curl_slist *, offset 64
 * @property {curl_httppost|null} more - struct curl_httppost *, offset 72
 * @property {bigint} flags - long, offset 80
 * @property {number|bigint|null} showfilename - char *, offset 88
 * @property {number|bigint|null} userp - void *, offset 96
 * @property {bigint} contentlen - curl_off_t, offset 104
 */
export class curl_httppost extends ArrayBuffer {
  constructor(init = 112) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 112) { return __view(curl_httppost, p, size, owner); }
  get ptr() { return __ptr(this); }
  get next() { const p = __dv(this).getBigUint64(0, true); return p === 0n ? null : curl_httppost.at(p); }
  set next(v) { __dv(this).setBigUint64(0, __ptrIn(v), true); }
  get name() { return __ptrOut(__dv(this).getBigUint64(8, true)); }
  set name(v) { __dv(this).setBigUint64(8, __ptrIn(v), true); }
  get namelength() { return __dv(this).getBigInt64(16, true); }
  set namelength(v) { __dv(this).setBigInt64(16, BigInt(v), true); }
  get contents() { return __ptrOut(__dv(this).getBigUint64(24, true)); }
  set contents(v) { __dv(this).setBigUint64(24, __ptrIn(v), true); }
  get contentslength() { return __dv(this).getBigInt64(32, true); }
  set contentslength(v) { __dv(this).setBigInt64(32, BigInt(v), true); }
  get buffer() { return __ptrOut(__dv(this).getBigUint64(40, true)); }
  set buffer(v) { __dv(this).setBigUint64(40, __ptrIn(v), true); }
  get bufferlength() { return __dv(this).getBigInt64(48, true); }
  set bufferlength(v) { __dv(this).setBigInt64(48, BigInt(v), true); }
  get contenttype() { return __ptrOut(__dv(this).getBigUint64(56, true)); }
  set contenttype(v) { __dv(this).setBigUint64(56, __ptrIn(v), true); }
  get contentheader() { const p = __dv(this).getBigUint64(64, true); return p === 0n ? null : curl_slist.at(p); }
  set contentheader(v) { __dv(this).setBigUint64(64, __ptrIn(v), true); }
  get more() { const p = __dv(this).getBigUint64(72, true); return p === 0n ? null : curl_httppost.at(p); }
  set more(v) { __dv(this).setBigUint64(72, __ptrIn(v), true); }
  get flags() { return __dv(this).getBigInt64(80, true); }
  set flags(v) { __dv(this).setBigInt64(80, BigInt(v), true); }
  get showfilename() { return __ptrOut(__dv(this).getBigUint64(88, true)); }
  set showfilename(v) { __dv(this).setBigUint64(88, __ptrIn(v), true); }
  get userp() { return __ptrOut(__dv(this).getBigUint64(96, true)); }
  set userp(v) { __dv(this).setBigUint64(96, __ptrIn(v), true); }
  get contentlen() { return __dv(this).getBigInt64(104, true); }
  set contentlen(v) { __dv(this).setBigInt64(104, BigInt(v), true); }
}
curl_httppost.size = 112;
curl_httppost.align = 8;
curl_httppost.fields = {next:{type:'struct curl_httppost *',offset:0},name:{type:'cstring',offset:8},namelength:{type:'i64',offset:16},contents:{type:'cstring',offset:24},contentslength:{type:'i64',offset:32},buffer:{type:'cstring',offset:40},bufferlength:{type:'i64',offset:48},contenttype:{type:'cstring',offset:56},contentheader:{type:'struct curl_slist *',offset:64},more:{type:'struct curl_httppost *',offset:72},flags:{type:'i64',offset:80},showfilename:{type:'cstring',offset:88},userp:{type:'void *',offset:96},contentlen:{type:'i64',offset:104}};

/* struct curl_fileinfo, 128 bytes (line 305) */
/**
 * struct curl_fileinfo, 128 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=128] - a byte length, or bytes to copy
 * @property {number|bigint|null} filename - char *, offset 0
 * @property {number} filetype - curlfiletype, offset 8
 * @property {bigint} time - time_t, offset 16
 * @property {number} perm - unsigned int, offset 24
 * @property {number} uid - int, offset 28
 * @property {number} gid - int, offset 32
 * @property {bigint} size - curl_off_t, offset 40
 * @property {bigint} hardlinks - long, offset 48
 * @property {Uint8Array} strings - struct (unnamed struct at /usr/include/x86_64-linux-gnu/curl/curl.h:315:3), offset 56
 * @property {number} flags - unsigned int, offset 96
 * @property {number|bigint|null} b_data - char *, offset 104
 * @property {bigint} b_size - size_t, offset 112
 * @property {bigint} b_used - size_t, offset 120
 */
export class curl_fileinfo extends ArrayBuffer {
  constructor(init = 128) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 128) { return __view(curl_fileinfo, p, size, owner); }
  get ptr() { return __ptr(this); }
  get filename() { return __ptrOut(__dv(this).getBigUint64(0, true)); }
  set filename(v) { __dv(this).setBigUint64(0, __ptrIn(v), true); }
  get filetype() { return __dv(this).getInt32(8, true); }
  set filetype(v) { __dv(this).setInt32(8, v, true); }
  get time() { return __dv(this).getBigInt64(16, true); }
  set time(v) { __dv(this).setBigInt64(16, BigInt(v), true); }
  get perm() { return __dv(this).getUint32(24, true); }
  set perm(v) { __dv(this).setUint32(24, v, true); }
  get uid() { return __dv(this).getInt32(28, true); }
  set uid(v) { __dv(this).setInt32(28, v, true); }
  get gid() { return __dv(this).getInt32(32, true); }
  set gid(v) { __dv(this).setInt32(32, v, true); }
  get size() { return __dv(this).getBigInt64(40, true); }
  set size(v) { __dv(this).setBigInt64(40, BigInt(v), true); }
  get hardlinks() { return __dv(this).getBigInt64(48, true); }
  set hardlinks(v) { __dv(this).setBigInt64(48, BigInt(v), true); }
  get strings() { return new Uint8Array(this, 56, 40); }
  set strings(v) { new Uint8Array(this, 56, 40).set(__bytes(v)); }
  get flags() { return __dv(this).getUint32(96, true); }
  set flags(v) { __dv(this).setUint32(96, v, true); }
  get b_data() { return __ptrOut(__dv(this).getBigUint64(104, true)); }
  set b_data(v) { __dv(this).setBigUint64(104, __ptrIn(v), true); }
  get b_size() { return __dv(this).getBigUint64(112, true); }
  set b_size(v) { __dv(this).setBigUint64(112, BigInt(v), true); }
  get b_used() { return __dv(this).getBigUint64(120, true); }
  set b_used(v) { __dv(this).setBigUint64(120, BigInt(v), true); }
}
curl_fileinfo.size = 128;
curl_fileinfo.align = 8;
curl_fileinfo.fields = {filename:{type:'cstring',offset:0},filetype:{type:'i32',offset:8},time:{type:'i64',offset:16},perm:{type:'u32',offset:24},uid:{type:'i32',offset:28},gid:{type:'i32',offset:32},size:{type:'i64',offset:40},hardlinks:{type:'i64',offset:48},strings:{type:'struct (unnamed struct at /usr/include/x86_64-linux-gnu/curl/curl.h:315:3)',offset:56},flags:{type:'u32',offset:96},b_data:{type:'cstring',offset:104},b_size:{type:'u64',offset:112},b_used:{type:'u64',offset:120}};

/* struct curl_sockaddr, 32 bytes (line 416) */
/**
 * struct curl_sockaddr, 32 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=32] - a byte length, or bytes to copy
 * @property {number} family - int, offset 0
 * @property {number} socktype - int, offset 4
 * @property {number} protocol - int, offset 8
 * @property {number} addrlen - unsigned int, offset 12
 * @property {Uint8Array} addr - struct sockaddr, offset 16
 */
export class curl_sockaddr extends ArrayBuffer {
  constructor(init = 32) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 32) { return __view(curl_sockaddr, p, size, owner); }
  get ptr() { return __ptr(this); }
  get family() { return __dv(this).getInt32(0, true); }
  set family(v) { __dv(this).setInt32(0, v, true); }
  get socktype() { return __dv(this).getInt32(4, true); }
  set socktype(v) { __dv(this).setInt32(4, v, true); }
  get protocol() { return __dv(this).getInt32(8, true); }
  set protocol(v) { __dv(this).setInt32(8, v, true); }
  get addrlen() { return __dv(this).getUint32(12, true); }
  set addrlen(v) { __dv(this).setUint32(12, v, true); }
  get addr() { return new Uint8Array(this, 16, 16); }
  set addr(v) { new Uint8Array(this, 16, 16).set(__bytes(v)); }
}
curl_sockaddr.size = 32;
curl_sockaddr.align = 4;
curl_sockaddr.fields = {family:{type:'i32',offset:0},socktype:{type:'i32',offset:4},protocol:{type:'i32',offset:8},addrlen:{type:'u32',offset:12},addr:{type:'struct sockaddr',offset:16}};

/* struct curl_khkey, 24 bytes (line 845) */
/**
 * struct curl_khkey, 24 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=24] - a byte length, or bytes to copy
 * @property {number|bigint|null} key - const char *, offset 0
 * @property {bigint} len - size_t, offset 8
 * @property {number} keytype - enum curl_khtype, offset 16
 */
export class curl_khkey extends ArrayBuffer {
  constructor(init = 24) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 24) { return __view(curl_khkey, p, size, owner); }
  get ptr() { return __ptr(this); }
  get key() { return __ptrOut(__dv(this).getBigUint64(0, true)); }
  set key(v) { __dv(this).setBigUint64(0, __ptrIn(v), true); }
  get len() { return __dv(this).getBigUint64(8, true); }
  set len(v) { __dv(this).setBigUint64(8, BigInt(v), true); }
  get keytype() { return __dv(this).getInt32(16, true); }
  set keytype(v) { __dv(this).setInt32(16, v, true); }
}
curl_khkey.size = 24;
curl_khkey.align = 8;
curl_khkey.fields = {key:{type:'cstring',offset:0},len:{type:'u64',offset:8},keytype:{type:'i32',offset:16}};

/* struct curl_hstsentry, 40 bytes (line 999) */
/**
 * struct curl_hstsentry, 40 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=40] - a byte length, or bytes to copy
 * @property {number|bigint|null} name - char *, offset 0
 * @property {bigint} namelen - size_t, offset 8
 * @property {number} includeSubDomains - unsigned int, 1 bits, offset 16
 * @property {Int8Array} expire - char[18], offset 17
 */
export class curl_hstsentry extends ArrayBuffer {
  constructor(init = 40) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 40) { return __view(curl_hstsentry, p, size, owner); }
  get ptr() { return __ptr(this); }
  get name() { return __ptrOut(__dv(this).getBigUint64(0, true)); }
  set name(v) { __dv(this).setBigUint64(0, __ptrIn(v), true); }
  get namelen() { return __dv(this).getBigUint64(8, true); }
  set namelen(v) { __dv(this).setBigUint64(8, BigInt(v), true); }
  get includeSubDomains() { return (__dv(this).getUint32(16, true) >>> 0) & 0x1; }
  set includeSubDomains(v) { __dv(this).setUint32(16, ((__dv(this).getUint32(16, true) & ~0x1) | ((v << 0) & 0x1)) >>> 0, true); }
  get expire() { return new Int8Array(this, 17, 18); }
  set expire(v) { new Int8Array(this, 17, 18).set(v); }
}
curl_hstsentry.size = 40;
curl_hstsentry.align = 8;
curl_hstsentry.fields = {name:{type:'cstring',offset:0},namelen:{type:'u64',offset:8},includeSubDomains:{type:'u32',bits:1,bitOffset:128},expire:{type:'char[18]',offset:17}};

/* struct curl_index, 16 bytes (line 1006) */
/**
 * struct curl_index, 16 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=16] - a byte length, or bytes to copy
 * @property {bigint} index - size_t, offset 0
 * @property {bigint} total - size_t, offset 8
 */
export class curl_index extends ArrayBuffer {
  constructor(init = 16) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 16) { return __view(curl_index, p, size, owner); }
  get ptr() { return __ptr(this); }
  get index() { return __dv(this).getBigUint64(0, true); }
  set index(v) { __dv(this).setBigUint64(0, BigInt(v), true); }
  get total() { return __dv(this).getBigUint64(8, true); }
  set total(v) { __dv(this).setBigUint64(8, BigInt(v), true); }
}
curl_index.size = 16;
curl_index.align = 8;
curl_index.fields = {index:{type:'u64',offset:0},total:{type:'u64',offset:8}};

/* struct curl_forms, 16 bytes (line 2532) */
/**
 * struct curl_forms, 16 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=16] - a byte length, or bytes to copy
 * @property {number} option - CURLformoption, offset 0
 * @property {number|bigint|null} value - const char *, offset 8
 */
export class curl_forms extends ArrayBuffer {
  constructor(init = 16) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 16) { return __view(curl_forms, p, size, owner); }
  get ptr() { return __ptr(this); }
  get option() { return __dv(this).getInt32(0, true); }
  set option(v) { __dv(this).setInt32(0, v, true); }
  get value() { return __ptrOut(__dv(this).getBigUint64(8, true)); }
  set value(v) { __dv(this).setBigUint64(8, __ptrIn(v), true); }
}
curl_forms.size = 16;
curl_forms.align = 8;
curl_forms.fields = {option:{type:'i32',offset:0},value:{type:'cstring',offset:8}};

/* struct curl_ssl_backend, 16 bytes (line 2773) */
/**
 * struct curl_ssl_backend, 16 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=16] - a byte length, or bytes to copy
 * @property {number} id - curl_sslbackend, offset 0
 * @property {number|bigint|null} name - const char *, offset 8
 */
export class curl_ssl_backend extends ArrayBuffer {
  constructor(init = 16) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 16) { return __view(curl_ssl_backend, p, size, owner); }
  get ptr() { return __ptr(this); }
  get id() { return __dv(this).getInt32(0, true); }
  set id(v) { __dv(this).setInt32(0, v, true); }
  get name() { return __ptrOut(__dv(this).getBigUint64(8, true)); }
  set name(v) { __dv(this).setBigUint64(8, __ptrIn(v), true); }
}
curl_ssl_backend.size = 16;
curl_ssl_backend.align = 8;
curl_ssl_backend.fields = {id:{type:'i32',offset:0},name:{type:'cstring',offset:8}};

/* struct curl_certinfo, 16 bytes (line 2822) */
/**
 * struct curl_certinfo, 16 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=16] - a byte length, or bytes to copy
 * @property {number} num_of_certs - int, offset 0
 * @property {number|bigint|null} certinfo - struct curl_slist **, offset 8
 */
export class curl_certinfo extends ArrayBuffer {
  constructor(init = 16) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 16) { return __view(curl_certinfo, p, size, owner); }
  get ptr() { return __ptr(this); }
  get num_of_certs() { return __dv(this).getInt32(0, true); }
  set num_of_certs(v) { __dv(this).setInt32(0, v, true); }
  get certinfo() { return __ptrOut(__dv(this).getBigUint64(8, true)); }
  set certinfo(v) { __dv(this).setBigUint64(8, __ptrIn(v), true); }
}
curl_certinfo.size = 16;
curl_certinfo.align = 8;
curl_certinfo.fields = {num_of_certs:{type:'i32',offset:0},certinfo:{type:'struct curl_slist **',offset:8}};

/* struct curl_tlssessioninfo, 16 bytes (line 2833) */
/**
 * struct curl_tlssessioninfo, 16 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=16] - a byte length, or bytes to copy
 * @property {number} backend - curl_sslbackend, offset 0
 * @property {number|bigint|null} internals - void *, offset 8
 */
export class curl_tlssessioninfo extends ArrayBuffer {
  constructor(init = 16) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 16) { return __view(curl_tlssessioninfo, p, size, owner); }
  get ptr() { return __ptr(this); }
  get backend() { return __dv(this).getInt32(0, true); }
  set backend(v) { __dv(this).setInt32(0, v, true); }
  get internals() { return __ptrOut(__dv(this).getBigUint64(8, true)); }
  set internals(v) { __dv(this).setBigUint64(8, __ptrIn(v), true); }
}
curl_tlssessioninfo.size = 16;
curl_tlssessioninfo.align = 8;
curl_tlssessioninfo.fields = {backend:{type:'i32',offset:0},internals:{type:'void *',offset:8}};

/* struct curl_version_info_data, 208 bytes (line 3054) */
/**
 * struct curl_version_info_data, 208 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=208] - a byte length, or bytes to copy
 * @property {number} age - CURLversion, offset 0
 * @property {number|bigint|null} version - const char *, offset 8
 * @property {number} version_num - unsigned int, offset 16
 * @property {number|bigint|null} host - const char *, offset 24
 * @property {number} features - int, offset 32
 * @property {number|bigint|null} ssl_version - const char *, offset 40
 * @property {bigint} ssl_version_num - long, offset 48
 * @property {number|bigint|null} libz_version - const char *, offset 56
 * @property {number|bigint|null} protocols - const char *const *, offset 64
 * @property {number|bigint|null} ares - const char *, offset 72
 * @property {number} ares_num - int, offset 80
 * @property {number|bigint|null} libidn - const char *, offset 88
 * @property {number} iconv_ver_num - int, offset 96
 * @property {number|bigint|null} libssh_version - const char *, offset 104
 * @property {number} brotli_ver_num - unsigned int, offset 112
 * @property {number|bigint|null} brotli_version - const char *, offset 120
 * @property {number} nghttp2_ver_num - unsigned int, offset 128
 * @property {number|bigint|null} nghttp2_version - const char *, offset 136
 * @property {number|bigint|null} quic_version - const char *, offset 144
 * @property {number|bigint|null} cainfo - const char *, offset 152
 * @property {number|bigint|null} capath - const char *, offset 160
 * @property {number} zstd_ver_num - unsigned int, offset 168
 * @property {number|bigint|null} zstd_version - const char *, offset 176
 * @property {number|bigint|null} hyper_version - const char *, offset 184
 * @property {number|bigint|null} gsasl_version - const char *, offset 192
 * @property {number|bigint|null} feature_names - const char *const *, offset 200
 */
export class curl_version_info_data extends ArrayBuffer {
  constructor(init = 208) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 208) { return __view(curl_version_info_data, p, size, owner); }
  get ptr() { return __ptr(this); }
  get age() { return __dv(this).getInt32(0, true); }
  set age(v) { __dv(this).setInt32(0, v, true); }
  get version() { return __ptrOut(__dv(this).getBigUint64(8, true)); }
  set version(v) { __dv(this).setBigUint64(8, __ptrIn(v), true); }
  get version_num() { return __dv(this).getUint32(16, true); }
  set version_num(v) { __dv(this).setUint32(16, v, true); }
  get host() { return __ptrOut(__dv(this).getBigUint64(24, true)); }
  set host(v) { __dv(this).setBigUint64(24, __ptrIn(v), true); }
  get features() { return __dv(this).getInt32(32, true); }
  set features(v) { __dv(this).setInt32(32, v, true); }
  get ssl_version() { return __ptrOut(__dv(this).getBigUint64(40, true)); }
  set ssl_version(v) { __dv(this).setBigUint64(40, __ptrIn(v), true); }
  get ssl_version_num() { return __dv(this).getBigInt64(48, true); }
  set ssl_version_num(v) { __dv(this).setBigInt64(48, BigInt(v), true); }
  get libz_version() { return __ptrOut(__dv(this).getBigUint64(56, true)); }
  set libz_version(v) { __dv(this).setBigUint64(56, __ptrIn(v), true); }
  get protocols() { return __ptrOut(__dv(this).getBigUint64(64, true)); }
  set protocols(v) { __dv(this).setBigUint64(64, __ptrIn(v), true); }
  get ares() { return __ptrOut(__dv(this).getBigUint64(72, true)); }
  set ares(v) { __dv(this).setBigUint64(72, __ptrIn(v), true); }
  get ares_num() { return __dv(this).getInt32(80, true); }
  set ares_num(v) { __dv(this).setInt32(80, v, true); }
  get libidn() { return __ptrOut(__dv(this).getBigUint64(88, true)); }
  set libidn(v) { __dv(this).setBigUint64(88, __ptrIn(v), true); }
  get iconv_ver_num() { return __dv(this).getInt32(96, true); }
  set iconv_ver_num(v) { __dv(this).setInt32(96, v, true); }
  get libssh_version() { return __ptrOut(__dv(this).getBigUint64(104, true)); }
  set libssh_version(v) { __dv(this).setBigUint64(104, __ptrIn(v), true); }
  get brotli_ver_num() { return __dv(this).getUint32(112, true); }
  set brotli_ver_num(v) { __dv(this).setUint32(112, v, true); }
  get brotli_version() { return __ptrOut(__dv(this).getBigUint64(120, true)); }
  set brotli_version(v) { __dv(this).setBigUint64(120, __ptrIn(v), true); }
  get nghttp2_ver_num() { return __dv(this).getUint32(128, true); }
  set nghttp2_ver_num(v) { __dv(this).setUint32(128, v, true); }
  get nghttp2_version() { return __ptrOut(__dv(this).getBigUint64(136, true)); }
  set nghttp2_version(v) { __dv(this).setBigUint64(136, __ptrIn(v), true); }
  get quic_version() { return __ptrOut(__dv(this).getBigUint64(144, true)); }
  set quic_version(v) { __dv(this).setBigUint64(144, __ptrIn(v), true); }
  get cainfo() { return __ptrOut(__dv(this).getBigUint64(152, true)); }
  set cainfo(v) { __dv(this).setBigUint64(152, __ptrIn(v), true); }
  get capath() { return __ptrOut(__dv(this).getBigUint64(160, true)); }
  set capath(v) { __dv(this).setBigUint64(160, __ptrIn(v), true); }
  get zstd_ver_num() { return __dv(this).getUint32(168, true); }
  set zstd_ver_num(v) { __dv(this).setUint32(168, v, true); }
  get zstd_version() { return __ptrOut(__dv(this).getBigUint64(176, true)); }
  set zstd_version(v) { __dv(this).setBigUint64(176, __ptrIn(v), true); }
  get hyper_version() { return __ptrOut(__dv(this).getBigUint64(184, true)); }
  set hyper_version(v) { __dv(this).setBigUint64(184, __ptrIn(v), true); }
  get gsasl_version() { return __ptrOut(__dv(this).getBigUint64(192, true)); }
  set gsasl_version(v) { __dv(this).setBigUint64(192, __ptrIn(v), true); }
  get feature_names() { return __ptrOut(__dv(this).getBigUint64(200, true)); }
  set feature_names(v) { __dv(this).setBigUint64(200, __ptrIn(v), true); }
}
curl_version_info_data.size = 208;
curl_version_info_data.align = 8;
curl_version_info_data.fields = {age:{type:'i32',offset:0},version:{type:'cstring',offset:8},version_num:{type:'u32',offset:16},host:{type:'cstring',offset:24},features:{type:'i32',offset:32},ssl_version:{type:'cstring',offset:40},ssl_version_num:{type:'i64',offset:48},libz_version:{type:'cstring',offset:56},protocols:{type:'char **',offset:64},ares:{type:'cstring',offset:72},ares_num:{type:'i32',offset:80},libidn:{type:'cstring',offset:88},iconv_ver_num:{type:'i32',offset:96},libssh_version:{type:'cstring',offset:104},brotli_ver_num:{type:'u32',offset:112},brotli_version:{type:'cstring',offset:120},nghttp2_ver_num:{type:'u32',offset:128},nghttp2_version:{type:'cstring',offset:136},quic_version:{type:'cstring',offset:144},cainfo:{type:'cstring',offset:152},capath:{type:'cstring',offset:160},zstd_ver_num:{type:'u32',offset:168},zstd_version:{type:'cstring',offset:176},hyper_version:{type:'cstring',offset:184},gsasl_version:{type:'cstring',offset:192},feature_names:{type:'char **',offset:200}};

/* struct curl_blob, 24 bytes (line 34) */
/**
 * struct curl_blob, 24 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=24] - a byte length, or bytes to copy
 * @property {number|bigint|null} data - void *, offset 0
 * @property {bigint} len - size_t, offset 8
 * @property {number} flags - unsigned int, offset 16
 */
export class curl_blob extends ArrayBuffer {
  constructor(init = 24) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 24) { return __view(curl_blob, p, size, owner); }
  get ptr() { return __ptr(this); }
  get data() { return __ptrOut(__dv(this).getBigUint64(0, true)); }
  set data(v) { __dv(this).setBigUint64(0, __ptrIn(v), true); }
  get len() { return __dv(this).getBigUint64(8, true); }
  set len(v) { __dv(this).setBigUint64(8, BigInt(v), true); }
  get flags() { return __dv(this).getUint32(16, true); }
  set flags(v) { __dv(this).setUint32(16, v, true); }
}
curl_blob.size = 24;
curl_blob.align = 8;
curl_blob.fields = {data:{type:'void *',offset:0},len:{type:'u64',offset:8},flags:{type:'u32',offset:16}};

/* struct CURLMsg, 24 bytes (line 101) */
/**
 * struct CURLMsg, 24 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=24] - a byte length, or bytes to copy
 * @property {number} msg - CURLMSG, offset 0
 * @property {number|bigint|null} easy_handle - CURL *, offset 8
 * @property {Uint8Array} data - union (unnamed union at /usr/include/x86_64-linux-gnu/curl/multi.h:104:3), offset 16
 */
export class CURLMsg extends ArrayBuffer {
  constructor(init = 24) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 24) { return __view(CURLMsg, p, size, owner); }
  get ptr() { return __ptr(this); }
  get msg() { return __dv(this).getInt32(0, true); }
  set msg(v) { __dv(this).setInt32(0, v, true); }
  get easy_handle() { return __ptrOut(__dv(this).getBigUint64(8, true)); }
  set easy_handle(v) { __dv(this).setBigUint64(8, __ptrIn(v), true); }
  get data() { return new Uint8Array(this, 16, 8); }
  set data(v) { new Uint8Array(this, 16, 8).set(__bytes(v)); }
}
CURLMsg.size = 24;
CURLMsg.align = 8;
CURLMsg.fields = {msg:{type:'i32',offset:0},easy_handle:{type:'CURL *',offset:8},data:{type:'union (unnamed union at /usr/include/x86_64-linux-gnu/curl/multi.h:104:3)',offset:16}};

/* struct curl_waitfd, 8 bytes (line 118) */
/**
 * struct curl_waitfd, 8 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=8] - a byte length, or bytes to copy
 * @property {number} fd - curl_socket_t, offset 0
 * @property {number} events - short, offset 4
 * @property {number} revents - short, offset 6
 */
export class curl_waitfd extends ArrayBuffer {
  constructor(init = 8) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 8) { return __view(curl_waitfd, p, size, owner); }
  get ptr() { return __ptr(this); }
  get fd() { return __dv(this).getInt32(0, true); }
  set fd(v) { __dv(this).setInt32(0, v, true); }
  get events() { return __dv(this).getInt16(4, true); }
  set events(v) { __dv(this).setInt16(4, v, true); }
  get revents() { return __dv(this).getInt16(6, true); }
  set revents(v) { __dv(this).setInt16(6, v, true); }
}
curl_waitfd.size = 8;
curl_waitfd.align = 4;
curl_waitfd.fields = {fd:{type:'i32',offset:0},events:{type:'i16',offset:4},revents:{type:'i16',offset:6}};

/* struct curl_easyoption, 24 bytes (line 51) */
/**
 * struct curl_easyoption, 24 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=24] - a byte length, or bytes to copy
 * @property {number|bigint|null} name - const char *, offset 0
 * @property {number} id - CURLoption, offset 8
 * @property {number} type - curl_easytype, offset 12
 * @property {number} flags - unsigned int, offset 16
 */
export class curl_easyoption extends ArrayBuffer {
  constructor(init = 24) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 24) { return __view(curl_easyoption, p, size, owner); }
  get ptr() { return __ptr(this); }
  get name() { return __ptrOut(__dv(this).getBigUint64(0, true)); }
  set name(v) { __dv(this).setBigUint64(0, __ptrIn(v), true); }
  get id() { return __dv(this).getInt32(8, true); }
  set id(v) { __dv(this).setInt32(8, v, true); }
  get type() { return __dv(this).getInt32(12, true); }
  set type(v) { __dv(this).setInt32(12, v, true); }
  get flags() { return __dv(this).getUint32(16, true); }
  set flags(v) { __dv(this).setUint32(16, v, true); }
}
curl_easyoption.size = 24;
curl_easyoption.align = 8;
curl_easyoption.fields = {name:{type:'cstring',offset:0},id:{type:'i32',offset:8},type:{type:'i32',offset:12},flags:{type:'u32',offset:16}};

/* struct curl_header, 48 bytes (line 31) */
/**
 * struct curl_header, 48 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=48] - a byte length, or bytes to copy
 * @property {number|bigint|null} name - char *, offset 0
 * @property {number|bigint|null} value - char *, offset 8
 * @property {bigint} amount - size_t, offset 16
 * @property {bigint} index - size_t, offset 24
 * @property {number} origin - unsigned int, offset 32
 * @property {number|bigint|null} anchor - void *, offset 40
 */
export class curl_header extends ArrayBuffer {
  constructor(init = 48) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 48) { return __view(curl_header, p, size, owner); }
  get ptr() { return __ptr(this); }
  get name() { return __ptrOut(__dv(this).getBigUint64(0, true)); }
  set name(v) { __dv(this).setBigUint64(0, __ptrIn(v), true); }
  get value() { return __ptrOut(__dv(this).getBigUint64(8, true)); }
  set value(v) { __dv(this).setBigUint64(8, __ptrIn(v), true); }
  get amount() { return __dv(this).getBigUint64(16, true); }
  set amount(v) { __dv(this).setBigUint64(16, BigInt(v), true); }
  get index() { return __dv(this).getBigUint64(24, true); }
  set index(v) { __dv(this).setBigUint64(24, BigInt(v), true); }
  get origin() { return __dv(this).getUint32(32, true); }
  set origin(v) { __dv(this).setUint32(32, v, true); }
  get anchor() { return __ptrOut(__dv(this).getBigUint64(40, true)); }
  set anchor(v) { __dv(this).setBigUint64(40, __ptrIn(v), true); }
}
curl_header.size = 48;
curl_header.align = 8;
curl_header.fields = {name:{type:'cstring',offset:0},value:{type:'cstring',offset:8},amount:{type:'u64',offset:16},index:{type:'u64',offset:24},origin:{type:'u32',offset:32},anchor:{type:'void *',offset:40}};

/* struct curl_ws_frame, 32 bytes (line 31) */
/**
 * struct curl_ws_frame, 32 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=32] - a byte length, or bytes to copy
 * @property {number} age - int, offset 0
 * @property {number} flags - int, offset 4
 * @property {bigint} offset - curl_off_t, offset 8
 * @property {bigint} bytesleft - curl_off_t, offset 16
 * @property {bigint} len - size_t, offset 24
 */
export class curl_ws_frame extends ArrayBuffer {
  constructor(init = 32) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 32) { return __view(curl_ws_frame, p, size, owner); }
  get ptr() { return __ptr(this); }
  get age() { return __dv(this).getInt32(0, true); }
  set age(v) { __dv(this).setInt32(0, v, true); }
  get flags() { return __dv(this).getInt32(4, true); }
  set flags(v) { __dv(this).setInt32(4, v, true); }
  get offset() { return __dv(this).getBigInt64(8, true); }
  set offset(v) { __dv(this).setBigInt64(8, BigInt(v), true); }
  get bytesleft() { return __dv(this).getBigInt64(16, true); }
  set bytesleft(v) { __dv(this).setBigInt64(16, BigInt(v), true); }
  get len() { return __dv(this).getBigUint64(24, true); }
  set len(v) { __dv(this).setBigUint64(24, BigInt(v), true); }
}
curl_ws_frame.size = 32;
curl_ws_frame.align = 8;
curl_ws_frame.fields = {age:{type:'i32',offset:0},flags:{type:'i32',offset:4},offset:{type:'i64',offset:8},bytesleft:{type:'i64',offset:16},len:{type:'u64',offset:24}};


/**
 * curl_strequal
 * @param {string|null} s1 - cstring
 * @param {string|null} s2 - cstring
 * @returns {number} - i32
 */
export const curl_strequal = CFunction({ptr:__sym('curl_strequal'),args:['cstring','cstring'],returns:'i32'});
/**
 * curl_strnequal
 * @param {string|null} s1 - cstring
 * @param {string|null} s2 - cstring
 * @param {bigint|number} n - u64
 * @returns {number} - i32
 */
export const curl_strnequal = CFunction({ptr:__sym('curl_strnequal'),args:['cstring','cstring','u64'],returns:'i32'});
/**
 * curl_mime_init
 * @param {object|number|bigint|null} easy - CURL *
 * @returns {number|bigint|null} - curl_mime *
 */
export const curl_mime_init = CFunction({ptr:__sym('curl_mime_init'),args:['CURL *'],returns:'curl_mime *'});
/**
 * curl_mime_free
 * @param {object|number|bigint|null} mime - curl_mime *
 * @returns {void}
 */
export const curl_mime_free = CFunction({ptr:__sym('curl_mime_free'),args:['curl_mime *'],returns:'void'});
/**
 * curl_mime_addpart
 * @param {object|number|bigint|null} mime - curl_mime *
 * @returns {number|bigint|null} - curl_mimepart *
 */
export const curl_mime_addpart = CFunction({ptr:__sym('curl_mime_addpart'),args:['curl_mime *'],returns:'curl_mimepart *'});
/**
 * curl_mime_name
 * @param {object|number|bigint|null} part - curl_mimepart *
 * @param {string|null} name - cstring
 * @returns {number} - i32
 */
export const curl_mime_name = CFunction({ptr:__sym('curl_mime_name'),args:['curl_mimepart *','cstring'],returns:'i32'});
/**
 * curl_mime_filename
 * @param {object|number|bigint|null} part - curl_mimepart *
 * @param {string|null} filename - cstring
 * @returns {number} - i32
 */
export const curl_mime_filename = CFunction({ptr:__sym('curl_mime_filename'),args:['curl_mimepart *','cstring'],returns:'i32'});
/**
 * curl_mime_type
 * @param {object|number|bigint|null} part - curl_mimepart *
 * @param {string|null} mimetype - cstring
 * @returns {number} - i32
 */
export const curl_mime_type = CFunction({ptr:__sym('curl_mime_type'),args:['curl_mimepart *','cstring'],returns:'i32'});
/**
 * curl_mime_encoder
 * @param {object|number|bigint|null} part - curl_mimepart *
 * @param {string|null} encoding - cstring
 * @returns {number} - i32
 */
export const curl_mime_encoder = CFunction({ptr:__sym('curl_mime_encoder'),args:['curl_mimepart *','cstring'],returns:'i32'});
/**
 * curl_mime_data
 * @param {object|number|bigint|null} part - curl_mimepart *
 * @param {string|null} data - cstring
 * @param {bigint|number} datasize - u64
 * @returns {number} - i32
 */
export const curl_mime_data = CFunction({ptr:__sym('curl_mime_data'),args:['curl_mimepart *','cstring','u64'],returns:'i32'});
/**
 * curl_mime_filedata
 * @param {object|number|bigint|null} part - curl_mimepart *
 * @param {string|null} filename - cstring
 * @returns {number} - i32
 */
export const curl_mime_filedata = CFunction({ptr:__sym('curl_mime_filedata'),args:['curl_mimepart *','cstring'],returns:'i32'});
/**
 * curl_mime_data_cb
 * @param {object|number|bigint|null} part - curl_mimepart *
 * @param {bigint|number} datasize - i64
 * @param {object|number|bigint|null} readfunc - function
 * @param {object|number|bigint|null} seekfunc - function
 * @param {object|number|bigint|null} freefunc - function
 * @param {object|number|bigint|null} arg - void *
 * @returns {number} - i32
 */
export const curl_mime_data_cb = CFunction({ptr:__sym('curl_mime_data_cb'),args:['curl_mimepart *','i64','function','function','function','void *'],returns:'i32'});
/**
 * curl_mime_subparts
 * @param {object|number|bigint|null} part - curl_mimepart *
 * @param {object|number|bigint|null} subparts - curl_mime *
 * @returns {number} - i32
 */
export const curl_mime_subparts = CFunction({ptr:__sym('curl_mime_subparts'),args:['curl_mimepart *','curl_mime *'],returns:'i32'});
/**
 * curl_mime_headers
 * @param {object|number|bigint|null} part - curl_mimepart *
 * @param {object|number|bigint|null} headers - struct curl_slist *
 * @param {number} take_ownership - i32
 * @returns {number} - i32
 */
export const curl_mime_headers = CFunction({ptr:__sym('curl_mime_headers'),args:['curl_mimepart *','struct curl_slist *','i32'],returns:'i32'});
/**
 * curl_formget
 * @param {object|number|bigint|null} form - struct curl_httppost *
 * @param {object|number|bigint|null} arg - void *
 * @param {object|number|bigint|null} append - function
 * @returns {number} - i32
 */
export const curl_formget = CFunction({ptr:__sym('curl_formget'),args:['struct curl_httppost *','void *','function'],returns:'i32'});
/**
 * curl_formfree
 * @param {object|number|bigint|null} form - struct curl_httppost *
 * @returns {void}
 */
export const curl_formfree = CFunction({ptr:__sym('curl_formfree'),args:['struct curl_httppost *'],returns:'void'});
/**
 * curl_getenv
 * @param {string|null} variable - cstring
 * @returns {string} - cstring
 */
export const curl_getenv = CFunction({ptr:__sym('curl_getenv'),args:['cstring'],returns:'cstring'});
/**
 * curl_version
 * @returns {string} - cstring
 */
export const curl_version = CFunction({ptr:__sym('curl_version'),args:[],returns:'cstring'});
/**
 * curl_easy_escape
 * @param {object|number|bigint|null} handle - CURL *
 * @param {string|null} string - cstring
 * @param {number} length - i32
 * @returns {string} - cstring
 */
export const curl_easy_escape = CFunction({ptr:__sym('curl_easy_escape'),args:['CURL *','cstring','i32'],returns:'cstring'});
/**
 * curl_escape
 * @param {string|null} string - cstring
 * @param {number} length - i32
 * @returns {string} - cstring
 */
export const curl_escape = CFunction({ptr:__sym('curl_escape'),args:['cstring','i32'],returns:'cstring'});
/**
 * curl_easy_unescape
 * @param {object|number|bigint|null} handle - CURL *
 * @param {string|null} string - cstring
 * @param {number} length - i32
 * @param {object|number|bigint|null} outlength - int *
 * @returns {string} - cstring
 */
export const curl_easy_unescape = CFunction({ptr:__sym('curl_easy_unescape'),args:['CURL *','cstring','i32','int *'],returns:'cstring'});
/**
 * curl_unescape
 * @param {string|null} string - cstring
 * @param {number} length - i32
 * @returns {string} - cstring
 */
export const curl_unescape = CFunction({ptr:__sym('curl_unescape'),args:['cstring','i32'],returns:'cstring'});
/**
 * curl_free
 * @param {object|number|bigint|null} p - void *
 * @returns {void}
 */
export const curl_free = CFunction({ptr:__sym('curl_free'),args:['void *'],returns:'void'});
/**
 * curl_global_init
 * @param {bigint|number} flags - i64
 * @returns {number} - i32
 */
export const curl_global_init = CFunction({ptr:__sym('curl_global_init'),args:['i64'],returns:'i32'});
/**
 * curl_global_init_mem
 * @param {bigint|number} flags - i64
 * @param {object|number|bigint|null} m - function
 * @param {object|number|bigint|null} f - function
 * @param {object|number|bigint|null} r - function
 * @param {object|number|bigint|null} s - function
 * @param {object|number|bigint|null} c - function
 * @returns {number} - i32
 */
export const curl_global_init_mem = CFunction({ptr:__sym('curl_global_init_mem'),args:['i64','function','function','function','function','function'],returns:'i32'});
/**
 * curl_global_cleanup
 * @returns {void}
 */
export const curl_global_cleanup = CFunction({ptr:__sym('curl_global_cleanup'),args:[],returns:'void'});
/**
 * curl_global_trace
 * @param {string|null} config - cstring
 * @returns {number} - i32
 */
export const curl_global_trace = CFunction({ptr:__sym('curl_global_trace'),args:['cstring'],returns:'i32'});
/**
 * curl_global_sslset
 * @param {number} id - i32
 * @param {string|null} name - cstring
 * @param {object|number|bigint|null} avail - curl_ssl_backend ***
 * @returns {number} - i32
 */
export const curl_global_sslset = CFunction({ptr:__sym('curl_global_sslset'),args:['i32','cstring','curl_ssl_backend ***'],returns:'i32'});
/**
 * curl_slist_append
 * @param {object|number|bigint|null} list - struct curl_slist *
 * @param {string|null} data - cstring
 * @returns {number|bigint|null} - struct curl_slist *
 */
export const curl_slist_append = CFunction({ptr:__sym('curl_slist_append'),args:['struct curl_slist *','cstring'],returns:'struct curl_slist *'});
/**
 * curl_slist_free_all
 * @param {object|number|bigint|null} list - struct curl_slist *
 * @returns {void}
 */
export const curl_slist_free_all = CFunction({ptr:__sym('curl_slist_free_all'),args:['struct curl_slist *'],returns:'void'});
/**
 * curl_getdate
 * @param {string|null} p - cstring
 * @param {object|number|bigint|null} unused - time_t *
 * @returns {bigint} - i64
 */
export const curl_getdate = CFunction({ptr:__sym('curl_getdate'),args:['cstring','time_t *'],returns:'i64'});
/**
 * curl_share_init
 * @returns {number|bigint|null} - CURLSH *
 */
export const curl_share_init = CFunction({ptr:__sym('curl_share_init'),args:[],returns:'CURLSH *'});
/**
 * curl_share_cleanup
 * @param {object|number|bigint|null} share - CURLSH *
 * @returns {number} - i32
 */
export const curl_share_cleanup = CFunction({ptr:__sym('curl_share_cleanup'),args:['CURLSH *'],returns:'i32'});
/**
 * curl_version_info
 * @param {number} a0 - i32
 * @returns {number|bigint|null} - curl_version_info_data *
 */
export const curl_version_info = CFunction({ptr:__sym('curl_version_info'),args:['i32'],returns:'curl_version_info_data *'});
/**
 * curl_easy_strerror
 * @param {number} a0 - i32
 * @returns {string} - cstring
 */
export const curl_easy_strerror = CFunction({ptr:__sym('curl_easy_strerror'),args:['i32'],returns:'cstring'});
/**
 * curl_share_strerror
 * @param {number} a0 - i32
 * @returns {string} - cstring
 */
export const curl_share_strerror = CFunction({ptr:__sym('curl_share_strerror'),args:['i32'],returns:'cstring'});
/**
 * curl_easy_pause
 * @param {object|number|bigint|null} handle - CURL *
 * @param {number} bitmask - i32
 * @returns {number} - i32
 */
export const curl_easy_pause = CFunction({ptr:__sym('curl_easy_pause'),args:['CURL *','i32'],returns:'i32'});
/**
 * curl_easy_init
 * @returns {number|bigint|null} - CURL *
 */
export const curl_easy_init = CFunction({ptr:__sym('curl_easy_init'),args:[],returns:'CURL *'});
/**
 * curl_easy_perform
 * @param {object|number|bigint|null} curl - CURL *
 * @returns {number} - i32
 */
export const curl_easy_perform = CFunction({ptr:__sym('curl_easy_perform'),args:['CURL *'],returns:'i32'});
/**
 * curl_easy_cleanup
 * @param {object|number|bigint|null} curl - CURL *
 * @returns {void}
 */
export const curl_easy_cleanup = CFunction({ptr:__sym('curl_easy_cleanup'),args:['CURL *'],returns:'void'});
/**
 * curl_easy_duphandle
 * @param {object|number|bigint|null} curl - CURL *
 * @returns {number|bigint|null} - CURL *
 */
export const curl_easy_duphandle = CFunction({ptr:__sym('curl_easy_duphandle'),args:['CURL *'],returns:'CURL *'});
/**
 * curl_easy_reset
 * @param {object|number|bigint|null} curl - CURL *
 * @returns {void}
 */
export const curl_easy_reset = CFunction({ptr:__sym('curl_easy_reset'),args:['CURL *'],returns:'void'});
/**
 * curl_easy_recv
 * @param {object|number|bigint|null} curl - CURL *
 * @param {object|number|bigint|null} buffer - void *
 * @param {bigint|number} buflen - u64
 * @param {object|number|bigint|null} n - size_t *
 * @returns {number} - i32
 */
export const curl_easy_recv = CFunction({ptr:__sym('curl_easy_recv'),args:['CURL *','void *','u64','size_t *'],returns:'i32'});
/**
 * curl_easy_send
 * @param {object|number|bigint|null} curl - CURL *
 * @param {object|number|bigint|null} buffer - void *
 * @param {bigint|number} buflen - u64
 * @param {object|number|bigint|null} n - size_t *
 * @returns {number} - i32
 */
export const curl_easy_send = CFunction({ptr:__sym('curl_easy_send'),args:['CURL *','void *','u64','size_t *'],returns:'i32'});
/**
 * curl_easy_upkeep
 * @param {object|number|bigint|null} curl - CURL *
 * @returns {number} - i32
 */
export const curl_easy_upkeep = CFunction({ptr:__sym('curl_easy_upkeep'),args:['CURL *'],returns:'i32'});
/**
 * curl_multi_init
 * @returns {number|bigint|null} - CURLM *
 */
export const curl_multi_init = CFunction({ptr:__sym('curl_multi_init'),args:[],returns:'CURLM *'});
/**
 * curl_multi_add_handle
 * @param {object|number|bigint|null} multi_handle - CURLM *
 * @param {object|number|bigint|null} curl_handle - CURL *
 * @returns {number} - i32
 */
export const curl_multi_add_handle = CFunction({ptr:__sym('curl_multi_add_handle'),args:['CURLM *','CURL *'],returns:'i32'});
/**
 * curl_multi_remove_handle
 * @param {object|number|bigint|null} multi_handle - CURLM *
 * @param {object|number|bigint|null} curl_handle - CURL *
 * @returns {number} - i32
 */
export const curl_multi_remove_handle = CFunction({ptr:__sym('curl_multi_remove_handle'),args:['CURLM *','CURL *'],returns:'i32'});
/**
 * curl_multi_fdset
 * @param {object|number|bigint|null} multi_handle - CURLM *
 * @param {object|number|bigint|null} read_fd_set - fd_set *
 * @param {object|number|bigint|null} write_fd_set - fd_set *
 * @param {object|number|bigint|null} exc_fd_set - fd_set *
 * @param {object|number|bigint|null} max_fd - int *
 * @returns {number} - i32
 */
export const curl_multi_fdset = CFunction({ptr:__sym('curl_multi_fdset'),args:['CURLM *','fd_set *','fd_set *','fd_set *','int *'],returns:'i32'});
/**
 * curl_multi_wait
 * @param {object|number|bigint|null} multi_handle - CURLM *
 * @param {object|number|bigint|null} extra_fds - struct curl_waitfd *
 * @param {number} extra_nfds - u32
 * @param {number} timeout_ms - i32
 * @param {object|number|bigint|null} ret - int *
 * @returns {number} - i32
 */
export const curl_multi_wait = CFunction({ptr:__sym('curl_multi_wait'),args:['CURLM *','struct curl_waitfd *','u32','i32','int *'],returns:'i32'});
/**
 * curl_multi_poll
 * @param {object|number|bigint|null} multi_handle - CURLM *
 * @param {object|number|bigint|null} extra_fds - struct curl_waitfd *
 * @param {number} extra_nfds - u32
 * @param {number} timeout_ms - i32
 * @param {object|number|bigint|null} ret - int *
 * @returns {number} - i32
 */
export const curl_multi_poll = CFunction({ptr:__sym('curl_multi_poll'),args:['CURLM *','struct curl_waitfd *','u32','i32','int *'],returns:'i32'});
/**
 * curl_multi_wakeup
 * @param {object|number|bigint|null} multi_handle - CURLM *
 * @returns {number} - i32
 */
export const curl_multi_wakeup = CFunction({ptr:__sym('curl_multi_wakeup'),args:['CURLM *'],returns:'i32'});
/**
 * curl_multi_perform
 * @param {object|number|bigint|null} multi_handle - CURLM *
 * @param {object|number|bigint|null} running_handles - int *
 * @returns {number} - i32
 */
export const curl_multi_perform = CFunction({ptr:__sym('curl_multi_perform'),args:['CURLM *','int *'],returns:'i32'});
/**
 * curl_multi_cleanup
 * @param {object|number|bigint|null} multi_handle - CURLM *
 * @returns {number} - i32
 */
export const curl_multi_cleanup = CFunction({ptr:__sym('curl_multi_cleanup'),args:['CURLM *'],returns:'i32'});
/**
 * curl_multi_info_read
 * @param {object|number|bigint|null} multi_handle - CURLM *
 * @param {object|number|bigint|null} msgs_in_queue - int *
 * @returns {number|bigint|null} - CURLMsg *
 */
export const curl_multi_info_read = CFunction({ptr:__sym('curl_multi_info_read'),args:['CURLM *','int *'],returns:'CURLMsg *'});
/**
 * curl_multi_strerror
 * @param {number} a0 - i32
 * @returns {string} - cstring
 */
export const curl_multi_strerror = CFunction({ptr:__sym('curl_multi_strerror'),args:['i32'],returns:'cstring'});
/**
 * curl_multi_socket
 * @param {object|number|bigint|null} multi_handle - CURLM *
 * @param {number} s - i32
 * @param {object|number|bigint|null} running_handles - int *
 * @returns {number} - i32
 */
export const curl_multi_socket = CFunction({ptr:__sym('curl_multi_socket'),args:['CURLM *','i32','int *'],returns:'i32'});
/**
 * curl_multi_socket_action
 * @param {object|number|bigint|null} multi_handle - CURLM *
 * @param {number} s - i32
 * @param {number} ev_bitmask - i32
 * @param {object|number|bigint|null} running_handles - int *
 * @returns {number} - i32
 */
export const curl_multi_socket_action = CFunction({ptr:__sym('curl_multi_socket_action'),args:['CURLM *','i32','i32','int *'],returns:'i32'});
/**
 * curl_multi_socket_all
 * @param {object|number|bigint|null} multi_handle - CURLM *
 * @param {object|number|bigint|null} running_handles - int *
 * @returns {number} - i32
 */
export const curl_multi_socket_all = CFunction({ptr:__sym('curl_multi_socket_all'),args:['CURLM *','int *'],returns:'i32'});
/**
 * curl_multi_timeout
 * @param {object|number|bigint|null} multi_handle - CURLM *
 * @param {object|number|bigint|null} milliseconds - long *
 * @returns {number} - i32
 */
export const curl_multi_timeout = CFunction({ptr:__sym('curl_multi_timeout'),args:['CURLM *','long *'],returns:'i32'});
/**
 * curl_multi_assign
 * @param {object|number|bigint|null} multi_handle - CURLM *
 * @param {number} sockfd - i32
 * @param {object|number|bigint|null} sockp - void *
 * @returns {number} - i32
 */
export const curl_multi_assign = CFunction({ptr:__sym('curl_multi_assign'),args:['CURLM *','i32','void *'],returns:'i32'});
/**
 * curl_multi_get_handles
 * @param {object|number|bigint|null} multi_handle - CURLM *
 * @returns {number|bigint|null} - CURL **
 */
export const curl_multi_get_handles = CFunction({ptr:__sym('curl_multi_get_handles'),args:['CURLM *'],returns:'CURL **'});
/**
 * curl_pushheader_bynum
 * @param {object|number|bigint|null} h - struct curl_pushheaders *
 * @param {bigint|number} num - u64
 * @returns {string} - cstring
 */
export const curl_pushheader_bynum = CFunction({ptr:__sym('curl_pushheader_bynum'),args:['struct curl_pushheaders *','u64'],returns:'cstring'});
/**
 * curl_pushheader_byname
 * @param {object|number|bigint|null} h - struct curl_pushheaders *
 * @param {string|null} name - cstring
 * @returns {string} - cstring
 */
export const curl_pushheader_byname = CFunction({ptr:__sym('curl_pushheader_byname'),args:['struct curl_pushheaders *','cstring'],returns:'cstring'});
/**
 * curl_url
 * @returns {number|bigint|null} - CURLU *
 */
export const curl_url = CFunction({ptr:__sym('curl_url'),args:[],returns:'CURLU *'});
/**
 * curl_url_cleanup
 * @param {object|number|bigint|null} handle - CURLU *
 * @returns {void}
 */
export const curl_url_cleanup = CFunction({ptr:__sym('curl_url_cleanup'),args:['CURLU *'],returns:'void'});
/**
 * curl_url_dup
 * @param {object|number|bigint|null} _in - CURLU *
 * @returns {number|bigint|null} - CURLU *
 */
export const curl_url_dup = CFunction({ptr:__sym('curl_url_dup'),args:['CURLU *'],returns:'CURLU *'});
/**
 * curl_url_get
 * @param {object|number|bigint|null} handle - CURLU *
 * @param {number} what - i32
 * @param {object|number|bigint|null} part - char **
 * @param {number} flags - u32
 * @returns {number} - i32
 */
export const curl_url_get = CFunction({ptr:__sym('curl_url_get'),args:['CURLU *','i32','char **','u32'],returns:'i32'});
/**
 * curl_url_set
 * @param {object|number|bigint|null} handle - CURLU *
 * @param {number} what - i32
 * @param {string|null} part - cstring
 * @param {number} flags - u32
 * @returns {number} - i32
 */
export const curl_url_set = CFunction({ptr:__sym('curl_url_set'),args:['CURLU *','i32','cstring','u32'],returns:'i32'});
/**
 * curl_url_strerror
 * @param {number} a0 - i32
 * @returns {string} - cstring
 */
export const curl_url_strerror = CFunction({ptr:__sym('curl_url_strerror'),args:['i32'],returns:'cstring'});
/**
 * curl_easy_option_by_name
 * @param {string|null} name - cstring
 * @returns {number|bigint|null} - struct curl_easyoption *
 */
export const curl_easy_option_by_name = CFunction({ptr:__sym('curl_easy_option_by_name'),args:['cstring'],returns:'struct curl_easyoption *'});
/**
 * curl_easy_option_by_id
 * @param {number} id - i32
 * @returns {number|bigint|null} - struct curl_easyoption *
 */
export const curl_easy_option_by_id = CFunction({ptr:__sym('curl_easy_option_by_id'),args:['i32'],returns:'struct curl_easyoption *'});
/**
 * curl_easy_option_next
 * @param {object|number|bigint|null} prev - struct curl_easyoption *
 * @returns {number|bigint|null} - struct curl_easyoption *
 */
export const curl_easy_option_next = CFunction({ptr:__sym('curl_easy_option_next'),args:['struct curl_easyoption *'],returns:'struct curl_easyoption *'});
/**
 * curl_easy_header
 * @param {object|number|bigint|null} easy - CURL *
 * @param {string|null} name - cstring
 * @param {bigint|number} index - u64
 * @param {number} origin - u32
 * @param {number} request - i32
 * @param {object|number|bigint|null} hout - struct curl_header **
 * @returns {number} - i32
 */
export const curl_easy_header = CFunction({ptr:__sym('curl_easy_header'),args:['CURL *','cstring','u64','u32','i32','struct curl_header **'],returns:'i32'});
/**
 * curl_easy_nextheader
 * @param {object|number|bigint|null} easy - CURL *
 * @param {number} origin - u32
 * @param {number} request - i32
 * @param {object|number|bigint|null} prev - struct curl_header *
 * @returns {number|bigint|null} - struct curl_header *
 */
export const curl_easy_nextheader = CFunction({ptr:__sym('curl_easy_nextheader'),args:['CURL *','u32','i32','struct curl_header *'],returns:'struct curl_header *'});
/**
 * curl_ws_recv
 * @param {object|number|bigint|null} curl - CURL *
 * @param {object|number|bigint|null} buffer - void *
 * @param {bigint|number} buflen - u64
 * @param {object|number|bigint|null} recv - size_t *
 * @param {object|number|bigint|null} metap - struct curl_ws_frame **
 * @returns {number} - i32
 */
export const curl_ws_recv = CFunction({ptr:__sym('curl_ws_recv'),args:['CURL *','void *','u64','size_t *','struct curl_ws_frame **'],returns:'i32'});
/**
 * curl_ws_send
 * @param {object|number|bigint|null} curl - CURL *
 * @param {object|number|bigint|null} buffer - void *
 * @param {bigint|number} buflen - u64
 * @param {object|number|bigint|null} sent - size_t *
 * @param {bigint|number} fragsize - i64
 * @param {number} flags - u32
 * @returns {number} - i32
 */
export const curl_ws_send = CFunction({ptr:__sym('curl_ws_send'),args:['CURL *','void *','u64','size_t *','i64','u32'],returns:'i32'});
/**
 * curl_ws_meta
 * @param {object|number|bigint|null} curl - CURL *
 * @returns {number|bigint|null} - struct curl_ws_frame *
 */
export const curl_ws_meta = CFunction({ptr:__sym('curl_ws_meta'),args:['CURL *'],returns:'struct curl_ws_frame *'});
/**
 * curl_mvprintf
 * @param {string|null} format - cstring
 * @param {object|number|bigint|null} args - struct __va_list_tag *
 * @returns {number} - i32
 */
export const curl_mvprintf = CFunction({ptr:__sym('curl_mvprintf'),args:['cstring','struct __va_list_tag *'],returns:'i32'});
/**
 * curl_mvfprintf
 * @param {object|number|bigint|null} fd - FILE *
 * @param {string|null} format - cstring
 * @param {object|number|bigint|null} args - struct __va_list_tag *
 * @returns {number} - i32
 */
export const curl_mvfprintf = CFunction({ptr:__sym('curl_mvfprintf'),args:['FILE *','cstring','struct __va_list_tag *'],returns:'i32'});
/**
 * curl_mvsprintf
 * @param {string|null} buffer - cstring
 * @param {string|null} format - cstring
 * @param {object|number|bigint|null} args - struct __va_list_tag *
 * @returns {number} - i32
 */
export const curl_mvsprintf = CFunction({ptr:__sym('curl_mvsprintf'),args:['cstring','cstring','struct __va_list_tag *'],returns:'i32'});
/**
 * curl_mvsnprintf
 * @param {string|null} buffer - cstring
 * @param {bigint|number} maxlength - u64
 * @param {string|null} format - cstring
 * @param {object|number|bigint|null} args - struct __va_list_tag *
 * @returns {number} - i32
 */
export const curl_mvsnprintf = CFunction({ptr:__sym('curl_mvsnprintf'),args:['cstring','u64','cstring','struct __va_list_tag *'],returns:'i32'});
/**
 * curl_mvaprintf
 * @param {string|null} format - cstring
 * @param {object|number|bigint|null} args - struct __va_list_tag *
 * @returns {string} - cstring
 */
export const curl_mvaprintf = CFunction({ptr:__sym('curl_mvaprintf'),args:['cstring','struct __va_list_tag *'],returns:'cstring'});

// Skipped (unsupported):
//   - curl_formadd: variadic functions are not supported
//   - curl_share_setopt: variadic functions are not supported
//   - curl_easy_setopt: variadic functions are not supported
//   - curl_easy_getinfo: variadic functions are not supported
//   - curl_multi_setopt: variadic functions are not supported
//   - curl_mprintf: variadic functions are not supported
//   - curl_mfprintf: variadic functions are not supported
//   - curl_msprintf: variadic functions are not supported
//   - curl_msnprintf: variadic functions are not supported
//   - curl_maprintf: variadic functions are not supported
