/* Auto-generated by qjsm tools/gen-bindings.js from /usr/include/libusb-1.0/libusb.h -- do not edit by hand.
 * Regenerate with:
 *   qjsm tools/gen-bindings.js --api=cfunction --library=libusb-1.0.so.0 --ffitype  /usr/include/libusb-1.0/libusb.h
 * (clang invocation used to build the AST, once per source: clang -Xclang -ast-dump=json -fsyntax-only <source>)
 */
import { CFunction, FFIType, dlsym, dlopen, RTLD_NOW } from 'ffi';

const __lib = dlopen("libusb-1.0.so.0", RTLD_NOW);
if (__lib == null) throw new Error("gen-bindings: dlopen(libusb-1.0.so.0) failed");

function __sym(name) {
  const p = dlsym(__lib, name);
  if(p == null) throw new Error("gen-bindings: symbol not found: " + name);
  return p;
}

export const libusb_init = CFunction({ ptr: __sym("libusb_init"), args: ["libusb_context **"], returns: FFIType.i32 });
export const libusb_init_context = CFunction({ ptr: __sym("libusb_init_context"), args: ["libusb_context **", "struct libusb_init_option *", FFIType.i32], returns: FFIType.i32 });
export const libusb_exit = CFunction({ ptr: __sym("libusb_exit"), args: ["libusb_context *"], returns: FFIType.void });
export const libusb_set_debug = CFunction({ ptr: __sym("libusb_set_debug"), args: ["libusb_context *", FFIType.i32], returns: FFIType.void });
export const libusb_set_log_cb = CFunction({ ptr: __sym("libusb_set_log_cb"), args: ["libusb_context *", FFIType.function, FFIType.i32], returns: FFIType.void });
export const libusb_get_version = CFunction({ ptr: __sym("libusb_get_version"), args: [], returns: "struct libusb_version *" });
export const libusb_has_capability = CFunction({ ptr: __sym("libusb_has_capability"), args: [FFIType.u32], returns: FFIType.i32 });
export const libusb_error_name = CFunction({ ptr: __sym("libusb_error_name"), args: [FFIType.i32], returns: FFIType.cstring });
export const libusb_setlocale = CFunction({ ptr: __sym("libusb_setlocale"), args: [FFIType.cstring], returns: FFIType.i32 });
export const libusb_strerror = CFunction({ ptr: __sym("libusb_strerror"), args: [FFIType.i32], returns: FFIType.cstring });
export const libusb_get_device_list = CFunction({ ptr: __sym("libusb_get_device_list"), args: ["libusb_context *", "libusb_device ***"], returns: FFIType.i64 });
export const libusb_free_device_list = CFunction({ ptr: __sym("libusb_free_device_list"), args: ["libusb_device **", FFIType.i32], returns: FFIType.void });
export const libusb_ref_device = CFunction({ ptr: __sym("libusb_ref_device"), args: ["libusb_device *"], returns: "libusb_device *" });
export const libusb_unref_device = CFunction({ ptr: __sym("libusb_unref_device"), args: ["libusb_device *"], returns: FFIType.void });
export const libusb_get_configuration = CFunction({ ptr: __sym("libusb_get_configuration"), args: ["libusb_device_handle *", "int *"], returns: FFIType.i32 });
export const libusb_get_device_descriptor = CFunction({ ptr: __sym("libusb_get_device_descriptor"), args: ["libusb_device *", "struct libusb_device_descriptor *"], returns: FFIType.i32 });
export const libusb_get_active_config_descriptor = CFunction({ ptr: __sym("libusb_get_active_config_descriptor"), args: ["libusb_device *", "struct libusb_config_descriptor **"], returns: FFIType.i32 });
export const libusb_get_config_descriptor = CFunction({ ptr: __sym("libusb_get_config_descriptor"), args: ["libusb_device *", FFIType.u8, "struct libusb_config_descriptor **"], returns: FFIType.i32 });
export const libusb_get_config_descriptor_by_value = CFunction({ ptr: __sym("libusb_get_config_descriptor_by_value"), args: ["libusb_device *", FFIType.u8, "struct libusb_config_descriptor **"], returns: FFIType.i32 });
export const libusb_free_config_descriptor = CFunction({ ptr: __sym("libusb_free_config_descriptor"), args: ["struct libusb_config_descriptor *"], returns: FFIType.void });
export const libusb_get_ss_endpoint_companion_descriptor = CFunction({ ptr: __sym("libusb_get_ss_endpoint_companion_descriptor"), args: ["libusb_context *", "struct libusb_endpoint_descriptor *", "struct libusb_ss_endpoint_companion_descriptor **"], returns: FFIType.i32 });
export const libusb_free_ss_endpoint_companion_descriptor = CFunction({ ptr: __sym("libusb_free_ss_endpoint_companion_descriptor"), args: ["struct libusb_ss_endpoint_companion_descriptor *"], returns: FFIType.void });
export const libusb_get_bos_descriptor = CFunction({ ptr: __sym("libusb_get_bos_descriptor"), args: ["libusb_device_handle *", "struct libusb_bos_descriptor **"], returns: FFIType.i32 });
export const libusb_free_bos_descriptor = CFunction({ ptr: __sym("libusb_free_bos_descriptor"), args: ["struct libusb_bos_descriptor *"], returns: FFIType.void });
export const libusb_get_usb_2_0_extension_descriptor = CFunction({ ptr: __sym("libusb_get_usb_2_0_extension_descriptor"), args: ["libusb_context *", "struct libusb_bos_dev_capability_descriptor *", "struct libusb_usb_2_0_extension_descriptor **"], returns: FFIType.i32 });
export const libusb_free_usb_2_0_extension_descriptor = CFunction({ ptr: __sym("libusb_free_usb_2_0_extension_descriptor"), args: ["struct libusb_usb_2_0_extension_descriptor *"], returns: FFIType.void });
export const libusb_get_ss_usb_device_capability_descriptor = CFunction({ ptr: __sym("libusb_get_ss_usb_device_capability_descriptor"), args: ["libusb_context *", "struct libusb_bos_dev_capability_descriptor *", "struct libusb_ss_usb_device_capability_descriptor **"], returns: FFIType.i32 });
export const libusb_free_ss_usb_device_capability_descriptor = CFunction({ ptr: __sym("libusb_free_ss_usb_device_capability_descriptor"), args: ["struct libusb_ss_usb_device_capability_descriptor *"], returns: FFIType.void });
export const libusb_get_container_id_descriptor = CFunction({ ptr: __sym("libusb_get_container_id_descriptor"), args: ["libusb_context *", "struct libusb_bos_dev_capability_descriptor *", "struct libusb_container_id_descriptor **"], returns: FFIType.i32 });
export const libusb_free_container_id_descriptor = CFunction({ ptr: __sym("libusb_free_container_id_descriptor"), args: ["struct libusb_container_id_descriptor *"], returns: FFIType.void });
export const libusb_get_platform_descriptor = CFunction({ ptr: __sym("libusb_get_platform_descriptor"), args: ["libusb_context *", "struct libusb_bos_dev_capability_descriptor *", "struct libusb_platform_descriptor **"], returns: FFIType.i32 });
export const libusb_free_platform_descriptor = CFunction({ ptr: __sym("libusb_free_platform_descriptor"), args: ["struct libusb_platform_descriptor *"], returns: FFIType.void });
export const libusb_get_bus_number = CFunction({ ptr: __sym("libusb_get_bus_number"), args: ["libusb_device *"], returns: FFIType.u8 });
export const libusb_get_port_number = CFunction({ ptr: __sym("libusb_get_port_number"), args: ["libusb_device *"], returns: FFIType.u8 });
export const libusb_get_port_numbers = CFunction({ ptr: __sym("libusb_get_port_numbers"), args: ["libusb_device *", "uint8_t *", FFIType.i32], returns: FFIType.i32 });
export const libusb_get_port_path = CFunction({ ptr: __sym("libusb_get_port_path"), args: ["libusb_context *", "libusb_device *", "uint8_t *", FFIType.u8], returns: FFIType.i32 });
export const libusb_get_parent = CFunction({ ptr: __sym("libusb_get_parent"), args: ["libusb_device *"], returns: "libusb_device *" });
export const libusb_get_device_address = CFunction({ ptr: __sym("libusb_get_device_address"), args: ["libusb_device *"], returns: FFIType.u8 });
export const libusb_get_device_speed = CFunction({ ptr: __sym("libusb_get_device_speed"), args: ["libusb_device *"], returns: FFIType.i32 });
export const libusb_get_max_packet_size = CFunction({ ptr: __sym("libusb_get_max_packet_size"), args: ["libusb_device *", FFIType.u8], returns: FFIType.i32 });
export const libusb_get_max_iso_packet_size = CFunction({ ptr: __sym("libusb_get_max_iso_packet_size"), args: ["libusb_device *", FFIType.u8], returns: FFIType.i32 });
export const libusb_get_max_alt_packet_size = CFunction({ ptr: __sym("libusb_get_max_alt_packet_size"), args: ["libusb_device *", FFIType.i32, FFIType.i32, FFIType.u8], returns: FFIType.i32 });
export const libusb_get_interface_association_descriptors = CFunction({ ptr: __sym("libusb_get_interface_association_descriptors"), args: ["libusb_device *", FFIType.u8, "struct libusb_interface_association_descriptor_array **"], returns: FFIType.i32 });
export const libusb_get_active_interface_association_descriptors = CFunction({ ptr: __sym("libusb_get_active_interface_association_descriptors"), args: ["libusb_device *", "struct libusb_interface_association_descriptor_array **"], returns: FFIType.i32 });
export const libusb_free_interface_association_descriptors = CFunction({ ptr: __sym("libusb_free_interface_association_descriptors"), args: ["struct libusb_interface_association_descriptor_array *"], returns: FFIType.void });
export const libusb_wrap_sys_device = CFunction({ ptr: __sym("libusb_wrap_sys_device"), args: ["libusb_context *", FFIType.i64, "libusb_device_handle **"], returns: FFIType.i32 });
export const libusb_open = CFunction({ ptr: __sym("libusb_open"), args: ["libusb_device *", "libusb_device_handle **"], returns: FFIType.i32 });
export const libusb_close = CFunction({ ptr: __sym("libusb_close"), args: ["libusb_device_handle *"], returns: FFIType.void });
export const libusb_get_device = CFunction({ ptr: __sym("libusb_get_device"), args: ["libusb_device_handle *"], returns: "libusb_device *" });
export const libusb_set_configuration = CFunction({ ptr: __sym("libusb_set_configuration"), args: ["libusb_device_handle *", FFIType.i32], returns: FFIType.i32 });
export const libusb_claim_interface = CFunction({ ptr: __sym("libusb_claim_interface"), args: ["libusb_device_handle *", FFIType.i32], returns: FFIType.i32 });
export const libusb_release_interface = CFunction({ ptr: __sym("libusb_release_interface"), args: ["libusb_device_handle *", FFIType.i32], returns: FFIType.i32 });
export const libusb_open_device_with_vid_pid = CFunction({ ptr: __sym("libusb_open_device_with_vid_pid"), args: ["libusb_context *", FFIType.u16, FFIType.u16], returns: "libusb_device_handle *" });
export const libusb_set_interface_alt_setting = CFunction({ ptr: __sym("libusb_set_interface_alt_setting"), args: ["libusb_device_handle *", FFIType.i32, FFIType.i32], returns: FFIType.i32 });
export const libusb_clear_halt = CFunction({ ptr: __sym("libusb_clear_halt"), args: ["libusb_device_handle *", FFIType.u8], returns: FFIType.i32 });
export const libusb_reset_device = CFunction({ ptr: __sym("libusb_reset_device"), args: ["libusb_device_handle *"], returns: FFIType.i32 });
export const libusb_alloc_streams = CFunction({ ptr: __sym("libusb_alloc_streams"), args: ["libusb_device_handle *", FFIType.u32, "unsigned char *", FFIType.i32], returns: FFIType.i32 });
export const libusb_free_streams = CFunction({ ptr: __sym("libusb_free_streams"), args: ["libusb_device_handle *", "unsigned char *", FFIType.i32], returns: FFIType.i32 });
export const libusb_dev_mem_alloc = CFunction({ ptr: __sym("libusb_dev_mem_alloc"), args: ["libusb_device_handle *", FFIType.u64], returns: "unsigned char *" });
export const libusb_dev_mem_free = CFunction({ ptr: __sym("libusb_dev_mem_free"), args: ["libusb_device_handle *", "unsigned char *", FFIType.u64], returns: FFIType.i32 });
export const libusb_kernel_driver_active = CFunction({ ptr: __sym("libusb_kernel_driver_active"), args: ["libusb_device_handle *", FFIType.i32], returns: FFIType.i32 });
export const libusb_detach_kernel_driver = CFunction({ ptr: __sym("libusb_detach_kernel_driver"), args: ["libusb_device_handle *", FFIType.i32], returns: FFIType.i32 });
export const libusb_attach_kernel_driver = CFunction({ ptr: __sym("libusb_attach_kernel_driver"), args: ["libusb_device_handle *", FFIType.i32], returns: FFIType.i32 });
export const libusb_set_auto_detach_kernel_driver = CFunction({ ptr: __sym("libusb_set_auto_detach_kernel_driver"), args: ["libusb_device_handle *", FFIType.i32], returns: FFIType.i32 });
export const libusb_alloc_transfer = CFunction({ ptr: __sym("libusb_alloc_transfer"), args: [FFIType.i32], returns: "struct libusb_transfer *" });
export const libusb_submit_transfer = CFunction({ ptr: __sym("libusb_submit_transfer"), args: ["struct libusb_transfer *"], returns: FFIType.i32 });
export const libusb_cancel_transfer = CFunction({ ptr: __sym("libusb_cancel_transfer"), args: ["struct libusb_transfer *"], returns: FFIType.i32 });
export const libusb_free_transfer = CFunction({ ptr: __sym("libusb_free_transfer"), args: ["struct libusb_transfer *"], returns: FFIType.void });
export const libusb_transfer_set_stream_id = CFunction({ ptr: __sym("libusb_transfer_set_stream_id"), args: ["struct libusb_transfer *", FFIType.u32], returns: FFIType.void });
export const libusb_transfer_get_stream_id = CFunction({ ptr: __sym("libusb_transfer_get_stream_id"), args: ["struct libusb_transfer *"], returns: FFIType.u32 });
export const libusb_control_transfer = CFunction({ ptr: __sym("libusb_control_transfer"), args: ["libusb_device_handle *", FFIType.u8, FFIType.u8, FFIType.u16, FFIType.u16, "unsigned char *", FFIType.u16, FFIType.u32], returns: FFIType.i32 });
export const libusb_bulk_transfer = CFunction({ ptr: __sym("libusb_bulk_transfer"), args: ["libusb_device_handle *", FFIType.u8, "unsigned char *", FFIType.i32, "int *", FFIType.u32], returns: FFIType.i32 });
export const libusb_interrupt_transfer = CFunction({ ptr: __sym("libusb_interrupt_transfer"), args: ["libusb_device_handle *", FFIType.u8, "unsigned char *", FFIType.i32, "int *", FFIType.u32], returns: FFIType.i32 });
export const libusb_get_string_descriptor_ascii = CFunction({ ptr: __sym("libusb_get_string_descriptor_ascii"), args: ["libusb_device_handle *", FFIType.u8, "unsigned char *", FFIType.i32], returns: FFIType.i32 });
export const libusb_try_lock_events = CFunction({ ptr: __sym("libusb_try_lock_events"), args: ["libusb_context *"], returns: FFIType.i32 });
export const libusb_lock_events = CFunction({ ptr: __sym("libusb_lock_events"), args: ["libusb_context *"], returns: FFIType.void });
export const libusb_unlock_events = CFunction({ ptr: __sym("libusb_unlock_events"), args: ["libusb_context *"], returns: FFIType.void });
export const libusb_event_handling_ok = CFunction({ ptr: __sym("libusb_event_handling_ok"), args: ["libusb_context *"], returns: FFIType.i32 });
export const libusb_event_handler_active = CFunction({ ptr: __sym("libusb_event_handler_active"), args: ["libusb_context *"], returns: FFIType.i32 });
export const libusb_interrupt_event_handler = CFunction({ ptr: __sym("libusb_interrupt_event_handler"), args: ["libusb_context *"], returns: FFIType.void });
export const libusb_lock_event_waiters = CFunction({ ptr: __sym("libusb_lock_event_waiters"), args: ["libusb_context *"], returns: FFIType.void });
export const libusb_unlock_event_waiters = CFunction({ ptr: __sym("libusb_unlock_event_waiters"), args: ["libusb_context *"], returns: FFIType.void });
export const libusb_wait_for_event = CFunction({ ptr: __sym("libusb_wait_for_event"), args: ["libusb_context *", "struct timeval *"], returns: FFIType.i32 });
export const libusb_handle_events_timeout = CFunction({ ptr: __sym("libusb_handle_events_timeout"), args: ["libusb_context *", "struct timeval *"], returns: FFIType.i32 });
export const libusb_handle_events_timeout_completed = CFunction({ ptr: __sym("libusb_handle_events_timeout_completed"), args: ["libusb_context *", "struct timeval *", "int *"], returns: FFIType.i32 });
export const libusb_handle_events = CFunction({ ptr: __sym("libusb_handle_events"), args: ["libusb_context *"], returns: FFIType.i32 });
export const libusb_handle_events_completed = CFunction({ ptr: __sym("libusb_handle_events_completed"), args: ["libusb_context *", "int *"], returns: FFIType.i32 });
export const libusb_handle_events_locked = CFunction({ ptr: __sym("libusb_handle_events_locked"), args: ["libusb_context *", "struct timeval *"], returns: FFIType.i32 });
export const libusb_pollfds_handle_timeouts = CFunction({ ptr: __sym("libusb_pollfds_handle_timeouts"), args: ["libusb_context *"], returns: FFIType.i32 });
export const libusb_get_next_timeout = CFunction({ ptr: __sym("libusb_get_next_timeout"), args: ["libusb_context *", "struct timeval *"], returns: FFIType.i32 });
export const libusb_get_pollfds = CFunction({ ptr: __sym("libusb_get_pollfds"), args: ["libusb_context *"], returns: "struct libusb_pollfd **" });
export const libusb_free_pollfds = CFunction({ ptr: __sym("libusb_free_pollfds"), args: ["struct libusb_pollfd **"], returns: FFIType.void });
export const libusb_set_pollfd_notifiers = CFunction({ ptr: __sym("libusb_set_pollfd_notifiers"), args: ["libusb_context *", FFIType.function, FFIType.function, "void *"], returns: FFIType.void });
export const libusb_hotplug_register_callback = CFunction({ ptr: __sym("libusb_hotplug_register_callback"), args: ["libusb_context *", FFIType.i32, FFIType.i32, FFIType.i32, FFIType.i32, FFIType.i32, FFIType.function, "void *", "libusb_hotplug_callback_handle *"], returns: FFIType.i32 });
export const libusb_hotplug_deregister_callback = CFunction({ ptr: __sym("libusb_hotplug_deregister_callback"), args: ["libusb_context *", FFIType.i32], returns: FFIType.void });
export const libusb_hotplug_get_user_data = CFunction({ ptr: __sym("libusb_hotplug_get_user_data"), args: ["libusb_context *", FFIType.i32], returns: "void *" });

// Skipped (unsupported):
//   - libusb_set_option: variadic functions are not supported
