/* Auto-generated by qjsm tools/gen-bindings.js from /usr/include/SDL2/SDL_video.h -- do not edit by hand.
 * Regenerate with:
 *   qjsm tools/gen-bindings.js --api=cfunction --library=libSDL2-2.0.so.0 -I/usr/include/SDL2 /usr/include/SDL2/SDL_video.h
 * (clang invocation used to build the AST: clang -Xclang -ast-dump=json -fsyntax-only -I/usr/include/SDL2 /usr/include/SDL2/SDL_video.h)
 */
import { CFunction, dlsym, dlopen, RTLD_NOW } from 'ffi';

const __lib = dlopen("libSDL2-2.0.so.0", RTLD_NOW);
if (__lib == null) throw new Error("gen-bindings: dlopen(libSDL2-2.0.so.0) failed");

function __sym(name) {
  const p = dlsym(__lib, name);
  if (p == null) throw new Error("gen-bindings: symbol not found: " + name);
  return p;
}

// enum (anonymous)
export const SDL_ORIENTATION_UNKNOWN = 0;
export const SDL_ORIENTATION_LANDSCAPE = 1;
export const SDL_ORIENTATION_LANDSCAPE_FLIPPED = 2;
export const SDL_ORIENTATION_PORTRAIT = 3;
export const SDL_ORIENTATION_PORTRAIT_FLIPPED = 4;

// enum (anonymous)
export const SDL_FALSE = 0;
export const SDL_TRUE = 1;

// enum (anonymous)
export const SDL_FLASH_CANCEL = 0;
export const SDL_FLASH_BRIEFLY = 1;
export const SDL_FLASH_UNTIL_FOCUSED = 2;

// enum (anonymous)
export const SDL_GL_RED_SIZE = 0;
export const SDL_GL_GREEN_SIZE = 1;
export const SDL_GL_BLUE_SIZE = 2;
export const SDL_GL_ALPHA_SIZE = 3;
export const SDL_GL_BUFFER_SIZE = 4;
export const SDL_GL_DOUBLEBUFFER = 5;
export const SDL_GL_DEPTH_SIZE = 6;
export const SDL_GL_STENCIL_SIZE = 7;
export const SDL_GL_ACCUM_RED_SIZE = 8;
export const SDL_GL_ACCUM_GREEN_SIZE = 9;
export const SDL_GL_ACCUM_BLUE_SIZE = 10;
export const SDL_GL_ACCUM_ALPHA_SIZE = 11;
export const SDL_GL_STEREO = 12;
export const SDL_GL_MULTISAMPLEBUFFERS = 13;
export const SDL_GL_MULTISAMPLESAMPLES = 14;
export const SDL_GL_ACCELERATED_VISUAL = 15;
export const SDL_GL_RETAINED_BACKING = 16;
export const SDL_GL_CONTEXT_MAJOR_VERSION = 17;
export const SDL_GL_CONTEXT_MINOR_VERSION = 18;
export const SDL_GL_CONTEXT_EGL = 19;
export const SDL_GL_CONTEXT_FLAGS = 20;
export const SDL_GL_CONTEXT_PROFILE_MASK = 21;
export const SDL_GL_SHARE_WITH_CURRENT_CONTEXT = 22;
export const SDL_GL_FRAMEBUFFER_SRGB_CAPABLE = 23;
export const SDL_GL_CONTEXT_RELEASE_BEHAVIOR = 24;
export const SDL_GL_CONTEXT_RESET_NOTIFICATION = 25;
export const SDL_GL_CONTEXT_NO_ERROR = 26;
export const SDL_GL_FLOATBUFFERS = 27;

export const SDL_GetNumVideoDrivers = CFunction({ ptr: __sym("SDL_GetNumVideoDrivers"), args: [], returns: "i32" });
export const SDL_GetVideoDriver = CFunction({ ptr: __sym("SDL_GetVideoDriver"), args: ["i32"], returns: "cstring" });
export const SDL_VideoInit = CFunction({ ptr: __sym("SDL_VideoInit"), args: ["cstring"], returns: "i32" });
export const SDL_VideoQuit = CFunction({ ptr: __sym("SDL_VideoQuit"), args: [], returns: "void" });
export const SDL_GetCurrentVideoDriver = CFunction({ ptr: __sym("SDL_GetCurrentVideoDriver"), args: [], returns: "cstring" });
export const SDL_GetNumVideoDisplays = CFunction({ ptr: __sym("SDL_GetNumVideoDisplays"), args: [], returns: "i32" });
export const SDL_GetDisplayName = CFunction({ ptr: __sym("SDL_GetDisplayName"), args: ["i32"], returns: "cstring" });
export const SDL_GetDisplayBounds = CFunction({ ptr: __sym("SDL_GetDisplayBounds"), args: ["i32", "pointer"], returns: "i32" });
export const SDL_GetDisplayUsableBounds = CFunction({ ptr: __sym("SDL_GetDisplayUsableBounds"), args: ["i32", "pointer"], returns: "i32" });
export const SDL_GetDisplayDPI = CFunction({ ptr: __sym("SDL_GetDisplayDPI"), args: ["i32", "pointer", "pointer", "pointer"], returns: "i32" });
export const SDL_GetDisplayOrientation = CFunction({ ptr: __sym("SDL_GetDisplayOrientation"), args: ["i32"], returns: "i32" });
export const SDL_GetNumDisplayModes = CFunction({ ptr: __sym("SDL_GetNumDisplayModes"), args: ["i32"], returns: "i32" });
export const SDL_GetDisplayMode = CFunction({ ptr: __sym("SDL_GetDisplayMode"), args: ["i32", "i32", "pointer"], returns: "i32" });
export const SDL_GetDesktopDisplayMode = CFunction({ ptr: __sym("SDL_GetDesktopDisplayMode"), args: ["i32", "pointer"], returns: "i32" });
export const SDL_GetCurrentDisplayMode = CFunction({ ptr: __sym("SDL_GetCurrentDisplayMode"), args: ["i32", "pointer"], returns: "i32" });
export const SDL_GetClosestDisplayMode = CFunction({ ptr: __sym("SDL_GetClosestDisplayMode"), args: ["i32", "pointer", "pointer"], returns: "pointer" });
export const SDL_GetPointDisplayIndex = CFunction({ ptr: __sym("SDL_GetPointDisplayIndex"), args: ["pointer"], returns: "i32" });
export const SDL_GetRectDisplayIndex = CFunction({ ptr: __sym("SDL_GetRectDisplayIndex"), args: ["pointer"], returns: "i32" });
export const SDL_GetWindowDisplayIndex = CFunction({ ptr: __sym("SDL_GetWindowDisplayIndex"), args: ["pointer"], returns: "i32" });
export const SDL_SetWindowDisplayMode = CFunction({ ptr: __sym("SDL_SetWindowDisplayMode"), args: ["pointer", "pointer"], returns: "i32" });
export const SDL_GetWindowDisplayMode = CFunction({ ptr: __sym("SDL_GetWindowDisplayMode"), args: ["pointer", "pointer"], returns: "i32" });
export const SDL_GetWindowICCProfile = CFunction({ ptr: __sym("SDL_GetWindowICCProfile"), args: ["pointer", "pointer"], returns: "pointer" });
export const SDL_GetWindowPixelFormat = CFunction({ ptr: __sym("SDL_GetWindowPixelFormat"), args: ["pointer"], returns: "u32" });
export const SDL_CreateWindow = CFunction({ ptr: __sym("SDL_CreateWindow"), args: ["cstring", "i32", "i32", "i32", "i32", "u32"], returns: "pointer" });
export const SDL_CreateWindowFrom = CFunction({ ptr: __sym("SDL_CreateWindowFrom"), args: ["pointer"], returns: "pointer" });
export const SDL_GetWindowID = CFunction({ ptr: __sym("SDL_GetWindowID"), args: ["pointer"], returns: "u32" });
export const SDL_GetWindowFromID = CFunction({ ptr: __sym("SDL_GetWindowFromID"), args: ["u32"], returns: "pointer" });
export const SDL_GetWindowFlags = CFunction({ ptr: __sym("SDL_GetWindowFlags"), args: ["pointer"], returns: "u32" });
export const SDL_SetWindowTitle = CFunction({ ptr: __sym("SDL_SetWindowTitle"), args: ["pointer", "cstring"], returns: "void" });
export const SDL_GetWindowTitle = CFunction({ ptr: __sym("SDL_GetWindowTitle"), args: ["pointer"], returns: "cstring" });
export const SDL_SetWindowIcon = CFunction({ ptr: __sym("SDL_SetWindowIcon"), args: ["pointer", "pointer"], returns: "void" });
export const SDL_SetWindowData = CFunction({ ptr: __sym("SDL_SetWindowData"), args: ["pointer", "cstring", "pointer"], returns: "pointer" });
export const SDL_GetWindowData = CFunction({ ptr: __sym("SDL_GetWindowData"), args: ["pointer", "cstring"], returns: "pointer" });
export const SDL_SetWindowPosition = CFunction({ ptr: __sym("SDL_SetWindowPosition"), args: ["pointer", "i32", "i32"], returns: "void" });
export const SDL_GetWindowPosition = CFunction({ ptr: __sym("SDL_GetWindowPosition"), args: ["pointer", "pointer", "pointer"], returns: "void" });
export const SDL_SetWindowSize = CFunction({ ptr: __sym("SDL_SetWindowSize"), args: ["pointer", "i32", "i32"], returns: "void" });
export const SDL_GetWindowSize = CFunction({ ptr: __sym("SDL_GetWindowSize"), args: ["pointer", "pointer", "pointer"], returns: "void" });
export const SDL_GetWindowBordersSize = CFunction({ ptr: __sym("SDL_GetWindowBordersSize"), args: ["pointer", "pointer", "pointer", "pointer", "pointer"], returns: "i32" });
export const SDL_GetWindowSizeInPixels = CFunction({ ptr: __sym("SDL_GetWindowSizeInPixels"), args: ["pointer", "pointer", "pointer"], returns: "void" });
export const SDL_SetWindowMinimumSize = CFunction({ ptr: __sym("SDL_SetWindowMinimumSize"), args: ["pointer", "i32", "i32"], returns: "void" });
export const SDL_GetWindowMinimumSize = CFunction({ ptr: __sym("SDL_GetWindowMinimumSize"), args: ["pointer", "pointer", "pointer"], returns: "void" });
export const SDL_SetWindowMaximumSize = CFunction({ ptr: __sym("SDL_SetWindowMaximumSize"), args: ["pointer", "i32", "i32"], returns: "void" });
export const SDL_GetWindowMaximumSize = CFunction({ ptr: __sym("SDL_GetWindowMaximumSize"), args: ["pointer", "pointer", "pointer"], returns: "void" });
export const SDL_SetWindowBordered = CFunction({ ptr: __sym("SDL_SetWindowBordered"), args: ["pointer", "i32"], returns: "void" });
export const SDL_SetWindowResizable = CFunction({ ptr: __sym("SDL_SetWindowResizable"), args: ["pointer", "i32"], returns: "void" });
export const SDL_SetWindowAlwaysOnTop = CFunction({ ptr: __sym("SDL_SetWindowAlwaysOnTop"), args: ["pointer", "i32"], returns: "void" });
export const SDL_ShowWindow = CFunction({ ptr: __sym("SDL_ShowWindow"), args: ["pointer"], returns: "void" });
export const SDL_HideWindow = CFunction({ ptr: __sym("SDL_HideWindow"), args: ["pointer"], returns: "void" });
export const SDL_RaiseWindow = CFunction({ ptr: __sym("SDL_RaiseWindow"), args: ["pointer"], returns: "void" });
export const SDL_MaximizeWindow = CFunction({ ptr: __sym("SDL_MaximizeWindow"), args: ["pointer"], returns: "void" });
export const SDL_MinimizeWindow = CFunction({ ptr: __sym("SDL_MinimizeWindow"), args: ["pointer"], returns: "void" });
export const SDL_RestoreWindow = CFunction({ ptr: __sym("SDL_RestoreWindow"), args: ["pointer"], returns: "void" });
export const SDL_SetWindowFullscreen = CFunction({ ptr: __sym("SDL_SetWindowFullscreen"), args: ["pointer", "u32"], returns: "i32" });
export const SDL_HasWindowSurface = CFunction({ ptr: __sym("SDL_HasWindowSurface"), args: ["pointer"], returns: "i32" });
export const SDL_GetWindowSurface = CFunction({ ptr: __sym("SDL_GetWindowSurface"), args: ["pointer"], returns: "pointer" });
export const SDL_UpdateWindowSurface = CFunction({ ptr: __sym("SDL_UpdateWindowSurface"), args: ["pointer"], returns: "i32" });
export const SDL_UpdateWindowSurfaceRects = CFunction({ ptr: __sym("SDL_UpdateWindowSurfaceRects"), args: ["pointer", "pointer", "i32"], returns: "i32" });
export const SDL_DestroyWindowSurface = CFunction({ ptr: __sym("SDL_DestroyWindowSurface"), args: ["pointer"], returns: "i32" });
export const SDL_SetWindowGrab = CFunction({ ptr: __sym("SDL_SetWindowGrab"), args: ["pointer", "i32"], returns: "void" });
export const SDL_SetWindowKeyboardGrab = CFunction({ ptr: __sym("SDL_SetWindowKeyboardGrab"), args: ["pointer", "i32"], returns: "void" });
export const SDL_SetWindowMouseGrab = CFunction({ ptr: __sym("SDL_SetWindowMouseGrab"), args: ["pointer", "i32"], returns: "void" });
export const SDL_GetWindowGrab = CFunction({ ptr: __sym("SDL_GetWindowGrab"), args: ["pointer"], returns: "i32" });
export const SDL_GetWindowKeyboardGrab = CFunction({ ptr: __sym("SDL_GetWindowKeyboardGrab"), args: ["pointer"], returns: "i32" });
export const SDL_GetWindowMouseGrab = CFunction({ ptr: __sym("SDL_GetWindowMouseGrab"), args: ["pointer"], returns: "i32" });
export const SDL_GetGrabbedWindow = CFunction({ ptr: __sym("SDL_GetGrabbedWindow"), args: [], returns: "pointer" });
export const SDL_SetWindowMouseRect = CFunction({ ptr: __sym("SDL_SetWindowMouseRect"), args: ["pointer", "pointer"], returns: "i32" });
export const SDL_GetWindowMouseRect = CFunction({ ptr: __sym("SDL_GetWindowMouseRect"), args: ["pointer"], returns: "pointer" });
export const SDL_SetWindowBrightness = CFunction({ ptr: __sym("SDL_SetWindowBrightness"), args: ["pointer", "f32"], returns: "i32" });
export const SDL_GetWindowBrightness = CFunction({ ptr: __sym("SDL_GetWindowBrightness"), args: ["pointer"], returns: "f32" });
export const SDL_SetWindowOpacity = CFunction({ ptr: __sym("SDL_SetWindowOpacity"), args: ["pointer", "f32"], returns: "i32" });
export const SDL_GetWindowOpacity = CFunction({ ptr: __sym("SDL_GetWindowOpacity"), args: ["pointer", "pointer"], returns: "i32" });
export const SDL_SetWindowModalFor = CFunction({ ptr: __sym("SDL_SetWindowModalFor"), args: ["pointer", "pointer"], returns: "i32" });
export const SDL_SetWindowInputFocus = CFunction({ ptr: __sym("SDL_SetWindowInputFocus"), args: ["pointer"], returns: "i32" });
export const SDL_SetWindowGammaRamp = CFunction({ ptr: __sym("SDL_SetWindowGammaRamp"), args: ["pointer", "pointer", "pointer", "pointer"], returns: "i32" });
export const SDL_GetWindowGammaRamp = CFunction({ ptr: __sym("SDL_GetWindowGammaRamp"), args: ["pointer", "pointer", "pointer", "pointer"], returns: "i32" });
export const SDL_SetWindowHitTest = CFunction({ ptr: __sym("SDL_SetWindowHitTest"), args: ["pointer", "function", "pointer"], returns: "i32" });
export const SDL_FlashWindow = CFunction({ ptr: __sym("SDL_FlashWindow"), args: ["pointer", "i32"], returns: "i32" });
export const SDL_DestroyWindow = CFunction({ ptr: __sym("SDL_DestroyWindow"), args: ["pointer"], returns: "void" });
export const SDL_IsScreenSaverEnabled = CFunction({ ptr: __sym("SDL_IsScreenSaverEnabled"), args: [], returns: "i32" });
export const SDL_EnableScreenSaver = CFunction({ ptr: __sym("SDL_EnableScreenSaver"), args: [], returns: "void" });
export const SDL_DisableScreenSaver = CFunction({ ptr: __sym("SDL_DisableScreenSaver"), args: [], returns: "void" });
export const SDL_GL_LoadLibrary = CFunction({ ptr: __sym("SDL_GL_LoadLibrary"), args: ["cstring"], returns: "i32" });
export const SDL_GL_GetProcAddress = CFunction({ ptr: __sym("SDL_GL_GetProcAddress"), args: ["cstring"], returns: "pointer" });
export const SDL_GL_UnloadLibrary = CFunction({ ptr: __sym("SDL_GL_UnloadLibrary"), args: [], returns: "void" });
export const SDL_GL_ExtensionSupported = CFunction({ ptr: __sym("SDL_GL_ExtensionSupported"), args: ["cstring"], returns: "i32" });
export const SDL_GL_ResetAttributes = CFunction({ ptr: __sym("SDL_GL_ResetAttributes"), args: [], returns: "void" });
export const SDL_GL_SetAttribute = CFunction({ ptr: __sym("SDL_GL_SetAttribute"), args: ["i32", "i32"], returns: "i32" });
export const SDL_GL_GetAttribute = CFunction({ ptr: __sym("SDL_GL_GetAttribute"), args: ["i32", "pointer"], returns: "i32" });
export const SDL_GL_CreateContext = CFunction({ ptr: __sym("SDL_GL_CreateContext"), args: ["pointer"], returns: "pointer" });
export const SDL_GL_MakeCurrent = CFunction({ ptr: __sym("SDL_GL_MakeCurrent"), args: ["pointer", "pointer"], returns: "i32" });
export const SDL_GL_GetCurrentWindow = CFunction({ ptr: __sym("SDL_GL_GetCurrentWindow"), args: [], returns: "pointer" });
export const SDL_GL_GetCurrentContext = CFunction({ ptr: __sym("SDL_GL_GetCurrentContext"), args: [], returns: "pointer" });
export const SDL_GL_GetDrawableSize = CFunction({ ptr: __sym("SDL_GL_GetDrawableSize"), args: ["pointer", "pointer", "pointer"], returns: "void" });
export const SDL_GL_SetSwapInterval = CFunction({ ptr: __sym("SDL_GL_SetSwapInterval"), args: ["i32"], returns: "i32" });
export const SDL_GL_GetSwapInterval = CFunction({ ptr: __sym("SDL_GL_GetSwapInterval"), args: [], returns: "i32" });
export const SDL_GL_SwapWindow = CFunction({ ptr: __sym("SDL_GL_SwapWindow"), args: ["pointer"], returns: "void" });
export const SDL_GL_DeleteContext = CFunction({ ptr: __sym("SDL_GL_DeleteContext"), args: ["pointer"], returns: "void" });
