/* Auto-generated by qjsm tools/gen-bindings.js from /usr/include/SDL2/SDL.h -- do not edit by hand.
 * Regenerate with:
 *   qjsm tools/gen-bindings.js --api=cfunction --library=libSDL2-2.0.so.0 -I/usr/include/SDL2 /usr/include/SDL2/SDL.h
 * (clang invocation used to build the AST: clang -Xclang -ast-dump=json -fsyntax-only -I/usr/include/SDL2 /usr/include/SDL2/SDL.h)
 */
import { CFunction, dlsym, dlopen, RTLD_NOW } from 'ffi';

const __lib = dlopen("libSDL2-2.0.so.0", RTLD_NOW);
if (__lib == null) throw new Error("gen-bindings: dlopen(libSDL2-2.0.so.0) failed");

function __sym(name) {
  const p = dlsym(__lib, name);
  if (p == null) throw new Error("gen-bindings: symbol not found: " + name);
  return p;
}

export const SDL_Init = CFunction({ ptr: __sym("SDL_Init"), args: ["u32"], returns: "i32" });
export const SDL_InitSubSystem = CFunction({ ptr: __sym("SDL_InitSubSystem"), args: ["u32"], returns: "i32" });
export const SDL_QuitSubSystem = CFunction({ ptr: __sym("SDL_QuitSubSystem"), args: ["u32"], returns: "void" });
export const SDL_WasInit = CFunction({ ptr: __sym("SDL_WasInit"), args: ["u32"], returns: "u32" });
export const SDL_Quit = CFunction({ ptr: __sym("SDL_Quit"), args: [], returns: "void" });
