/* Auto-generated by qjsm tools/gen-bindings.js from /usr/include/SDL2/SDL_surface.h -- do not edit by hand.
 * Regenerate with:
 *   qjsm tools/gen-bindings.js --api=cfunction --library=libSDL2-2.0.so.0 -I/usr/include/SDL2 /usr/include/SDL2/SDL_surface.h
 * (clang invocation used to build the AST: clang -Xclang -ast-dump=json -fsyntax-only -I/usr/include/SDL2 /usr/include/SDL2/SDL_surface.h)
 */
import { CFunction, dlsym, dlopen, RTLD_NOW } from 'ffi';

const __lib = dlopen("libSDL2-2.0.so.0", RTLD_NOW);
if (__lib == null) throw new Error("gen-bindings: dlopen(libSDL2-2.0.so.0) failed");

function __sym(name) {
  const p = dlsym(__lib, name);
  if (p == null) throw new Error("gen-bindings: symbol not found: " + name);
  return p;
}

// enum (anonymous)
export const SDL_FALSE = 0;
export const SDL_TRUE = 1;

// enum (anonymous)
export const SDL_BLENDMODE_NONE = 0;
export const SDL_BLENDMODE_BLEND = 1;
export const SDL_BLENDMODE_ADD = 2;
export const SDL_BLENDMODE_MOD = 4;
export const SDL_BLENDMODE_MUL = 8;
export const SDL_BLENDMODE_INVALID = 2147483647;

// enum (anonymous)
export const SDL_YUV_CONVERSION_JPEG = 0;
export const SDL_YUV_CONVERSION_BT601 = 1;
export const SDL_YUV_CONVERSION_BT709 = 2;
export const SDL_YUV_CONVERSION_AUTOMATIC = 3;

export const SDL_CreateRGBSurface = CFunction({ ptr: __sym("SDL_CreateRGBSurface"), args: ["u32", "i32", "i32", "i32", "u32", "u32", "u32", "u32"], returns: "pointer" });
export const SDL_CreateRGBSurfaceWithFormat = CFunction({ ptr: __sym("SDL_CreateRGBSurfaceWithFormat"), args: ["u32", "i32", "i32", "i32", "u32"], returns: "pointer" });
export const SDL_CreateRGBSurfaceFrom = CFunction({ ptr: __sym("SDL_CreateRGBSurfaceFrom"), args: ["pointer", "i32", "i32", "i32", "i32", "u32", "u32", "u32", "u32"], returns: "pointer" });
export const SDL_CreateRGBSurfaceWithFormatFrom = CFunction({ ptr: __sym("SDL_CreateRGBSurfaceWithFormatFrom"), args: ["pointer", "i32", "i32", "i32", "i32", "u32"], returns: "pointer" });
export const SDL_FreeSurface = CFunction({ ptr: __sym("SDL_FreeSurface"), args: ["pointer"], returns: "void" });
export const SDL_SetSurfacePalette = CFunction({ ptr: __sym("SDL_SetSurfacePalette"), args: ["pointer", "pointer"], returns: "i32" });
export const SDL_LockSurface = CFunction({ ptr: __sym("SDL_LockSurface"), args: ["pointer"], returns: "i32" });
export const SDL_UnlockSurface = CFunction({ ptr: __sym("SDL_UnlockSurface"), args: ["pointer"], returns: "void" });
export const SDL_LoadBMP_RW = CFunction({ ptr: __sym("SDL_LoadBMP_RW"), args: ["pointer", "i32"], returns: "pointer" });
export const SDL_SaveBMP_RW = CFunction({ ptr: __sym("SDL_SaveBMP_RW"), args: ["pointer", "pointer", "i32"], returns: "i32" });
export const SDL_SetSurfaceRLE = CFunction({ ptr: __sym("SDL_SetSurfaceRLE"), args: ["pointer", "i32"], returns: "i32" });
export const SDL_HasSurfaceRLE = CFunction({ ptr: __sym("SDL_HasSurfaceRLE"), args: ["pointer"], returns: "i32" });
export const SDL_SetColorKey = CFunction({ ptr: __sym("SDL_SetColorKey"), args: ["pointer", "i32", "u32"], returns: "i32" });
export const SDL_HasColorKey = CFunction({ ptr: __sym("SDL_HasColorKey"), args: ["pointer"], returns: "i32" });
export const SDL_GetColorKey = CFunction({ ptr: __sym("SDL_GetColorKey"), args: ["pointer", "pointer"], returns: "i32" });
export const SDL_SetSurfaceColorMod = CFunction({ ptr: __sym("SDL_SetSurfaceColorMod"), args: ["pointer", "u8", "u8", "u8"], returns: "i32" });
export const SDL_GetSurfaceColorMod = CFunction({ ptr: __sym("SDL_GetSurfaceColorMod"), args: ["pointer", "pointer", "pointer", "pointer"], returns: "i32" });
export const SDL_SetSurfaceAlphaMod = CFunction({ ptr: __sym("SDL_SetSurfaceAlphaMod"), args: ["pointer", "u8"], returns: "i32" });
export const SDL_GetSurfaceAlphaMod = CFunction({ ptr: __sym("SDL_GetSurfaceAlphaMod"), args: ["pointer", "pointer"], returns: "i32" });
export const SDL_SetSurfaceBlendMode = CFunction({ ptr: __sym("SDL_SetSurfaceBlendMode"), args: ["pointer", "i32"], returns: "i32" });
export const SDL_GetSurfaceBlendMode = CFunction({ ptr: __sym("SDL_GetSurfaceBlendMode"), args: ["pointer", "pointer"], returns: "i32" });
export const SDL_SetClipRect = CFunction({ ptr: __sym("SDL_SetClipRect"), args: ["pointer", "pointer"], returns: "i32" });
export const SDL_GetClipRect = CFunction({ ptr: __sym("SDL_GetClipRect"), args: ["pointer", "pointer"], returns: "void" });
export const SDL_DuplicateSurface = CFunction({ ptr: __sym("SDL_DuplicateSurface"), args: ["pointer"], returns: "pointer" });
export const SDL_ConvertSurface = CFunction({ ptr: __sym("SDL_ConvertSurface"), args: ["pointer", "pointer", "u32"], returns: "pointer" });
export const SDL_ConvertSurfaceFormat = CFunction({ ptr: __sym("SDL_ConvertSurfaceFormat"), args: ["pointer", "u32", "u32"], returns: "pointer" });
export const SDL_ConvertPixels = CFunction({ ptr: __sym("SDL_ConvertPixels"), args: ["i32", "i32", "u32", "pointer", "i32", "u32", "pointer", "i32"], returns: "i32" });
export const SDL_PremultiplyAlpha = CFunction({ ptr: __sym("SDL_PremultiplyAlpha"), args: ["i32", "i32", "u32", "pointer", "i32", "u32", "pointer", "i32"], returns: "i32" });
export const SDL_FillRect = CFunction({ ptr: __sym("SDL_FillRect"), args: ["pointer", "pointer", "u32"], returns: "i32" });
export const SDL_FillRects = CFunction({ ptr: __sym("SDL_FillRects"), args: ["pointer", "pointer", "i32", "u32"], returns: "i32" });
export const SDL_UpperBlit = CFunction({ ptr: __sym("SDL_UpperBlit"), args: ["pointer", "pointer", "pointer", "pointer"], returns: "i32" });
export const SDL_LowerBlit = CFunction({ ptr: __sym("SDL_LowerBlit"), args: ["pointer", "pointer", "pointer", "pointer"], returns: "i32" });
export const SDL_SoftStretch = CFunction({ ptr: __sym("SDL_SoftStretch"), args: ["pointer", "pointer", "pointer", "pointer"], returns: "i32" });
export const SDL_SoftStretchLinear = CFunction({ ptr: __sym("SDL_SoftStretchLinear"), args: ["pointer", "pointer", "pointer", "pointer"], returns: "i32" });
export const SDL_UpperBlitScaled = CFunction({ ptr: __sym("SDL_UpperBlitScaled"), args: ["pointer", "pointer", "pointer", "pointer"], returns: "i32" });
export const SDL_LowerBlitScaled = CFunction({ ptr: __sym("SDL_LowerBlitScaled"), args: ["pointer", "pointer", "pointer", "pointer"], returns: "i32" });
export const SDL_SetYUVConversionMode = CFunction({ ptr: __sym("SDL_SetYUVConversionMode"), args: ["i32"], returns: "void" });
export const SDL_GetYUVConversionMode = CFunction({ ptr: __sym("SDL_GetYUVConversionMode"), args: [], returns: "i32" });
export const SDL_GetYUVConversionModeForResolution = CFunction({ ptr: __sym("SDL_GetYUVConversionModeForResolution"), args: ["i32", "i32"], returns: "i32" });
