/* Auto-generated by qjsm tools/gen-bindings.js from /usr/include/SDL2/SDL_error.h -- do not edit by hand.
 * Regenerate with:
 *   qjsm tools/gen-bindings.js --api=cfunction --library=libSDL2-2.0.so.0 -I/usr/include/SDL2 /usr/include/SDL2/SDL_error.h
 * (clang invocation used to build the AST: clang -Xclang -ast-dump=json -fsyntax-only -I/usr/include/SDL2 /usr/include/SDL2/SDL_error.h)
 */
import { CFunction, dlsym, dlopen, RTLD_NOW } from 'ffi';

const __lib = dlopen("libSDL2-2.0.so.0", RTLD_NOW);
if (__lib == null) throw new Error("gen-bindings: dlopen(libSDL2-2.0.so.0) failed");

function __sym(name) {
  const p = dlsym(__lib, name);
  if (p == null) throw new Error("gen-bindings: symbol not found: " + name);
  return p;
}

export const SDL_GetError = CFunction({ ptr: __sym("SDL_GetError"), args: [], returns: "cstring" });
export const SDL_GetErrorMsg = CFunction({ ptr: __sym("SDL_GetErrorMsg"), args: ["cstring", "i32"], returns: "cstring" });
export const SDL_ClearError = CFunction({ ptr: __sym("SDL_ClearError"), args: [], returns: "void" });

// Skipped (unsupported):
//   - SDL_SetError: variadic functions are not supported
//   - SDL_Error: parameter code (SDL_errorcode): unrecognized C type "SDL_errorcode"
