/* Auto-generated by qjsm tools/gen-bindings.js from /usr/include/zlib.h -- do not edit by hand.
 * Regenerate with:
 *   qjsm tools/gen-bindings.js --api=cfunction --library=libz.so.1 --ffitype  /usr/include/zlib.h
 * (clang invocation used to build the AST, once per source: clang -Xclang -ast-dump=json -fsyntax-only <source>)
 */
import { CFunction, FFIType, dlsym, dlopen, RTLD_NOW } from 'ffi';

const __lib = dlopen("libz.so.1", RTLD_NOW);
if (__lib == null) throw new Error("gen-bindings: dlopen(libz.so.1) failed");

function __sym(name) {
  const p = dlsym(__lib, name);
  if (p == null) throw new Error("gen-bindings: symbol not found: " + name);
  return p;
}

export const zlibVersion = CFunction({ ptr: __sym("zlibVersion"), args: [], returns: FFIType.cstring });
export const deflate = CFunction({ ptr: __sym("deflate"), args: [FFIType.pointer, FFIType.i32], returns: FFIType.i32 });
export const deflateEnd = CFunction({ ptr: __sym("deflateEnd"), args: [FFIType.pointer], returns: FFIType.i32 });
export const inflate = CFunction({ ptr: __sym("inflate"), args: [FFIType.pointer, FFIType.i32], returns: FFIType.i32 });
export const inflateEnd = CFunction({ ptr: __sym("inflateEnd"), args: [FFIType.pointer], returns: FFIType.i32 });
export const deflateSetDictionary = CFunction({ ptr: __sym("deflateSetDictionary"), args: [FFIType.pointer, FFIType.pointer, FFIType.u32], returns: FFIType.i32 });
export const deflateGetDictionary = CFunction({ ptr: __sym("deflateGetDictionary"), args: [FFIType.pointer, FFIType.pointer, FFIType.pointer], returns: FFIType.i32 });
export const deflateCopy = CFunction({ ptr: __sym("deflateCopy"), args: [FFIType.pointer, FFIType.pointer], returns: FFIType.i32 });
export const deflateReset = CFunction({ ptr: __sym("deflateReset"), args: [FFIType.pointer], returns: FFIType.i32 });
export const deflateParams = CFunction({ ptr: __sym("deflateParams"), args: [FFIType.pointer, FFIType.i32, FFIType.i32], returns: FFIType.i32 });
export const deflateTune = CFunction({ ptr: __sym("deflateTune"), args: [FFIType.pointer, FFIType.i32, FFIType.i32, FFIType.i32, FFIType.i32], returns: FFIType.i32 });
export const deflateBound = CFunction({ ptr: __sym("deflateBound"), args: [FFIType.pointer, FFIType.u64], returns: FFIType.u64 });
export const deflatePending = CFunction({ ptr: __sym("deflatePending"), args: [FFIType.pointer, FFIType.pointer, FFIType.pointer], returns: FFIType.i32 });
export const deflatePrime = CFunction({ ptr: __sym("deflatePrime"), args: [FFIType.pointer, FFIType.i32, FFIType.i32], returns: FFIType.i32 });
export const deflateSetHeader = CFunction({ ptr: __sym("deflateSetHeader"), args: [FFIType.pointer, FFIType.pointer], returns: FFIType.i32 });
export const inflateSetDictionary = CFunction({ ptr: __sym("inflateSetDictionary"), args: [FFIType.pointer, FFIType.pointer, FFIType.u32], returns: FFIType.i32 });
export const inflateGetDictionary = CFunction({ ptr: __sym("inflateGetDictionary"), args: [FFIType.pointer, FFIType.pointer, FFIType.pointer], returns: FFIType.i32 });
export const inflateSync = CFunction({ ptr: __sym("inflateSync"), args: [FFIType.pointer], returns: FFIType.i32 });
export const inflateCopy = CFunction({ ptr: __sym("inflateCopy"), args: [FFIType.pointer, FFIType.pointer], returns: FFIType.i32 });
export const inflateReset = CFunction({ ptr: __sym("inflateReset"), args: [FFIType.pointer], returns: FFIType.i32 });
export const inflateReset2 = CFunction({ ptr: __sym("inflateReset2"), args: [FFIType.pointer, FFIType.i32], returns: FFIType.i32 });
export const inflatePrime = CFunction({ ptr: __sym("inflatePrime"), args: [FFIType.pointer, FFIType.i32, FFIType.i32], returns: FFIType.i32 });
export const inflateMark = CFunction({ ptr: __sym("inflateMark"), args: [FFIType.pointer], returns: FFIType.i64 });
export const inflateGetHeader = CFunction({ ptr: __sym("inflateGetHeader"), args: [FFIType.pointer, FFIType.pointer], returns: FFIType.i32 });
export const inflateBack = CFunction({ ptr: __sym("inflateBack"), args: [FFIType.pointer, FFIType.function, FFIType.pointer, FFIType.function, FFIType.pointer], returns: FFIType.i32 });
export const inflateBackEnd = CFunction({ ptr: __sym("inflateBackEnd"), args: [FFIType.pointer], returns: FFIType.i32 });
export const zlibCompileFlags = CFunction({ ptr: __sym("zlibCompileFlags"), args: [], returns: FFIType.u64 });
export const compress = CFunction({ ptr: __sym("compress"), args: [FFIType.pointer, FFIType.pointer, FFIType.pointer, FFIType.u64], returns: FFIType.i32 });
export const compress2 = CFunction({ ptr: __sym("compress2"), args: [FFIType.pointer, FFIType.pointer, FFIType.pointer, FFIType.u64, FFIType.i32], returns: FFIType.i32 });
export const compressBound = CFunction({ ptr: __sym("compressBound"), args: [FFIType.u64], returns: FFIType.u64 });
export const uncompress = CFunction({ ptr: __sym("uncompress"), args: [FFIType.pointer, FFIType.pointer, FFIType.pointer, FFIType.u64], returns: FFIType.i32 });
export const uncompress2 = CFunction({ ptr: __sym("uncompress2"), args: [FFIType.pointer, FFIType.pointer, FFIType.pointer, FFIType.pointer], returns: FFIType.i32 });
export const gzdopen = CFunction({ ptr: __sym("gzdopen"), args: [FFIType.i32, FFIType.cstring], returns: FFIType.pointer });
export const gzbuffer = CFunction({ ptr: __sym("gzbuffer"), args: [FFIType.pointer, FFIType.u32], returns: FFIType.i32 });
export const gzsetparams = CFunction({ ptr: __sym("gzsetparams"), args: [FFIType.pointer, FFIType.i32, FFIType.i32], returns: FFIType.i32 });
export const gzread = CFunction({ ptr: __sym("gzread"), args: [FFIType.pointer, FFIType.pointer, FFIType.u32], returns: FFIType.i32 });
export const gzfread = CFunction({ ptr: __sym("gzfread"), args: [FFIType.pointer, FFIType.u64, FFIType.u64, FFIType.pointer], returns: FFIType.u64 });
export const gzwrite = CFunction({ ptr: __sym("gzwrite"), args: [FFIType.pointer, FFIType.pointer, FFIType.u32], returns: FFIType.i32 });
export const gzfwrite = CFunction({ ptr: __sym("gzfwrite"), args: [FFIType.pointer, FFIType.u64, FFIType.u64, FFIType.pointer], returns: FFIType.u64 });
export const gzputs = CFunction({ ptr: __sym("gzputs"), args: [FFIType.pointer, FFIType.cstring], returns: FFIType.i32 });
export const gzgets = CFunction({ ptr: __sym("gzgets"), args: [FFIType.pointer, FFIType.cstring, FFIType.i32], returns: FFIType.cstring });
export const gzputc = CFunction({ ptr: __sym("gzputc"), args: [FFIType.pointer, FFIType.i32], returns: FFIType.i32 });
export const gzgetc = CFunction({ ptr: __sym("gzgetc"), args: [FFIType.pointer], returns: FFIType.i32 });
export const gzungetc = CFunction({ ptr: __sym("gzungetc"), args: [FFIType.i32, FFIType.pointer], returns: FFIType.i32 });
export const gzflush = CFunction({ ptr: __sym("gzflush"), args: [FFIType.pointer, FFIType.i32], returns: FFIType.i32 });
export const gzrewind = CFunction({ ptr: __sym("gzrewind"), args: [FFIType.pointer], returns: FFIType.i32 });
export const gzeof = CFunction({ ptr: __sym("gzeof"), args: [FFIType.pointer], returns: FFIType.i32 });
export const gzdirect = CFunction({ ptr: __sym("gzdirect"), args: [FFIType.pointer], returns: FFIType.i32 });
export const gzclose = CFunction({ ptr: __sym("gzclose"), args: [FFIType.pointer], returns: FFIType.i32 });
export const gzclose_r = CFunction({ ptr: __sym("gzclose_r"), args: [FFIType.pointer], returns: FFIType.i32 });
export const gzclose_w = CFunction({ ptr: __sym("gzclose_w"), args: [FFIType.pointer], returns: FFIType.i32 });
export const gzerror = CFunction({ ptr: __sym("gzerror"), args: [FFIType.pointer, FFIType.pointer], returns: FFIType.cstring });
export const gzclearerr = CFunction({ ptr: __sym("gzclearerr"), args: [FFIType.pointer], returns: FFIType.void });
export const adler32 = CFunction({ ptr: __sym("adler32"), args: [FFIType.u64, FFIType.pointer, FFIType.u32], returns: FFIType.u64 });
export const adler32_z = CFunction({ ptr: __sym("adler32_z"), args: [FFIType.u64, FFIType.pointer, FFIType.u64], returns: FFIType.u64 });
export const crc32 = CFunction({ ptr: __sym("crc32"), args: [FFIType.u64, FFIType.pointer, FFIType.u32], returns: FFIType.u64 });
export const crc32_z = CFunction({ ptr: __sym("crc32_z"), args: [FFIType.u64, FFIType.pointer, FFIType.u64], returns: FFIType.u64 });
export const crc32_combine_op = CFunction({ ptr: __sym("crc32_combine_op"), args: [FFIType.u64, FFIType.u64, FFIType.u64], returns: FFIType.u64 });
export const deflateInit_ = CFunction({ ptr: __sym("deflateInit_"), args: [FFIType.pointer, FFIType.i32, FFIType.cstring, FFIType.i32], returns: FFIType.i32 });
export const inflateInit_ = CFunction({ ptr: __sym("inflateInit_"), args: [FFIType.pointer, FFIType.cstring, FFIType.i32], returns: FFIType.i32 });
export const deflateInit2_ = CFunction({ ptr: __sym("deflateInit2_"), args: [FFIType.pointer, FFIType.i32, FFIType.i32, FFIType.i32, FFIType.i32, FFIType.i32, FFIType.cstring, FFIType.i32], returns: FFIType.i32 });
export const inflateInit2_ = CFunction({ ptr: __sym("inflateInit2_"), args: [FFIType.pointer, FFIType.i32, FFIType.cstring, FFIType.i32], returns: FFIType.i32 });
export const inflateBackInit_ = CFunction({ ptr: __sym("inflateBackInit_"), args: [FFIType.pointer, FFIType.i32, FFIType.pointer, FFIType.cstring, FFIType.i32], returns: FFIType.i32 });
export const gzgetc_ = CFunction({ ptr: __sym("gzgetc_"), args: [FFIType.pointer], returns: FFIType.i32 });
export const gzopen = CFunction({ ptr: __sym("gzopen"), args: [FFIType.cstring, FFIType.cstring], returns: FFIType.pointer });
export const gzseek = CFunction({ ptr: __sym("gzseek"), args: [FFIType.pointer, FFIType.i64, FFIType.i32], returns: FFIType.i64 });
export const gztell = CFunction({ ptr: __sym("gztell"), args: [FFIType.pointer], returns: FFIType.i64 });
export const gzoffset = CFunction({ ptr: __sym("gzoffset"), args: [FFIType.pointer], returns: FFIType.i64 });
export const adler32_combine = CFunction({ ptr: __sym("adler32_combine"), args: [FFIType.u64, FFIType.u64, FFIType.i64], returns: FFIType.u64 });
export const crc32_combine = CFunction({ ptr: __sym("crc32_combine"), args: [FFIType.u64, FFIType.u64, FFIType.i64], returns: FFIType.u64 });
export const crc32_combine_gen = CFunction({ ptr: __sym("crc32_combine_gen"), args: [FFIType.i64], returns: FFIType.u64 });
export const zError = CFunction({ ptr: __sym("zError"), args: [FFIType.i32], returns: FFIType.cstring });
export const inflateSyncPoint = CFunction({ ptr: __sym("inflateSyncPoint"), args: [FFIType.pointer], returns: FFIType.i32 });
export const get_crc_table = CFunction({ ptr: __sym("get_crc_table"), args: [], returns: FFIType.pointer });
export const inflateUndermine = CFunction({ ptr: __sym("inflateUndermine"), args: [FFIType.pointer, FFIType.i32], returns: FFIType.i32 });
export const inflateValidate = CFunction({ ptr: __sym("inflateValidate"), args: [FFIType.pointer, FFIType.i32], returns: FFIType.i32 });
export const inflateCodesUsed = CFunction({ ptr: __sym("inflateCodesUsed"), args: [FFIType.pointer], returns: FFIType.u64 });
export const inflateResetKeep = CFunction({ ptr: __sym("inflateResetKeep"), args: [FFIType.pointer], returns: FFIType.i32 });
export const deflateResetKeep = CFunction({ ptr: __sym("deflateResetKeep"), args: [FFIType.pointer], returns: FFIType.i32 });
export const gzvprintf = CFunction({ ptr: __sym("gzvprintf"), args: [FFIType.pointer, FFIType.cstring, FFIType.pointer], returns: FFIType.i32 });

// Skipped (unsupported):
//   - gzprintf: variadic functions are not supported
