/* Auto-generated by qjsm tools/gen-bindings.js from /usr/include/zlib.h -- do not edit by hand.
 * Regenerate with:
 *   qjsm tools/gen-bindings.js --api=cfunction --library=libz.so.1 --structs --jsdoc  /usr/include/zlib.h
 * (clang invocation used to build the AST, once per source: clang -Xclang -ast-dump=json -fsyntax-only <source>)
 */
import { CFunction, toArrayBuffer, ptr as __ptr, toString as __cstr, dlsym, dlopen, RTLD_NOW } from 'ffi';

const __lib = dlopen("libz.so.1", RTLD_NOW);
if (__lib == null) throw new Error("gen-bindings: dlopen(libz.so.1) failed");

function __sym(name) {
  const p = dlsym(__lib, name);
  if(p == null) throw new Error("gen-bindings: symbol not found: " + name);
  return p;
}

const __dvs = new WeakMap();

function __dv(o) {
  let d = __dvs.get(o);
  if(!d) __dvs.set(o, (d = new DataView(o)));
  return d;
}

function __ptrOut(v) {
  return v === 0n ? null : v <= 0xffffffffn ? Number(v) : v;
}

function __ptrIn(v) {
  return v === null || v === undefined ? 0n : typeof v === "object" ? BigInt(v.ptr !== undefined ? v.ptr : __ptr(v)) : BigInt(v);
}

const __index = /^(0|[1-9]\d*)$/;

function __ptrArray(a, wrap) {
  const at = i => {
    const p = a[i];
    return p === 0n ? null : wrap ? wrap(p) : __ptrOut(p);
  };

  return new Proxy(a, {
    get(t, k) {
      if(typeof k === "string" && __index.test(k)) return Number(k) < t.length ? at(Number(k)) : undefined;
      if(k === Symbol.iterator) return function*() { for(let i = 0; i < t.length; i++) yield at(i); };

      const v = Reflect.get(t, k, t);
      return typeof v === "function" ? v.bind(t) : v;
    },
    set(t, k, v) {
      if(typeof k === "string" && __index.test(k)) {
        if(Number(k) >= t.length) return false;
        t[k] = __ptrIn(v);
        return true;
      }
      return Reflect.set(t, k, v, t);
    },
  });
}

function __bytes(v) {
  return ArrayBuffer.isView(v) ? new Uint8Array(v.buffer, v.byteOffset, v.byteLength) : new Uint8Array(v);
}

function __view(cls, p, size, owner) {
  const b = toArrayBuffer(BigInt(p), size, false);

  Object.setPrototypeOf(b, cls.prototype);
  if(owner) Object.defineProperty(b, "__owner", { value: owner });
  return b;
}

const __sizes = { bool: 1, i8: 1, u8: 1, i16: 2, u16: 2, i32: 4, u32: 4, i64: 8, u64: 8, i64_fast: 8, u64_fast: 8, f32: 4, f64: 8, pointer: 8, ptr: 8, function: 8, cstring: 8 };

/* A type spelled "T *" is a pointer, whatever T is. */
function __sz(type) {
  return __sizes[type.endsWith("*") ? "pointer" : type];
}

function __read(dv, type, off) {
  if(type.endsWith("*")) type = "pointer";
  switch(type) {
    case "bool": return dv.getUint8(off) !== 0;
    case "i8": return dv.getInt8(off);
    case "u8": return dv.getUint8(off);
    case "i16": return dv.getInt16(off, true);
    case "u16": return dv.getUint16(off, true);
    case "i32": return dv.getInt32(off, true);
    case "u32": return dv.getUint32(off, true);
    case "i64": return dv.getBigInt64(off, true);
    case "u64": return dv.getBigUint64(off, true);
    case "i64_fast": return Number(dv.getBigInt64(off, true));
    case "u64_fast": return Number(dv.getBigUint64(off, true));
    case "f32": return dv.getFloat32(off, true);
    case "f64": return dv.getFloat64(off, true);
    case "pointer": case "ptr": case "function": return __ptrOut(dv.getBigUint64(off, true));
    case "cstring": { const p = __ptrOut(dv.getBigUint64(off, true)); return p === null ? null : __cstr(p); }
  }
}

function __write(dv, type, off, v) {
  if(type.endsWith("*")) type = "pointer";
  switch(type) {
    case "bool": return dv.setUint8(off, v ? 1 : 0);
    case "i8": return dv.setInt8(off, v);
    case "u8": return dv.setUint8(off, v);
    case "i16": return dv.setInt16(off, v, true);
    case "u16": return dv.setUint16(off, v, true);
    case "i32": return dv.setInt32(off, v, true);
    case "u32": return dv.setUint32(off, v, true);
    case "i64": case "i64_fast": return dv.setBigInt64(off, BigInt(v), true);
    case "u64": case "u64_fast": case "pointer": case "ptr": case "function": return dv.setBigUint64(off, v === null ? 0n : BigInt(v), true);
    case "f32": return dv.setFloat32(off, v, true);
    case "f64": return dv.setFloat64(off, v, true);
  }
  throw new TypeError("cannot write a " + type + " field");
}

function __variable(name, type) {
  const v = { get ptr() { return __sym(name); } };
  if(__sz(type) !== undefined) {
    const dv = () => new DataView(toArrayBuffer(__sym(name), __sz(type), false));
    Object.defineProperty(v, "value", { enumerable: true, get: () => __read(dv(), type, 0), set: x => __write(dv(), type, 0, x) });
  }
  return v;
}

function __ret(cls, f) {
  return (...args) => Object.setPrototypeOf(f(...args), cls.prototype);
}

// classes and structs

/* struct z_stream_s, 112 bytes (line 86) */
/**
 * struct z_stream_s, 112 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=112] - a byte length, or bytes to copy
 * @property {number|bigint|null} next_in - Bytef *, offset 0
 * @property {number} avail_in - uInt, offset 8
 * @property {bigint} total_in - uLong, offset 16
 * @property {number|bigint|null} next_out - Bytef *, offset 24
 * @property {number} avail_out - uInt, offset 32
 * @property {bigint} total_out - uLong, offset 40
 * @property {number|bigint|null} msg - char *, offset 48
 * @property {number|bigint|null} state - struct internal_state *, offset 56
 * @property {number|bigint|null} zalloc - alloc_func, offset 64
 * @property {number|bigint|null} zfree - free_func, offset 72
 * @property {Uint8Array} opaque - voidpf, offset 80
 * @property {number} data_type - int, offset 88
 * @property {bigint} adler - uLong, offset 96
 * @property {bigint} reserved - uLong, offset 104
 */
export class z_stream_s extends ArrayBuffer {
  constructor(init = 112) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 112) { return __view(z_stream_s, p, size, owner); }
  get ptr() { return __ptr(this); }
  get next_in() { return __ptrOut(__dv(this).getBigUint64(0, true)); }
  set next_in(v) { __dv(this).setBigUint64(0, __ptrIn(v), true); }
  get avail_in() { return __dv(this).getUint32(8, true); }
  set avail_in(v) { __dv(this).setUint32(8, v, true); }
  get total_in() { return __dv(this).getBigUint64(16, true); }
  set total_in(v) { __dv(this).setBigUint64(16, BigInt(v), true); }
  get next_out() { return __ptrOut(__dv(this).getBigUint64(24, true)); }
  set next_out(v) { __dv(this).setBigUint64(24, __ptrIn(v), true); }
  get avail_out() { return __dv(this).getUint32(32, true); }
  set avail_out(v) { __dv(this).setUint32(32, v, true); }
  get total_out() { return __dv(this).getBigUint64(40, true); }
  set total_out(v) { __dv(this).setBigUint64(40, BigInt(v), true); }
  get msg() { return __ptrOut(__dv(this).getBigUint64(48, true)); }
  set msg(v) { __dv(this).setBigUint64(48, __ptrIn(v), true); }
  get state() { return __ptrOut(__dv(this).getBigUint64(56, true)); }
  set state(v) { __dv(this).setBigUint64(56, __ptrIn(v), true); }
  get zalloc() { return __ptrOut(__dv(this).getBigUint64(64, true)); }
  set zalloc(v) { __dv(this).setBigUint64(64, __ptrIn(v), true); }
  get zfree() { return __ptrOut(__dv(this).getBigUint64(72, true)); }
  set zfree(v) { __dv(this).setBigUint64(72, __ptrIn(v), true); }
  get opaque() { return new Uint8Array(this, 80, 8); }
  set opaque(v) { new Uint8Array(this, 80, 8).set(__bytes(v)); }
  get data_type() { return __dv(this).getInt32(88, true); }
  set data_type(v) { __dv(this).setInt32(88, v, true); }
  get adler() { return __dv(this).getBigUint64(96, true); }
  set adler(v) { __dv(this).setBigUint64(96, BigInt(v), true); }
  get reserved() { return __dv(this).getBigUint64(104, true); }
  set reserved(v) { __dv(this).setBigUint64(104, BigInt(v), true); }
}
z_stream_s.size = 112;
z_stream_s.align = 8;
z_stream_s.fields = {next_in:{type:'Bytef *',offset:0},avail_in:{type:'u32',offset:8},total_in:{type:'u64',offset:16},next_out:{type:'Bytef *',offset:24},avail_out:{type:'u32',offset:32},total_out:{type:'u64',offset:40},msg:{type:'cstring',offset:48},state:{type:'struct internal_state *',offset:56},zalloc:{type:'function',offset:64},zfree:{type:'function',offset:72},opaque:{type:'void *',offset:80},data_type:{type:'i32',offset:88},adler:{type:'u64',offset:96},reserved:{type:'u64',offset:104}};

/* struct gz_header_s, 80 bytes (line 114) */
/**
 * struct gz_header_s, 80 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=80] - a byte length, or bytes to copy
 * @property {number} text - int, offset 0
 * @property {bigint} time - uLong, offset 8
 * @property {number} xflags - int, offset 16
 * @property {number} os - int, offset 20
 * @property {number|bigint|null} extra - Bytef *, offset 24
 * @property {number} extra_len - uInt, offset 32
 * @property {number} extra_max - uInt, offset 36
 * @property {number|bigint|null} name - Bytef *, offset 40
 * @property {number} name_max - uInt, offset 48
 * @property {number|bigint|null} comment - Bytef *, offset 56
 * @property {number} comm_max - uInt, offset 64
 * @property {number} hcrc - int, offset 68
 * @property {number} done - int, offset 72
 */
export class gz_header_s extends ArrayBuffer {
  constructor(init = 80) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 80) { return __view(gz_header_s, p, size, owner); }
  get ptr() { return __ptr(this); }
  get text() { return __dv(this).getInt32(0, true); }
  set text(v) { __dv(this).setInt32(0, v, true); }
  get time() { return __dv(this).getBigUint64(8, true); }
  set time(v) { __dv(this).setBigUint64(8, BigInt(v), true); }
  get xflags() { return __dv(this).getInt32(16, true); }
  set xflags(v) { __dv(this).setInt32(16, v, true); }
  get os() { return __dv(this).getInt32(20, true); }
  set os(v) { __dv(this).setInt32(20, v, true); }
  get extra() { return __ptrOut(__dv(this).getBigUint64(24, true)); }
  set extra(v) { __dv(this).setBigUint64(24, __ptrIn(v), true); }
  get extra_len() { return __dv(this).getUint32(32, true); }
  set extra_len(v) { __dv(this).setUint32(32, v, true); }
  get extra_max() { return __dv(this).getUint32(36, true); }
  set extra_max(v) { __dv(this).setUint32(36, v, true); }
  get name() { return __ptrOut(__dv(this).getBigUint64(40, true)); }
  set name(v) { __dv(this).setBigUint64(40, __ptrIn(v), true); }
  get name_max() { return __dv(this).getUint32(48, true); }
  set name_max(v) { __dv(this).setUint32(48, v, true); }
  get comment() { return __ptrOut(__dv(this).getBigUint64(56, true)); }
  set comment(v) { __dv(this).setBigUint64(56, __ptrIn(v), true); }
  get comm_max() { return __dv(this).getUint32(64, true); }
  set comm_max(v) { __dv(this).setUint32(64, v, true); }
  get hcrc() { return __dv(this).getInt32(68, true); }
  set hcrc(v) { __dv(this).setInt32(68, v, true); }
  get done() { return __dv(this).getInt32(72, true); }
  set done(v) { __dv(this).setInt32(72, v, true); }
}
gz_header_s.size = 80;
gz_header_s.align = 8;
gz_header_s.fields = {text:{type:'i32',offset:0},time:{type:'u64',offset:8},xflags:{type:'i32',offset:16},os:{type:'i32',offset:20},extra:{type:'Bytef *',offset:24},extra_len:{type:'u32',offset:32},extra_max:{type:'u32',offset:36},name:{type:'Bytef *',offset:40},name_max:{type:'u32',offset:48},comment:{type:'Bytef *',offset:56},comm_max:{type:'u32',offset:64},hcrc:{type:'i32',offset:68},done:{type:'i32',offset:72}};

/* struct gzFile_s, 24 bytes (line 1837) */
/**
 * struct gzFile_s, 24 bytes
 * @extends {ArrayBuffer}
 * @param {number|ArrayBuffer|ArrayBufferView} [init=24] - a byte length, or bytes to copy
 * @property {number} have - unsigned int, offset 0
 * @property {number|bigint|null} next - unsigned char *, offset 8
 * @property {bigint} pos - off_t, offset 16
 */
export class gzFile_s extends ArrayBuffer {
  constructor(init = 24) { super(typeof init === 'number' ? init : init.byteLength); if(typeof init !== 'number') new Uint8Array(this).set(__bytes(init)); }
  static at(p, owner, size = 24) { return __view(gzFile_s, p, size, owner); }
  get ptr() { return __ptr(this); }
  get have() { return __dv(this).getUint32(0, true); }
  set have(v) { __dv(this).setUint32(0, v, true); }
  get next() { return __ptrOut(__dv(this).getBigUint64(8, true)); }
  set next(v) { __dv(this).setBigUint64(8, __ptrIn(v), true); }
  get pos() { return __dv(this).getBigInt64(16, true); }
  set pos(v) { __dv(this).setBigInt64(16, BigInt(v), true); }
}
gzFile_s.size = 24;
gzFile_s.align = 8;
gzFile_s.fields = {have:{type:'u32',offset:0},next:{type:'unsigned char *',offset:8},pos:{type:'i64',offset:16}};

export const z_stream = z_stream_s;
export const gz_header = gz_header_s;

/**
 * zlibVersion
 * @returns {string} - cstring
 */
export const zlibVersion = CFunction({ptr:__sym('zlibVersion'),args:[],returns:'cstring'});
/**
 * deflate
 * @param {object|number|bigint|null} strm - z_stream *
 * @param {number} flush - i32
 * @returns {number} - i32
 */
export const deflate = CFunction({ptr:__sym('deflate'),args:['z_stream *','i32'],returns:'i32'});
/**
 * deflateEnd
 * @param {object|number|bigint|null} strm - z_stream *
 * @returns {number} - i32
 */
export const deflateEnd = CFunction({ptr:__sym('deflateEnd'),args:['z_stream *'],returns:'i32'});
/**
 * inflate
 * @param {object|number|bigint|null} strm - z_stream *
 * @param {number} flush - i32
 * @returns {number} - i32
 */
export const inflate = CFunction({ptr:__sym('inflate'),args:['z_stream *','i32'],returns:'i32'});
/**
 * inflateEnd
 * @param {object|number|bigint|null} strm - z_stream *
 * @returns {number} - i32
 */
export const inflateEnd = CFunction({ptr:__sym('inflateEnd'),args:['z_stream *'],returns:'i32'});
/**
 * deflateSetDictionary
 * @param {object|number|bigint|null} strm - z_stream *
 * @param {object|number|bigint|null} dictionary - Bytef *
 * @param {number} dictLength - u32
 * @returns {number} - i32
 */
export const deflateSetDictionary = CFunction({ptr:__sym('deflateSetDictionary'),args:['z_stream *','Bytef *','u32'],returns:'i32'});
/**
 * deflateGetDictionary
 * @param {object|number|bigint|null} strm - z_stream *
 * @param {object|number|bigint|null} dictionary - Bytef *
 * @param {object|number|bigint|null} dictLength - uInt *
 * @returns {number} - i32
 */
export const deflateGetDictionary = CFunction({ptr:__sym('deflateGetDictionary'),args:['z_stream *','Bytef *','uInt *'],returns:'i32'});
/**
 * deflateCopy
 * @param {object|number|bigint|null} dest - z_stream *
 * @param {object|number|bigint|null} source - z_stream *
 * @returns {number} - i32
 */
export const deflateCopy = CFunction({ptr:__sym('deflateCopy'),args:['z_stream *','z_stream *'],returns:'i32'});
/**
 * deflateReset
 * @param {object|number|bigint|null} strm - z_stream *
 * @returns {number} - i32
 */
export const deflateReset = CFunction({ptr:__sym('deflateReset'),args:['z_stream *'],returns:'i32'});
/**
 * deflateParams
 * @param {object|number|bigint|null} strm - z_stream *
 * @param {number} level - i32
 * @param {number} strategy - i32
 * @returns {number} - i32
 */
export const deflateParams = CFunction({ptr:__sym('deflateParams'),args:['z_stream *','i32','i32'],returns:'i32'});
/**
 * deflateTune
 * @param {object|number|bigint|null} strm - z_stream *
 * @param {number} good_length - i32
 * @param {number} max_lazy - i32
 * @param {number} nice_length - i32
 * @param {number} max_chain - i32
 * @returns {number} - i32
 */
export const deflateTune = CFunction({ptr:__sym('deflateTune'),args:['z_stream *','i32','i32','i32','i32'],returns:'i32'});
/**
 * deflateBound
 * @param {object|number|bigint|null} strm - z_stream *
 * @param {bigint|number} sourceLen - u64
 * @returns {bigint} - u64
 */
export const deflateBound = CFunction({ptr:__sym('deflateBound'),args:['z_stream *','u64'],returns:'u64'});
/**
 * deflatePending
 * @param {object|number|bigint|null} strm - z_stream *
 * @param {object|number|bigint|null} pending - unsigned int *
 * @param {object|number|bigint|null} bits - int *
 * @returns {number} - i32
 */
export const deflatePending = CFunction({ptr:__sym('deflatePending'),args:['z_stream *','unsigned int *','int *'],returns:'i32'});
/**
 * deflatePrime
 * @param {object|number|bigint|null} strm - z_stream *
 * @param {number} bits - i32
 * @param {number} value - i32
 * @returns {number} - i32
 */
export const deflatePrime = CFunction({ptr:__sym('deflatePrime'),args:['z_stream *','i32','i32'],returns:'i32'});
/**
 * deflateSetHeader
 * @param {object|number|bigint|null} strm - z_stream *
 * @param {object|number|bigint|null} head - gz_header *
 * @returns {number} - i32
 */
export const deflateSetHeader = CFunction({ptr:__sym('deflateSetHeader'),args:['z_stream *','gz_header *'],returns:'i32'});
/**
 * inflateSetDictionary
 * @param {object|number|bigint|null} strm - z_stream *
 * @param {object|number|bigint|null} dictionary - Bytef *
 * @param {number} dictLength - u32
 * @returns {number} - i32
 */
export const inflateSetDictionary = CFunction({ptr:__sym('inflateSetDictionary'),args:['z_stream *','Bytef *','u32'],returns:'i32'});
/**
 * inflateGetDictionary
 * @param {object|number|bigint|null} strm - z_stream *
 * @param {object|number|bigint|null} dictionary - Bytef *
 * @param {object|number|bigint|null} dictLength - uInt *
 * @returns {number} - i32
 */
export const inflateGetDictionary = CFunction({ptr:__sym('inflateGetDictionary'),args:['z_stream *','Bytef *','uInt *'],returns:'i32'});
/**
 * inflateSync
 * @param {object|number|bigint|null} strm - z_stream *
 * @returns {number} - i32
 */
export const inflateSync = CFunction({ptr:__sym('inflateSync'),args:['z_stream *'],returns:'i32'});
/**
 * inflateCopy
 * @param {object|number|bigint|null} dest - z_stream *
 * @param {object|number|bigint|null} source - z_stream *
 * @returns {number} - i32
 */
export const inflateCopy = CFunction({ptr:__sym('inflateCopy'),args:['z_stream *','z_stream *'],returns:'i32'});
/**
 * inflateReset
 * @param {object|number|bigint|null} strm - z_stream *
 * @returns {number} - i32
 */
export const inflateReset = CFunction({ptr:__sym('inflateReset'),args:['z_stream *'],returns:'i32'});
/**
 * inflateReset2
 * @param {object|number|bigint|null} strm - z_stream *
 * @param {number} windowBits - i32
 * @returns {number} - i32
 */
export const inflateReset2 = CFunction({ptr:__sym('inflateReset2'),args:['z_stream *','i32'],returns:'i32'});
/**
 * inflatePrime
 * @param {object|number|bigint|null} strm - z_stream *
 * @param {number} bits - i32
 * @param {number} value - i32
 * @returns {number} - i32
 */
export const inflatePrime = CFunction({ptr:__sym('inflatePrime'),args:['z_stream *','i32','i32'],returns:'i32'});
/**
 * inflateMark
 * @param {object|number|bigint|null} strm - z_stream *
 * @returns {bigint} - i64
 */
export const inflateMark = CFunction({ptr:__sym('inflateMark'),args:['z_stream *'],returns:'i64'});
/**
 * inflateGetHeader
 * @param {object|number|bigint|null} strm - z_stream *
 * @param {object|number|bigint|null} head - gz_header *
 * @returns {number} - i32
 */
export const inflateGetHeader = CFunction({ptr:__sym('inflateGetHeader'),args:['z_stream *','gz_header *'],returns:'i32'});
/**
 * inflateBack
 * @param {object|number|bigint|null} strm - z_stream *
 * @param {object|number|bigint|null} _in - function
 * @param {object|number|bigint|null} in_desc - void *
 * @param {object|number|bigint|null} out - function
 * @param {object|number|bigint|null} out_desc - void *
 * @returns {number} - i32
 */
export const inflateBack = CFunction({ptr:__sym('inflateBack'),args:['z_stream *','function','void *','function','void *'],returns:'i32'});
/**
 * inflateBackEnd
 * @param {object|number|bigint|null} strm - z_stream *
 * @returns {number} - i32
 */
export const inflateBackEnd = CFunction({ptr:__sym('inflateBackEnd'),args:['z_stream *'],returns:'i32'});
/**
 * zlibCompileFlags
 * @returns {bigint} - u64
 */
export const zlibCompileFlags = CFunction({ptr:__sym('zlibCompileFlags'),args:[],returns:'u64'});
/**
 * compress
 * @param {object|number|bigint|null} dest - Bytef *
 * @param {object|number|bigint|null} destLen - uLongf *
 * @param {object|number|bigint|null} source - Bytef *
 * @param {bigint|number} sourceLen - u64
 * @returns {number} - i32
 */
export const compress = CFunction({ptr:__sym('compress'),args:['Bytef *','uLongf *','Bytef *','u64'],returns:'i32'});
/**
 * compress2
 * @param {object|number|bigint|null} dest - Bytef *
 * @param {object|number|bigint|null} destLen - uLongf *
 * @param {object|number|bigint|null} source - Bytef *
 * @param {bigint|number} sourceLen - u64
 * @param {number} level - i32
 * @returns {number} - i32
 */
export const compress2 = CFunction({ptr:__sym('compress2'),args:['Bytef *','uLongf *','Bytef *','u64','i32'],returns:'i32'});
/**
 * compressBound
 * @param {bigint|number} sourceLen - u64
 * @returns {bigint} - u64
 */
export const compressBound = CFunction({ptr:__sym('compressBound'),args:['u64'],returns:'u64'});
/**
 * uncompress
 * @param {object|number|bigint|null} dest - Bytef *
 * @param {object|number|bigint|null} destLen - uLongf *
 * @param {object|number|bigint|null} source - Bytef *
 * @param {bigint|number} sourceLen - u64
 * @returns {number} - i32
 */
export const uncompress = CFunction({ptr:__sym('uncompress'),args:['Bytef *','uLongf *','Bytef *','u64'],returns:'i32'});
/**
 * uncompress2
 * @param {object|number|bigint|null} dest - Bytef *
 * @param {object|number|bigint|null} destLen - uLongf *
 * @param {object|number|bigint|null} source - Bytef *
 * @param {object|number|bigint|null} sourceLen - uLong *
 * @returns {number} - i32
 */
export const uncompress2 = CFunction({ptr:__sym('uncompress2'),args:['Bytef *','uLongf *','Bytef *','uLong *'],returns:'i32'});
/**
 * gzdopen
 * @param {number} fd - i32
 * @param {string|null} mode - cstring
 * @returns {number|bigint|null} - struct gzFile_s *
 */
export const gzdopen = CFunction({ptr:__sym('gzdopen'),args:['i32','cstring'],returns:'struct gzFile_s *'});
/**
 * gzbuffer
 * @param {object|number|bigint|null} file - struct gzFile_s *
 * @param {number} size - u32
 * @returns {number} - i32
 */
export const gzbuffer = CFunction({ptr:__sym('gzbuffer'),args:['struct gzFile_s *','u32'],returns:'i32'});
/**
 * gzsetparams
 * @param {object|number|bigint|null} file - struct gzFile_s *
 * @param {number} level - i32
 * @param {number} strategy - i32
 * @returns {number} - i32
 */
export const gzsetparams = CFunction({ptr:__sym('gzsetparams'),args:['struct gzFile_s *','i32','i32'],returns:'i32'});
/**
 * gzread
 * @param {object|number|bigint|null} file - struct gzFile_s *
 * @param {object|number|bigint|null} buf - void *
 * @param {number} len - u32
 * @returns {number} - i32
 */
export const gzread = CFunction({ptr:__sym('gzread'),args:['struct gzFile_s *','void *','u32'],returns:'i32'});
/**
 * gzfread
 * @param {object|number|bigint|null} buf - void *
 * @param {bigint|number} size - u64
 * @param {bigint|number} nitems - u64
 * @param {object|number|bigint|null} file - struct gzFile_s *
 * @returns {bigint} - u64
 */
export const gzfread = CFunction({ptr:__sym('gzfread'),args:['void *','u64','u64','struct gzFile_s *'],returns:'u64'});
/**
 * gzwrite
 * @param {object|number|bigint|null} file - struct gzFile_s *
 * @param {object|number|bigint|null} buf - void *
 * @param {number} len - u32
 * @returns {number} - i32
 */
export const gzwrite = CFunction({ptr:__sym('gzwrite'),args:['struct gzFile_s *','void *','u32'],returns:'i32'});
/**
 * gzfwrite
 * @param {object|number|bigint|null} buf - void *
 * @param {bigint|number} size - u64
 * @param {bigint|number} nitems - u64
 * @param {object|number|bigint|null} file - struct gzFile_s *
 * @returns {bigint} - u64
 */
export const gzfwrite = CFunction({ptr:__sym('gzfwrite'),args:['void *','u64','u64','struct gzFile_s *'],returns:'u64'});
/**
 * gzputs
 * @param {object|number|bigint|null} file - struct gzFile_s *
 * @param {string|null} s - cstring
 * @returns {number} - i32
 */
export const gzputs = CFunction({ptr:__sym('gzputs'),args:['struct gzFile_s *','cstring'],returns:'i32'});
/**
 * gzgets
 * @param {object|number|bigint|null} file - struct gzFile_s *
 * @param {string|null} buf - cstring
 * @param {number} len - i32
 * @returns {string} - cstring
 */
export const gzgets = CFunction({ptr:__sym('gzgets'),args:['struct gzFile_s *','cstring','i32'],returns:'cstring'});
/**
 * gzputc
 * @param {object|number|bigint|null} file - struct gzFile_s *
 * @param {number} c - i32
 * @returns {number} - i32
 */
export const gzputc = CFunction({ptr:__sym('gzputc'),args:['struct gzFile_s *','i32'],returns:'i32'});
/**
 * gzgetc
 * @param {object|number|bigint|null} file - struct gzFile_s *
 * @returns {number} - i32
 */
export const gzgetc = CFunction({ptr:__sym('gzgetc'),args:['struct gzFile_s *'],returns:'i32'});
/**
 * gzungetc
 * @param {number} c - i32
 * @param {object|number|bigint|null} file - struct gzFile_s *
 * @returns {number} - i32
 */
export const gzungetc = CFunction({ptr:__sym('gzungetc'),args:['i32','struct gzFile_s *'],returns:'i32'});
/**
 * gzflush
 * @param {object|number|bigint|null} file - struct gzFile_s *
 * @param {number} flush - i32
 * @returns {number} - i32
 */
export const gzflush = CFunction({ptr:__sym('gzflush'),args:['struct gzFile_s *','i32'],returns:'i32'});
/**
 * gzrewind
 * @param {object|number|bigint|null} file - struct gzFile_s *
 * @returns {number} - i32
 */
export const gzrewind = CFunction({ptr:__sym('gzrewind'),args:['struct gzFile_s *'],returns:'i32'});
/**
 * gzeof
 * @param {object|number|bigint|null} file - struct gzFile_s *
 * @returns {number} - i32
 */
export const gzeof = CFunction({ptr:__sym('gzeof'),args:['struct gzFile_s *'],returns:'i32'});
/**
 * gzdirect
 * @param {object|number|bigint|null} file - struct gzFile_s *
 * @returns {number} - i32
 */
export const gzdirect = CFunction({ptr:__sym('gzdirect'),args:['struct gzFile_s *'],returns:'i32'});
/**
 * gzclose
 * @param {object|number|bigint|null} file - struct gzFile_s *
 * @returns {number} - i32
 */
export const gzclose = CFunction({ptr:__sym('gzclose'),args:['struct gzFile_s *'],returns:'i32'});
/**
 * gzclose_r
 * @param {object|number|bigint|null} file - struct gzFile_s *
 * @returns {number} - i32
 */
export const gzclose_r = CFunction({ptr:__sym('gzclose_r'),args:['struct gzFile_s *'],returns:'i32'});
/**
 * gzclose_w
 * @param {object|number|bigint|null} file - struct gzFile_s *
 * @returns {number} - i32
 */
export const gzclose_w = CFunction({ptr:__sym('gzclose_w'),args:['struct gzFile_s *'],returns:'i32'});
/**
 * gzerror
 * @param {object|number|bigint|null} file - struct gzFile_s *
 * @param {object|number|bigint|null} errnum - int *
 * @returns {string} - cstring
 */
export const gzerror = CFunction({ptr:__sym('gzerror'),args:['struct gzFile_s *','int *'],returns:'cstring'});
/**
 * gzclearerr
 * @param {object|number|bigint|null} file - struct gzFile_s *
 * @returns {void}
 */
export const gzclearerr = CFunction({ptr:__sym('gzclearerr'),args:['struct gzFile_s *'],returns:'void'});
/**
 * adler32
 * @param {bigint|number} adler - u64
 * @param {object|number|bigint|null} buf - Bytef *
 * @param {number} len - u32
 * @returns {bigint} - u64
 */
export const adler32 = CFunction({ptr:__sym('adler32'),args:['u64','Bytef *','u32'],returns:'u64'});
/**
 * adler32_z
 * @param {bigint|number} adler - u64
 * @param {object|number|bigint|null} buf - Bytef *
 * @param {bigint|number} len - u64
 * @returns {bigint} - u64
 */
export const adler32_z = CFunction({ptr:__sym('adler32_z'),args:['u64','Bytef *','u64'],returns:'u64'});
/**
 * crc32
 * @param {bigint|number} crc - u64
 * @param {object|number|bigint|null} buf - Bytef *
 * @param {number} len - u32
 * @returns {bigint} - u64
 */
export const crc32 = CFunction({ptr:__sym('crc32'),args:['u64','Bytef *','u32'],returns:'u64'});
/**
 * crc32_z
 * @param {bigint|number} crc - u64
 * @param {object|number|bigint|null} buf - Bytef *
 * @param {bigint|number} len - u64
 * @returns {bigint} - u64
 */
export const crc32_z = CFunction({ptr:__sym('crc32_z'),args:['u64','Bytef *','u64'],returns:'u64'});
/**
 * crc32_combine_op
 * @param {bigint|number} crc1 - u64
 * @param {bigint|number} crc2 - u64
 * @param {bigint|number} op - u64
 * @returns {bigint} - u64
 */
export const crc32_combine_op = CFunction({ptr:__sym('crc32_combine_op'),args:['u64','u64','u64'],returns:'u64'});
/**
 * deflateInit_
 * @param {object|number|bigint|null} strm - z_stream *
 * @param {number} level - i32
 * @param {string|null} version - cstring
 * @param {number} stream_size - i32
 * @returns {number} - i32
 */
export const deflateInit_ = CFunction({ptr:__sym('deflateInit_'),args:['z_stream *','i32','cstring','i32'],returns:'i32'});
/**
 * inflateInit_
 * @param {object|number|bigint|null} strm - z_stream *
 * @param {string|null} version - cstring
 * @param {number} stream_size - i32
 * @returns {number} - i32
 */
export const inflateInit_ = CFunction({ptr:__sym('inflateInit_'),args:['z_stream *','cstring','i32'],returns:'i32'});
/**
 * deflateInit2_
 * @param {object|number|bigint|null} strm - z_stream *
 * @param {number} level - i32
 * @param {number} method - i32
 * @param {number} windowBits - i32
 * @param {number} memLevel - i32
 * @param {number} strategy - i32
 * @param {string|null} version - cstring
 * @param {number} stream_size - i32
 * @returns {number} - i32
 */
export const deflateInit2_ = CFunction({ptr:__sym('deflateInit2_'),args:['z_stream *','i32','i32','i32','i32','i32','cstring','i32'],returns:'i32'});
/**
 * inflateInit2_
 * @param {object|number|bigint|null} strm - z_stream *
 * @param {number} windowBits - i32
 * @param {string|null} version - cstring
 * @param {number} stream_size - i32
 * @returns {number} - i32
 */
export const inflateInit2_ = CFunction({ptr:__sym('inflateInit2_'),args:['z_stream *','i32','cstring','i32'],returns:'i32'});
/**
 * inflateBackInit_
 * @param {object|number|bigint|null} strm - z_stream *
 * @param {number} windowBits - i32
 * @param {object|number|bigint|null} window - unsigned char *
 * @param {string|null} version - cstring
 * @param {number} stream_size - i32
 * @returns {number} - i32
 */
export const inflateBackInit_ = CFunction({ptr:__sym('inflateBackInit_'),args:['z_stream *','i32','unsigned char *','cstring','i32'],returns:'i32'});
/**
 * gzgetc_
 * @param {object|number|bigint|null} file - struct gzFile_s *
 * @returns {number} - i32
 */
export const gzgetc_ = CFunction({ptr:__sym('gzgetc_'),args:['struct gzFile_s *'],returns:'i32'});
/**
 * gzopen
 * @param {string|null} a0 - cstring
 * @param {string|null} a1 - cstring
 * @returns {number|bigint|null} - struct gzFile_s *
 */
export const gzopen = CFunction({ptr:__sym('gzopen'),args:['cstring','cstring'],returns:'struct gzFile_s *'});
/**
 * gzseek
 * @param {object|number|bigint|null} a0 - struct gzFile_s *
 * @param {bigint|number} a1 - i64
 * @param {number} a2 - i32
 * @returns {bigint} - i64
 */
export const gzseek = CFunction({ptr:__sym('gzseek'),args:['struct gzFile_s *','i64','i32'],returns:'i64'});
/**
 * gztell
 * @param {object|number|bigint|null} a0 - struct gzFile_s *
 * @returns {bigint} - i64
 */
export const gztell = CFunction({ptr:__sym('gztell'),args:['struct gzFile_s *'],returns:'i64'});
/**
 * gzoffset
 * @param {object|number|bigint|null} a0 - struct gzFile_s *
 * @returns {bigint} - i64
 */
export const gzoffset = CFunction({ptr:__sym('gzoffset'),args:['struct gzFile_s *'],returns:'i64'});
/**
 * adler32_combine
 * @param {bigint|number} a0 - u64
 * @param {bigint|number} a1 - u64
 * @param {bigint|number} a2 - i64
 * @returns {bigint} - u64
 */
export const adler32_combine = CFunction({ptr:__sym('adler32_combine'),args:['u64','u64','i64'],returns:'u64'});
/**
 * crc32_combine
 * @param {bigint|number} a0 - u64
 * @param {bigint|number} a1 - u64
 * @param {bigint|number} a2 - i64
 * @returns {bigint} - u64
 */
export const crc32_combine = CFunction({ptr:__sym('crc32_combine'),args:['u64','u64','i64'],returns:'u64'});
/**
 * crc32_combine_gen
 * @param {bigint|number} a0 - i64
 * @returns {bigint} - u64
 */
export const crc32_combine_gen = CFunction({ptr:__sym('crc32_combine_gen'),args:['i64'],returns:'u64'});
/**
 * zError
 * @param {number} a0 - i32
 * @returns {string} - cstring
 */
export const zError = CFunction({ptr:__sym('zError'),args:['i32'],returns:'cstring'});
/**
 * inflateSyncPoint
 * @param {object|number|bigint|null} a0 - z_stream *
 * @returns {number} - i32
 */
export const inflateSyncPoint = CFunction({ptr:__sym('inflateSyncPoint'),args:['z_stream *'],returns:'i32'});
/**
 * get_crc_table
 * @returns {number|bigint|null} - z_crc_t *
 */
export const get_crc_table = CFunction({ptr:__sym('get_crc_table'),args:[],returns:'z_crc_t *'});
/**
 * inflateUndermine
 * @param {object|number|bigint|null} a0 - z_stream *
 * @param {number} a1 - i32
 * @returns {number} - i32
 */
export const inflateUndermine = CFunction({ptr:__sym('inflateUndermine'),args:['z_stream *','i32'],returns:'i32'});
/**
 * inflateValidate
 * @param {object|number|bigint|null} a0 - z_stream *
 * @param {number} a1 - i32
 * @returns {number} - i32
 */
export const inflateValidate = CFunction({ptr:__sym('inflateValidate'),args:['z_stream *','i32'],returns:'i32'});
/**
 * inflateCodesUsed
 * @param {object|number|bigint|null} a0 - z_stream *
 * @returns {bigint} - u64
 */
export const inflateCodesUsed = CFunction({ptr:__sym('inflateCodesUsed'),args:['z_stream *'],returns:'u64'});
/**
 * inflateResetKeep
 * @param {object|number|bigint|null} a0 - z_stream *
 * @returns {number} - i32
 */
export const inflateResetKeep = CFunction({ptr:__sym('inflateResetKeep'),args:['z_stream *'],returns:'i32'});
/**
 * deflateResetKeep
 * @param {object|number|bigint|null} a0 - z_stream *
 * @returns {number} - i32
 */
export const deflateResetKeep = CFunction({ptr:__sym('deflateResetKeep'),args:['z_stream *'],returns:'i32'});
/**
 * gzvprintf
 * @param {object|number|bigint|null} file - struct gzFile_s *
 * @param {string|null} format - cstring
 * @param {object|number|bigint|null} va - struct __va_list_tag *
 * @returns {number} - i32
 */
export const gzvprintf = CFunction({ptr:__sym('gzvprintf'),args:['struct gzFile_s *','cstring','struct __va_list_tag *'],returns:'i32'});

// Skipped (unsupported):
//   - gzprintf: variadic functions are not supported
