#!/usr/bin/env qjsm
/* examples/cairo.js -- draw a simple scene and save it as a PNG, using
 * lib/cairo.js (generated by tools/gen-bindings.js from cairo.h, see
 * doc/c-function.md).
 *
 * Usage: qjsm examples/cairo.js [out.png]
 */
import * as cairo from '../lib/cairo.js';
import { CAIRO_FORMAT_ARGB32, CAIRO_STATUS_SUCCESS, CAIRO_FONT_SLANT_NORMAL, CAIRO_FONT_WEIGHT_BOLD } from '../lib/cairo.js';

function main(args) {
  const outPath = args[0] || '.tmp/cairo-example.png';
  const width = 320,
    height = 240;

  const surface = cairo.cairo_image_surface_create(CAIRO_FORMAT_ARGB32, width, height);
  const cr = cairo.cairo_create(surface);

  cairo.cairo_set_source_rgb(cr, 1, 1, 1);
  cairo.cairo_paint(cr);

  cairo.cairo_set_source_rgb(cr, 0.2, 0.4, 0.9);
  cairo.cairo_rectangle(cr, 20, 20, width - 40, height - 40);
  cairo.cairo_fill(cr);

  cairo.cairo_set_source_rgba(cr, 1, 0.8, 0, 0.9);
  cairo.cairo_arc(cr, width / 2, height / 2, 70, 0, 2 * Math.PI);
  cairo.cairo_fill(cr);

  cairo.cairo_set_source_rgb(cr, 0, 0, 0);
  cairo.cairo_set_line_width(cr, 3);
  cairo.cairo_move_to(cr, 40, height - 40);
  cairo.cairo_curve_to(cr, width / 3, 40, (2 * width) / 3, height - 40, width - 40, 40);
  cairo.cairo_stroke(cr);

  cairo.cairo_select_font_face(cr, 'sans-serif', CAIRO_FONT_SLANT_NORMAL, CAIRO_FONT_WEIGHT_BOLD);
  cairo.cairo_set_font_size(cr, 28);
  cairo.cairo_set_source_rgb(cr, 1, 1, 1);
  cairo.cairo_move_to(cr, 30, 40);
  cairo.cairo_show_text(cr, 'qjs-ffi + cairo');

  const status = cairo.cairo_surface_write_to_png(surface, outPath);

  cairo.cairo_destroy(cr);
  cairo.cairo_surface_destroy(surface);

  if(status !== CAIRO_STATUS_SUCCESS) throw new Error('cairo_surface_write_to_png failed: cairo_status_t ' + status);

  console.log('wrote', outPath, width + 'x' + height);
}

main(scriptArgs.slice(1));
