#!/usr/bin/env qjsm
/* examples/freetype.js -- render one glyph to an ASCII-art bitmap using
 * lib/freetype.js (generated by tools/gen-bindings.js from freetype.h, see
 * doc/c-function.md).
 *
 * Usage: qjsm examples/freetype.js [font.ttf] [char] [pixel-size]
 */
import * as ft from '../lib/freetype.js';
import { pointerSize, toArrayBuffer, toString } from 'ffi';

const FT_LOAD_RENDER = 1 << 2;

/* FT_FaceRec/FT_GlyphSlotRec/FT_Bitmap field offsets, measured with
 * offsetof() against the system freetype2 headers (see .tmp/offs.c) --
 * these structs aren't exposed as FFIType-describable layouts, so reading
 * them means going straight at the ABI. 64-bit Linux only, consistent with
 * the rest of this project's little-endian/LP64 assumption.
 */
const FACE_FAMILY_NAME = 40; // FT_String* (8)
const FACE_NUM_GLYPHS = 32; // FT_Long (8)
const FACE_GLYPH = 152; // FT_GlyphSlot (8)
const SLOT_BITMAP = 152; // FT_Bitmap (embedded)
const SLOT_BITMAP_LEFT = 192; // FT_Int (4)
const SLOT_BITMAP_TOP = 196; // FT_Int (4)
const BITMAP_ROWS = 0; // unsigned int (4)
const BITMAP_WIDTH = 4; // unsigned int (4)
const BITMAP_PITCH = 8; // int (4)
const BITMAP_BUFFER = 16; // unsigned char* (8)

function readPtr(buf, ofs = 0) {
  return pointerSize === 8 ? new DataView(buf).getBigUint64(ofs, true) : new DataView(buf).getUint32(ofs, true);
}

function check(err, what) {
  if(err) throw new Error(what + ' failed: FT_Error ' + err);
}

/* 10-level gray ramp, darkest-first, for an 8bpp FT_PIXEL_MODE_GRAY bitmap. */
const RAMP = ' .:-=+*#%@';

/* Reads the embedded FT_Bitmap at byte offset `ofs` within an
 * already-fetched glyph-slot buffer `slot` -- kept as an offset rather than
 * a second native pointer to avoid BigInt/Number pointer arithmetic
 * (pointerSize === 8 makes every pointer value a BigInt, and BigInt + Number
 * throws).
 */
function renderAscii(slot, ofs) {
  const rows = new DataView(slot).getUint32(ofs + BITMAP_ROWS, true);
  const width = new DataView(slot).getUint32(ofs + BITMAP_WIDTH, true);
  const pitch = new DataView(slot).getInt32(ofs + BITMAP_PITCH, true);
  const bufferPtr = readPtr(slot, ofs + BITMAP_BUFFER);

  if(!rows || !width || !bufferPtr) {
    console.log('(empty glyph -- try a visible, non-space character)');
    return;
  }

  const pixels = new Uint8Array(toArrayBuffer(bufferPtr, rows * Math.abs(pitch)));

  for(let y = 0; y < rows; y++) {
    let line = '';
    for(let x = 0; x < width; x++) line += RAMP[Math.min(RAMP.length - 1, (pixels[y * Math.abs(pitch) + x] * RAMP.length) >> 8)];
    console.log(line);
  }
}

function main(args) {
  const fontPath = args[0] || '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf';
  const char = args[1] || 'A';
  const pixelSize = +(args[2] || 48);

  const libraryBuf = new ArrayBuffer(pointerSize);
  check(ft.FT_Init_FreeType(libraryBuf), 'FT_Init_FreeType');
  const library = readPtr(libraryBuf);

  const faceBuf = new ArrayBuffer(pointerSize);
  check(ft.FT_New_Face(library, fontPath, 0, faceBuf), 'FT_New_Face(' + fontPath + ')');
  const face = readPtr(faceBuf);

  const faceRec = toArrayBuffer(face, 160);
  const familyName = toString(readPtr(faceRec, FACE_FAMILY_NAME));
  const numGlyphs = new DataView(faceRec).getBigUint64(FACE_NUM_GLYPHS, true);
  console.log('font:', familyName, '(' + numGlyphs + ' glyphs)');

  check(ft.FT_Set_Pixel_Sizes(face, 0, pixelSize), 'FT_Set_Pixel_Sizes');
  check(ft.FT_Load_Char(face, char.codePointAt(0), FT_LOAD_RENDER), 'FT_Load_Char(' + JSON.stringify(char) + ')');

  const glyph = readPtr(toArrayBuffer(face, 160), FACE_GLYPH);
  const slot = toArrayBuffer(glyph, 200);
  console.log('glyph:', JSON.stringify(char), 'origin (' + new DataView(slot).getInt32(SLOT_BITMAP_LEFT, true) + ',' + new DataView(slot).getInt32(SLOT_BITMAP_TOP, true) + ')');

  renderAscii(slot, SLOT_BITMAP);

  ft.FT_Done_Face(face);
  ft.FT_Done_FreeType(library);
}

main(scriptArgs.slice(1));
