#!/usr/bin/env qjsm
/* examples/sdl2.js -- create an off-screen window, draw a raw pixel
 * gradient straight into its surface, and read a pixel back to prove the
 * write landed. Uses lib/sdl2.js (generated by tools/gen-bindings.js from
 * the SDL.h headers, see doc/c-function.md).
 *
 * Runs headless by default (SDL_VIDEODRIVER=dummy, no real display needed).
 * Usage: qjsm examples/sdl2.js
 */
import * as std from 'std';
import * as sdl from '../lib/sdl2.js';
import { pointerSize, toArrayBuffer } from 'ffi';

const SDL_INIT_VIDEO = 0x20;
const SDL_WINDOWPOS_UNDEFINED = 0x1fff0000;

/* SDL_Surface field offsets, measured with offsetof() against the system
 * SDL2 headers (see .tmp/offs.c) -- format/w/h/pitch/pixels aren't exposed
 * as FFIType-describable layouts, so reading/writing them means going
 * straight at the ABI. 64-bit Linux only.
 */
const SURFACE_W = 16; // int (4)
const SURFACE_H = 20; // int (4)
const SURFACE_PITCH = 24; // int (4)
const SURFACE_PIXELS = 32; // void* (8)

function readPtr(buf, ofs = 0) {
  return pointerSize === 8 ? new DataView(buf).getBigUint64(ofs, true) : new DataView(buf).getUint32(ofs, true);
}

function check(cond, what) {
  if(!cond) throw new Error(what + ' failed: ' + sdl.SDL_GetError());
}

function main() {
  if(std.getenv('SDL_VIDEODRIVER') === undefined) std.setenv('SDL_VIDEODRIVER', 'dummy');

  check(sdl.SDL_Init(SDL_INIT_VIDEO) === 0, 'SDL_Init');

  const width = 64,
    height = 48;
  const window = sdl.SDL_CreateWindow('qjs-ffi + SDL2', SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, width, height, 0);
  check(window, 'SDL_CreateWindow');

  const surface = sdl.SDL_GetWindowSurface(window);
  check(surface, 'SDL_GetWindowSurface');

  const surfaceView = toArrayBuffer(surface, 40);
  const w = new DataView(surfaceView).getInt32(SURFACE_W, true);
  const h = new DataView(surfaceView).getInt32(SURFACE_H, true);
  const pitch = new DataView(surfaceView).getInt32(SURFACE_PITCH, true);
  const pixelsPtr = readPtr(surfaceView, SURFACE_PIXELS);
  console.log('surface', w + 'x' + h, 'pitch', pitch);

  // Raw pixel write: a horizontal red -> blue gradient, straight into the
  // native ARGB8888 buffer -- no SDL_MapRGB/SDL_FillRect needed, since we
  // already know the byte layout this software surface uses on this ABI.
  const pixels = new Uint32Array(toArrayBuffer(pixelsPtr, h * pitch, false));
  const stride = pitch / 4;

  for(let y = 0; y < h; y++)
    for(let x = 0; x < w; x++) {
      const red = Math.floor((x / (w - 1)) * 255);
      const blue = 255 - red;
      pixels[y * stride + x] = (0xff << 24) | (red << 16) | (0 << 8) | blue;
    }

  check(sdl.SDL_UpdateWindowSurface(window) === 0, 'SDL_UpdateWindowSurface');

  const first = pixels[0].toString(16).padStart(8, '0');
  const last = pixels[w - 1].toString(16).padStart(8, '0');
  console.log('row 0 first pixel 0x' + first + ', last pixel 0x' + last);

  sdl.SDL_DestroyWindow(window);
  sdl.SDL_Quit();
}

main();
